### ISSUE TITLE
I have some problems with this addon in blender 2.8

### ISSUE THREAD

**Issue by abd123-mc** [TheDuckCow/MCprep#102]
I have a problem with preparing materials in blender 2.8,its so Different from 2.79 i cant animating textures and when i import a opj world file is only as one opject not Each block type alone
  -Even when I chose "export individual blocks" in mineways- and when i spawn any mesh swap- like redston lamp- it spawn two blocks and in mesh swap and preparing materials, settings do not change, however i change them,its not working and part of the Mish Swap list does not appear - Moreover, none of the menu options are already working😁-
I think everyone who uses this addon in version 2.8 suffers from these problems
Is it a problem in the addon or what?🤔
And Can those problems be solved?🤔🤔

**Comment by TheDuckCow** [comment]
Hi there, sorry you have been experiencing issues. I'll break down the different things you mentioned, and ask follow up questions for each:

- world importing issues: This is actually a change to blender itself, not MCprep; OBJ files now be imported with all objects merged together. To fix, go into edit mode (tab), and press p - separate by materials. Exit material mode, and now you have separate objects for everything, which will make things easier. 
- Prep materials issues: Is your only issue that you can't animate textures? Are you using jmc2obj to generate the world obj file?
- Meshswap issues: It could be that you have moved (in edit mode) your world object or changed the origin, these would mess up meshswap. But if you want me to debug further, please share the obj file (I don't need the textures, just the OBJ file) and I can debug further.

**Comment by abd123-mc** [comment]
OK , it seems that the problem of importing the world was the cause of those problems, on the whole, thank you Sent from Mail for Windows 10 From: Patrick W. CrawfordSent: Wednesday, January 8, 2020 5:01 AMTo: TheDuckCow/MCprepCc: abd123-mc; State changeSubject: Re: [TheDuckCow/MCprep] I have some problems with this addon in blender 2.8 (#102) Hi there, sorry you have been experiencing issues. I'll break down the different things you mentioned, and ask follow up questions for each:world importing issues: This is actually a change to blender itself, not MCprep; OBJ files now be imported with all objects merged together. To fix, go into edit mode (tab), and press p - separate by materials. Exit material mode, and now you have separate objects for everything, which will make things easier.Prep materials issues: Is your only issue that you can't animate textures? Are you using jmc2obj to generate the world obj file?Meshswap issues: It could be that you have moved (in edit mode) your world object or changed the origin, these would mess up meshswap. But if you want me to debug further, please share the obj file (I don't need the textures, just the OBJ file) and I can debug further.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TheDuckCow** [comment]
Glad to hear it is working now, let me know if there are any other issues that come up - closing this ticket in the meantime.
