### ISSUE TITLE
When MeshSwap,the places of the blocks are not true.

### ISSUE THREAD

**Issue by ghost** [TheDuckCow/MCprep#103]
When MeshSwap,the places of the blocks are not true.
![批注 2020-01-16 104601](https://user-images.githubusercontent.com/50913224/72489378-daf03000-384e-11ea-9f61-4f152d474b02.png)

**Comment by TheDuckCow** [comment]
Sorry for not responding until now, I had mentally grouped this with other meshswap placement issues. I'll followup later to see if the next MCprep update solves the issue here (not out just yet).

**Comment by TheDuckCow** [comment]
As per other reports, I believe this issue has been resolved in the latest v3.2.3 update (and is now on v3.2.3.1). Please let me know if this is not the case, and be sure to either use the in-blender updater, or fully remove the addon and install it again fresh to make sure you get the updated meshswap file.
