### ISSUE TITLE
Spawner section is missing from MCPrep tab in 2.8

### ISSUE THREAD

**Issue by SweetPalindrome** [TheDuckCow/MCprep#104]
I just installed everything & following along in a video, I noticed I don't have a *Spawner* section in the MCPrep tab. I'm in Blender 2.8, and I can add a mob using the ADD button, but the section highlighted in your video is missing. What have I done to break things so fast?

**Comment by TheDuckCow** [comment]
Hi there, can you share which video you were comparing against? It is possible an older video shows an older UI. At the moment, it should look something like the screenshot attached. Note you must be in object mode for the panel to show up, it will not show if in pose mode.

**Comment by SweetPalindrome** [comment]
Thank you! I was stuck in pose mode.

**Comment by TheDuckCow** [comment]
Thanks for clarifying that - I am planning to make a change so that this is a bit more obvious to users by way of a label instead of just disappearing.
