### ISSUE TITLE
[ISSUE] Dont have mob spawner in my mcprep tab

### ISSUE THREAD

**Issue by TimRambo** [TheDuckCow/MCprep#105]
It was there before now its gone i am on the latest blender via steam.
[https://timrambo.eu/i/01s.png](url)

**Comment by TimRambo** [comment]
i am stupid.

**Comment by TheDuckCow** [comment]
Hi there - just curious, was the issue that you were in pose or edit mode? If so, you are not the first to think it has disappeared - I think I'll be changing it so the panel still shows up, but explicitly has a label to return to object mode.
