### ISSUE TITLE
World showing as white when imported in both material andd rendered view.

### ISSUE THREAD

**Issue by EliteRanger** [TheDuckCow/MCprep#109]
Started doing animations a few weeks ago and all was well. Earlier today, when importing a world, the world appeared as white. When attempting to "prep materials" the error "Nothing modified, be sure you selected objects with existing materials!" appeared. I have read that it may be the texture file path needs to be changed. How would I do this?

Many thanks!
![Annotation 2020-03-17 173133](https://user-images.githubusercontent.com/62302773/76884193-3487d180-6875-11ea-9731-35ccc7117b86.png)
![Annotation 2020-03-17 173018](https://user-images.githubusercontent.com/62302773/76884198-36ea2b80-6875-11ea-8b67-5d7400ebdf2b.png)

**Comment by TheDuckCow** [comment]
Sorry for the delayed reply. If it comes in completely white even before using MCprep, it likely means it wasn't exported with materials. There should be both an obj as well as an mtl file, and in whatever you used for exporting you should ensure you select separate materials per blocks. Hope this helps.

**Comment by TheDuckCow** [comment]
Following up here, did you have any luck with this?

**Comment by TheDuckCow** [comment]
Closing in the meantime - I've seen this issue crop up when users have imported worlds where the .mtl file was missing for instance. Double check both the obj and mtl files are generated, and the textures themselves.
