### ISSUE TITLE
owait

### ISSUE THREAD

**Issue by theawesomecharles** [TheDuckCow/MCprep#11]
O_O???

**Comment by TheDuckCow** [comment]
Can you include a screenshot of the spawner panel? Is the panel showing, but maybe collapsed? Do any buttons show up at all or drop downs ? Alternatively,  if you are on Windows can you open from the window menu at the very top "show console" and share what ever errors might show up there after trying to open the panel?

Finally, which version of MCprep are you using?

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Resolving due to updated title and stance, glad it's worked out 👍
