### ISSUE TITLE
i cant check mcprep so i will never use you and i willcfind you and kill you

### ISSUE THREAD

**Issue by yeetmybeetle** [TheDuckCow/MCprep#110]

**Comment by TheDuckCow** [comment]
I'm just going to close this issue, unless you have an actual issue to report (....with a description/screenshot, and one fewer death threat).

**Comment by yeetmybeetle** [comment]
Lol im just 9 Sent from Mail for Windows 10 From: Patrick W. CrawfordSent: Monday, April 6, 2020 6:50 AMTo: TheDuckCow/MCprepCc: yeetmybeetle; AuthorSubject: Re: [TheDuckCow/MCprep] i cant check mcprep so i will never use you and i willcfind you and kill you (#110) I'm just going to close this issue, unless you have an actual issue to report (....with a description/screenshot, and one fewer death threat).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
