### ISSUE TITLE
no mobs visible in spawner box

### ISSUE THREAD

**Issue by minetekkaz** [TheDuckCow/MCprep#111]
I can't see any mobs/rigs available in spawner. I've tried reloading assets and blender 2.8 only crashes. Any idea what could be causing this? Kind regards, Dan

**Comment by TheDuckCow** [comment]
Can you share a screenshot of the advanced settings under the mob panel? You'll also see a button there for resetting the mob spawner folder path. Also worth checking out that folderpath manually to see if there are rigs there.

**Comment by TheDuckCow** [comment]
Just following up here, did you have any luck?

**Comment by TheDuckCow** [comment]
Closing in the meantime - let me know if this is still an issue.
