### ISSUE TITLE
MCPrep Traceback error

### ISSUE THREAD

**Issue by Exendx** [TheDuckCow/MCprep#114]
![image](https://user-images.githubusercontent.com/29308769/80321030-3a0efa80-87d7-11ea-9d71-fc1b821b9300.png)

any fix?

**Comment by TheDuckCow** [comment]
Yes - the release coming in the next couple days will address this. Thanks for reporting!

**Comment by TheDuckCow** [comment]
Release is now out, thanks for reporting.
