### ISSUE TITLE
Issue i think

### ISSUE THREAD

**Issue by MadnessTeahmGamin** [TheDuckCow/MCprep#116]
am trying to do a player on blender and it keep doing this 
![image](https://user-images.githubusercontent.com/64515729/80561310-a17ca400-89a9-11ea-94bb-2361946e5fc6.png)

and idk why

**Comment by TheDuckCow** [comment]
Looks like a custom rig, so not sure I can fully answer the question for you. Does the rig look ok in the original file it came from? Have you tried using render view or render an image of the character to see that it's not a viewport issue? Consider also selecting the whole rig, and pressing the "prep materials" button, that might fix it as well (.. or make it worse, depending on how materials for the rig was setup).

**Comment by MadnessTeahmGamin** [comment]
i did the Render and it shows a steve skin i tried the prep materials it says no materials found on selected object....

**Comment by TheDuckCow** [comment]
If it works in render, then most likely your issue is selecting the active image for the rig. Are you in cycles/Eevee or Blender internal?

Also for the short term, using solid mode should be workable as well.
