### ISSUE TITLE
Help when i try to tick the addon i cant tick it

### ISSUE THREAD

**Issue by Theheadlessadmin** [TheDuckCow/MCprep#12]

**Comment by TheDuckCow** [comment]
Hello,

Make sure you download the correct zip file, that is, from: http://theduckcow.com/dev/blender/mcprep-download/

Then make sure you install the zip file on its own. Please let me know if that still does not work, and let me know your blender version (should be 2.72+)

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Closing for staleness.
