### ISSUE TITLE
"Nothing modified, be sure you selected objects with existing materials!" error when using prep materials despite all selected objects having materials, and textures imported into blender.

### ISSUE THREAD

**Issue by lucianojamimbo** [TheDuckCow/MCprep#121]
Here's a short video demonstrating the problem [on youtube](https://www.youtube.com/watch?v=T8a1Azwdp8s&feature=youtu.be)

The blender version is 2.82.7, and the obj was generated through jmc2obj.

all the required textures are imported into blender, and all objects have materials.

**Comment by TheDuckCow** [comment]
Thanks for sharing the video, definitely helps.

based on the video, it looks like the obj imported with *blank materials*, ie either a missing material .mtl file OR disconnected textures. You could tell this if you go into the shader editor of any of the raw materials, and find that no images are loaded in the actual image block. It is odd that your image editor does show all the images loaded, but I also see that they are disconnected from any materials (have 0's next to them).

I'd try again from a fresh blend file, see if there are any textures immediately after loading (before prepping materials); if there aren't, then you'll need to try re-exporting either the world or the textures as something went awry.

**Comment by lucianojamimbo** [comment]
Turns out that this issue was caused by me not exporting the textures from jmc2obj before the .obj and .mtl
