### ISSUE TITLE
I cant see it

### ISSUE THREAD

**Issue by HarveyAnimates** [TheDuckCow/MCprep#126]
Its not appearing in preferences (Im on chromebook)

**Comment by bytzo** [comment]
Blender is not officially supported on ChromeOS. However, if you have managed to port it somehow, you must first install the add-on for it to appear in preferences.

To do this, first [download the latest release](https://github.com/TheDuckCow/MCprep/releases/latest) of MCprep as a `.zip` file and save it to a local directory. Then, head over to the Blender preferences pane and select "Add-ons." Press the install button in the upper right hand corner, and select the `.zip` file you downloaded earlier. Finally, press "Install Add-on" after selecting the `.zip` file. The MCprep addon should now appear in the preferences pane. If not, click the refresh button. Use the checkbox on the left of the MCprep icon to enable the addon.

For the official instructions, see [README.md](https://github.com/TheDuckCow/MCprep/blob/master/README.md).

**Comment by TheDuckCow** [comment]
@bytzo thanks for helping provide the info here, much appreciated!

@HarveyAnimates see the response, but I am curious to hear how you are running blender - is it through a service, or through one of the [methods here](https://chromeunboxed.com/three-ways-to-install-blender-3d-software-on-your-chromebook/)? If it's actually installed and running natively on the machine (as opposed to streamed over a web browser), then I'd expect the same installation steps to apply. Let me know!

**Comment by HarveyAnimates** [comment]
Wait I have it and its working agan so idk

**Comment by TheDuckCow** [comment]
Ok - closing in the meantime, though I'm still curious how you have blender running (are you running linux on the Chromebook?)

**Comment by HarveyAnimates** [comment]
Rollapp
