### ISSUE TITLE
How do I remove the facial features? (Auto-Made Eyes and Irises for example.)

### ISSUE THREAD

**Issue by ImSloke** [TheDuckCow/MCprep#128]
Probably a dumb question... I couldn't find the answer anywhere. :(

**Comment by TheDuckCow** [comment]
What do you want to remove - the eyes/mouth painted into the textures themselves? Or, remove the actual mesh features for eyes/mouth/eyes?

If the first, then go into gimp/photoshop/whatever/even blender's image painting editor, and overwrite the pixels for those features in the head texture.

![paint out](https://user-images.githubusercontent.com/2958461/83319381-feb77f80-a20b-11ea-93bc-4889379dc841.png)


If the second, I suggest using the "Simple" rig found under the spawner, it doesn't have eyes/mouths in the mesh itself.

![simple player](https://user-images.githubusercontent.com/2958461/83319318-746f1b80-a20b-11ea-8336-4f48a7a480bd.png)

**Comment by ImSloke** [comment]
Omg, I'm not smart. Why didn't I try this... Thanks!

**Comment by TheDuckCow** [comment]
Glad this helped!
