### ISSUE TITLE
How do I use the meshswap for 3D objects

### ISSUE THREAD

**Issue by Colcifer** [TheDuckCow/MCprep#132]
Im a little new at this but it keeps on duplicating the fire blocks a lot on every fire block and it has like an alpha texture, and then the grass doesn't become 3d

**Comment by TheDuckCow** [comment]
Hi there! Sorry for the delay - could you share a screenshot? Also make sure that you didn't move or translate the world at all, and that you selected either jmc2obj or Mineways based on what you used to import the world. 

Also double check that your scale is 1:1 (ie 1 block has a width of 1 blender unit).

**Comment by TheDuckCow** [comment]
Just a quick follow up, closing the issue in the meantime but let me know if the above response didn't yet.
