### ISSUE TITLE
I can't Enable the Plugin

### ISSUE THREAD

**Issue by Tgg1337** [TheDuckCow/MCprep#134]
I can't enable this Plugin

https://ibb.co/Jv2nDKZ (Error Message)

**Comment by ChiefEYT** [comment]
I've had the same problem with blender 2.83. someone told me to uninstall mcprep then enable it. I haven't tried it yet but it could help.

**Comment by ChiefEYT** [comment]
nevermind it didnt help

**Comment by Tgg1337** [comment]
Ok

ChiefEYT <notifications@github.com> schrieb am Fr., 19. Juni 2020, 06:00:

**Comment by TheDuckCow** [comment]
Make sure you are installing the .zip as per [this video](https://www.youtube.com/watch?v=Z8fMRFAXG-k&list=PL8X_CzUEVBfaa9PD9lWm4HdQCxUhl62Zb&index=2), the error makes me think something else was selected? If you are still having the issue, feel free to screen record and share back so I can help further, as the error itself isn't even MCprep code, but what Blender runs when installing an expected.zip (like MCprep) or .py single-file addon.

**Comment by agoldenlife** [comment]
Add another person to this issue.  Running blender 2.83.3.  A couple things to note:

1. The video says go to "File" then "User Preferences"  This does not exist in the windows installation for 2.83.3.  Instead you have to go to "Edit"  then "Preferences"
2. When you attempt to install, I do not have a button that says "Install
from file".  I only have a button that states "Install Add On".  Mine is lower right, your was top right as well.

The installer says it installs successfully, but the add on remains grayed out.  Let me know if I can do anything to help troubleshoot further.  I have uninstalled and installed the addon several times.

Attached you will find a video (.mp4) in the zip file that I recorded of my install and results.  Hopefully that is helpful.

[MCPrep add on to Blender no worky.zip](https://github.com/TheDuckCow/MCprep/files/4933146/MCPrep.add.on.to.Blender.no.worky.zip)

**Comment by Tgg1337** [comment]
now it's working and i've had this in a zip file and threre was the same problem
