### ISSUE TITLE
MCprep texture swap not working [jmc2obj]

### ISSUE THREAD

**Issue by AliCaliK1** [TheDuckCow/MCprep#135]
when I swap to realistico, blender said there is 12 materials affected, yet there is no change to the textures.

**Comment by TheDuckCow** [comment]
Sorry you're having issues - difficult to troubleshoot each pack, but can you do the following?
1) Go through and try swapping individual blocks one by one to see which ones are being updated
2) Show a before & after render (not viewport) of an example block
3) Show the same block's color map, to indicate what you expect it should look like
3) Share with me the exact link or download of the realistico pack you are using, ie same version and everything, this way I can go in and debug further

Also, are hoping to bring in normal and specular maps, or just change the primary color map?

**Comment by TheDuckCow** [comment]
Following up here after quite awhile, any updates or did you manage to get this working better?

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime - but please reach out if you have more information!
