### ISSUE TITLE
Incorrect normal and/or specular texture application for some blocks

### ISSUE THREAD

**Issue by bytzo** [TheDuckCow/MCprep#137]
For some blocks, an incorrect normal and/or specular texture is applied to a material. This is due to the way textures are mapped to the materials. It appears that searching for more generalized material names instead of searching for strict material names causes this issue.

Below is an example with 2 affcted blocks (wood and stone).
![image](https://user-images.githubusercontent.com/55573462/85822209-30e6cf00-b72f-11ea-9e39-d639fc21d711.png)
_(rendered in Cycles with 32 samples)_
Here, incorrect normal and specular maps are being applied to the oak logs, due to MCprep finding `oak_log_top_n` and `oak_log_top_s` before finding the correct `oak_log_n` and `oak_log_s` maps. However, the color map is correct.

Additionally, the incorrect specular map is being applied to the stone block. Since the resource pack used does not have a stone specular image, MCprep continues looking until it finds an image with "stone" in the name, which happened to be `stonecutter_saw_s`, causing the incorrect specular texture.

This issue could be fixed by making MCprep more strict when selecting textures to use. Another alternative that could work more reliably would be to search for normal and specular maps based on the name of the color map, since it appears that MCprep only has issues finding normal and specular maps, and that the PBR maps are guaranteed to have the same name as the color map (besides the extension).

(Screenshot taken in [`bytzo:dev`](https://github.com/bytzo/MCprep/tree/dev) to highlight specular map, however issue applies to latest release)

**Comment by TheDuckCow** [comment]
Thanks for identifying this and calling it out as a separate bug. I agree with your second suggestion, search for normal and specular maps based on the name of the color map.

The key function is: `def find_additional_passes(image_file)`, the way I do c-style loop:
```
filtered_files = [f for f in os.listdir(img_dir)
					if os.path.isfile(os.path.join(img_dir,f)) and
					f.lower().startswith(base_name.lower()) and
					os.path.splitext(f)[-1].lower() in exts
					]
```

Issue is coming in from startswith() I believe. I'm working on a fix now to make it more explicit. It's bad style to have this long of a c-style loop anyways, so I'll just be breaking it up further.

**Comment by TheDuckCow** [comment]
Just committed a fix that works for me (confirming both it was an issue before, and is now resolved). I'll keep this open until I hear from you that it's looking good on your end.

One more question - I'd love to make my allowed pbr extensions match what's really out there, as several of the below are just guesses essentially. Any chance you're able to comment on which ones you've never personally seen used as suffixes within resource packs (or if I'm missing any)? I'll do some research tool, and then based on our combined thoughts update the logic:

```
exts = [".png",".jpg",".jpeg",".tiff"]
normal = [" n","_n","-n"," normal","_norm","_nrm"," normals"]
spec = [" s","_s","-s"," specular","_spec"]
disp = [" d","_d","-d"," displace","_disp"," bump"," b","_b","-b"]
```

For instance, I've never actually seen any resource packs that use the convention of "oak_log normals.png" so " normals" above could probably be removed without consequence.

**Comment by bytzo** [comment]
Can confirm it works! :D

From my experience, I've only seen Java Edition packs use the `_n` and `_s` extensions. This could be since I usually deal with newer packs, which are all developed on either SEUS or labPBR. However, I don't think any of the other extensions are used since shader packs seem to only accept `_n` and `_s`. Additionally, I have never seen separate displacement maps anywhere in resource packs. This is due to the displacement map being stored in the alpha channel of the normal map in many packs. Again, this could also be due to the packs I work with, so maybe a separate displacement map is used in some packs. 

Will close this now as the issue is resolved. Thanks!
