### ISSUE TITLE
Import from Mineways changes or removes some blocks

### ISSUE THREAD

**Issue by CyarSkirata** [TheDuckCow/MCprep#138]
When I imported the world into Blender I discovered all my campfires have become soul campfires, my white beds have become red, and my item frames are missing. Help?

**Comment by TheDuckCow** [comment]
Sorry for the delay. Can you share what you used to export your world (e.g. Mineways), and do they look that way before using the MCprep addon at all? This will help us to understand where the issue is arising.

**Comment by CyarSkirata** [comment]
I'm not sure how to check what exactly Mineways exported, I'm not exactly great at computers, but if I can figure out how I'll share the contents of the output folder here. (So far I've only done this one export.)

**Comment by CyarSkirata** [comment]
I can send these three. If you need the 3d object or the .mtl file too I'm not sure how I could send those except for by email.
![House_Fight_Set-Alpha](https://user-images.githubusercontent.com/66367650/88066364-9464f080-cb65-11ea-8ea2-d18aa13eb2da.png)
![House_Fight_Set-RGB](https://user-images.githubusercontent.com/66367650/88066377-96c74a80-cb65-11ea-97e0-e60eefad6361.png)
![House_Fight_Set-RGBA](https://user-images.githubusercontent.com/66367650/88066382-98910e00-cb65-11ea-8c78-ecaeaef26e14.png)

**Comment by TheDuckCow** [comment]
Hi there, thanks for sharing. Yes, I think if you are able to zip if your export, which should include the .obj and .mtl file, I can then see if this is more specifically a Mineways export issue, or another one. Might be also good to just double check you're using the latest version of Mineways (try deleting your current one, and installing the new one) as I know the Mineways owner has somewhat recently pushed some updates out.

**Comment by TheDuckCow** [comment]
Just a follow up on this, any luck?

**Comment by CyarSkirata** [comment]
Sorry the reply's taken so long. Wasn't getting notifications.
Let's see if this works...
[World Export.zip](https://github.com/TheDuckCow/MCprep/files/5020903/World.Export.zip)

**Comment by CyarSkirata** [comment]
Did the zip folder work?

**Comment by TheDuckCow** [comment]
Sorry about the delay. See [this video](https://drive.google.com/file/d/1NsXV2yiaPYIIj83hSOqpzZdbRxK1CYZ2/view?usp=sharing) where I manually fix the textures by editing the UV layout. It's a little rough, but works.

I confirm that this would appear to be a Mineways exporting issue to me (if you indeed affirm they are *normal* fires in the game itself), I say this because even the block names and material names have soul in the name. I'd also make sure you are using the latest version of Mineways, and maybe there's also an issue if the world was made or used in say a beta version of Minecraft? Sharing the Minecraft version it was made/edit in would help.

**Comment by TheDuckCow** [comment]
Follow up on this - are you able to share what version of Mineways you were using, or if this is still an issue?

**Comment by CyarSkirata** [comment]
Sorry for the delay, lost track of my emails for a bit and forgot to check here. I built it in 1.16.1

**Comment by CyarSkirata** [comment]
Oh, and yes. In-game, they're normal orange campfires, the beds are white not red, and item frames don't appear to exist at all in the export.

**Comment by CyarSkirata** [comment]
_Oh,_ sorry, misread. _Mineways_ version is 7.18.0.0

**Comment by TheDuckCow** [comment]
No worries! So just checking, is the issue still present? I can direct you to the Mineways repo if it seems like a real and still present bug.

**Comment by TheDuckCow** [comment]
Quick follow up here, let me know if it this helped or if it seems like an issue to report to mineways!

**Comment by CyarSkirata** [comment]
Sorry I went quiet like that. My PC died completely back in November and
this is the first notification my phone has shown me.
