### ISSUE TITLE
Simple Player: Second layer on skin not showing

### ISSUE THREAD

**Issue by FETXU** [TheDuckCow/MCprep#139]
Hey there, I can not get the second layer on the skin to show. The mesh is there, but the texture is not showing.

**Comment by Piki-Studios** [comment]
![Annotation 2020-07-17 065555](https://user-images.githubusercontent.com/56762410/87711005-c3443500-c7fa-11ea-9e47-8d5b74ded216.png)

**Comment by TheDuckCow** [comment]
Hi! Double check that the texture in question actually makes use of the second layer. If you think it does, would you mind attaching it here so I can look further? Also by the looks, you are using the Simple Player Rig, is that right?

**Comment by TheDuckCow** [comment]
Sorry one more thing, try also going into rendered mode to see if it shows up as expected there. Sometimes solid mode doesn't look as you would expect. Press Z and select Rendered mode.

**Comment by HillustratedMike36** [comment]
Is that the simple rig? By default, they are displayed as those extra wires.

To change that...
...Select the second layer object, and go to the object properties (highlighted in the picture).
Go to the 'Viewport Display' tab and click on the dropdown menu next to 'Display As' and click on 'Textured'.
![2ndLayerEnable](https://user-images.githubusercontent.com/12376365/87941314-f7249200-ca68-11ea-9d77-9424d37d60f3.png)

You should then see the second layer on your skin _(for my skin, in this case, it's my hair and jacket)_

**Comment by TheDuckCow** [comment]
Ah, good callout @HillustratedMike36, maybe I should see about changing the default so that it's textured. Would that be better you think?

**Comment by HillustratedMike36** [comment]
Well, that saves having to change the viewport display on that mesh, so that would be a welcome change to people who has not changed that setting.

**Comment by TheDuckCow** [comment]
Awesome. I've updated the asset in my local addon, future releases will have this change included (ie the next one after v3.2.3). Will close this issue at that point for visibility.

**Comment by TheDuckCow** [comment]
Marking as closed as I have established it being tracked to the v3.2.4 milestone release. This updated rig setting is not published yet, but will be in that release (aiming for pretty soon, but not giving a hard date)
