### ISSUE TITLE
MCPrep enable traceback error

### ISSUE THREAD

**Issue by Hitamichi** [TheDuckCow/MCprep#14]
I am trying to enable MCPrep and this is the error I receive. I am unsure what to do from here and would greatly appreciate some help.

![screen shot 2017-02-04 at 9 09 55 am](https://cloud.githubusercontent.com/assets/25551007/22619513/765e76b2-eabb-11e6-9c14-36eaa1c4a368.png)

**Comment by TheDuckCow** [comment]
It appears to be an issue with the preview icon module, I'll see about fixing it in s future version but for now you should be able to use blender version 2.75 or newer. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook
>

**Comment by Hitamichi** [comment]
Alrighty, thanks. I'll update from 2.72 then to see if that helps. Hopefully, it does. I will post to see if it works or not. I believe that this is what other people are experiencing when they are trying to enable MCprep and they are unable.

**Comment by Hitamichi** [comment]
After updating from blender 2.72 to blender 2.78 I am now able to enable MCprep.

**Comment by TheDuckCow** [comment]
Glad to hear it. Still keeping this issue marked as open so I'll revisit making it work again with older versions, thanks for reporting!

**Comment by help101** [comment]
the only thing is with mine it is 2.78 but it wont work

**Comment by TheDuckCow** [comment]
Can you please comment with a screenshot of the traceback issue? Otherwise it is hard for me to understand what is wrong.

**Comment by TheDuckCow** [comment]
@help101 and @Hitamichi can you try re-installing with the latest version of MCprep? version 3.0.1 came out earlier today and may fix these enabling issues. Please let me know if there is still an issue.

**Comment by TheDuckCow** [comment]
I realize now that there was still another (silly) issue that caused this bug to occur, so I'll be putting together a quick patch and releasing soon. Fixed in the dev branch, so I'm closing here for now.

**Comment by ThePoptartCrpr** [comment]
When do you estimate that patch will be ready? :P

**Comment by TheDuckCow** [comment]
A few days, sorry - caught up in the middle of a key animation release. I don’t see why it wouldn’t be by the end of the week though!


Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com <http://www.theduckcow.com/>
youtube <http://www.youtube.com/TheDuckCow>, twitter <https://twitter.com/TheDuckCow>, facebook <https://www.facebook.com/TheDuckCow>

**Comment by Crashbandit04** [comment]
What about me
![screenshot 14](https://user-images.githubusercontent.com/43712181/46251476-da494580-c421-11e8-993a-eb0d9325b99d.png)

**Comment by TheDuckCow** [comment]
@Crashbandit04 I see you commented on #55, responding there
