### ISSUE TITLE
It came error when I installed the add-on

### ISSUE THREAD

**Issue by LucianoMarcio1** [TheDuckCow/MCprep#142]
It came error when I installed the add-on
I can't install Blender Addons #141
It came error when I installed the add-on

**Comment by HillustratedMike36** [comment]
Can you send your log?
Can you record footage of yourself attempting to install it?
Can you not enable the addon?

These are essential to issues like these, a problem like this suddenly doesn't just appear.

**Comment by TheDuckCow** [comment]
Sorry for the delay here. Indeed, any screenshots of the *first* error popup would be helpful. Make sure you are installing the .zip file directly downloaded from the website.

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, feel free to re-open if you're still having trouble.
