### ISSUE TITLE
I want to know how to use all the tools of the most important add-on for creating a minecraft series

### ISSUE THREAD

**Issue by LucianoMarcio1** [TheDuckCow/MCprep#143]
I want to know how to use all the tools of the most important add-on for creating a minecraft series

**Comment by HillustratedMike36** [comment]
**If you are using Blender 2.8**, @TheDuckCow currently has [a Youtube playlist up of tutorials regarding the addon],(https://bit.ly/MCprepTutorials) and as far as I know, still is developing them. There's also the [README](https://github.com/TheDuckCow/MCprep/blob/master/README.md) covering every single function in the addon.

**If you are using Blender 2.72 to 2.79**, there's the aforementioned README, which includes videos from his [MCprep videos playlist](https://www.youtube.com/playlist?list=PL8X_CzUEVBfaajwyguIj_utPXO4tEOr7a).

**Comment by HillustratedMike36** [comment]
**If you are using Blender 2.8,** @TheDuckCow currently has [a Youtube playlist up of tutorials regarding the addon,](https://bit.ly/MCprepTutorials) and as far as I know, still is developing them. There's also the [README](https://github.com/TheDuckCow/MCprep/blob/master/README.md) covering every single function in the addon.

**If you are using Blender 2.72 to 2.79,** there's the aforementioned README, which includes videos from his [MCprep videos playlist](https://www.youtube.com/playlist?list=PL8X_CzUEVBfaajwyguIj_utPXO4tEOr7a).

**Comment by TheDuckCow** [comment]
Thanks @HillustratedMike36 for commenting that in for me!

@LucianoMarcio1 let me know if those resources are what you are looking for, or if you are looking for something else.

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime - if you are looking for help with a specific topic, feel free to reply!
