### ISSUE TITLE
Minecraft rigs makes me lag in blender?

### ISSUE THREAD

**Issue by Ebolai1** [TheDuckCow/MCprep#144]
Whenever i spawn one or two rigs, they reduce my fps by about 4 frames. This is in the viewport display in blender. I use the rigs for animation, since it's very simple to use, and easy to add skins. But why do they consume so much of my graphics card? I have a gtx 1080, so that shouldn't be a problem. 

My specs:
I7 8700 2.4 GHZ
GTX 1080
16GB RAM

**Comment by TheDuckCow** [comment]
Hi there, it's likely not your graphics card, but a consequence of the rigs themselves if they are complicated and have multiple drivers and lots of constraints/extra bones. Blender in general does not actually handle having lots of rigs at the same time very well, and dependencies in rigs are evaluated in a not very parallel manner. 

Curious, what rigs were you adding? Are they custom?

Another protip: Put your rigs into their own collections, so you can show/hide when you don't need to be actively looking at them. Same goes for the world import, hiding it when not needed (or hiding whatever isn't the core, immediate world around you) will help a lot.

**Comment by TheDuckCow** [comment]
Just a quick follow up here, let me know if the above tips help at all with better playback/animating performance.

**Comment by Ebolai1** [comment]
Hey again
The rigs I'm using are the player ones you can spawn in with the mob spawner, and I use costum skins from usernames. There were also a few zombies used. Right now I'm not home, so I won't be able to try out your tip in about a week. I'll let you know how it goes when I've tried it. Thanks for the help!

**Comment by Ebolai1** [comment]
Well now the weirdest thing happened - I tried using blender on the laptop I have here, but now it lags when i just enter blender... I've also set the performance to cuda. There might be a problem with either my PC or blender.

**Comment by TheDuckCow** [comment]
Hm that strikes me as odd. When you say it lags as soon as you select cuda, is that because you are also in material or rendered mode in the viewport? Or even solid mode is slow?

**Comment by Ebolai1** [comment]
Well It’s weird, but I’m pretty sure my blender is just screwed. It doesn’t save any of my changes in «preferences», and it doesn’t use the full potential of my graphics card (only uses around 30%). So it might not actually be the rigs’ that cause the problem. But I’ll try hiding them as you said earlier.

**Comment by TheDuckCow** [comment]
Closing this in the meantime, let me know if it helped!
