### ISSUE TITLE
Add simple alex/skinny arm player

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#146]
It has come to my attention that we are missing a simple player skinny arm rig in MCprep! Open question to consider is whether to to modify the "Simple Player" rig to include this via a slider option, or to just add another separate rig itself. I am leaning to separate rig, so that they truly remain "simple" and not require drivers, and to make it more searchable.

**Comment by HillustratedMike36** [comment]
I second the option to a new separate rig to help sell the simplicity

**Comment by TheDuckCow** [comment]
Closing this issue as I have locally created the required assets, expecting to rename it to be the "Simple slim player". I also fixed/updated some texture mapping for the main Alex fancyfeet rig.
