### ISSUE TITLE
Entities (Custom/Other Models) spawner category

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#148]
This would be a place in MCprep, likely under the spawner panel, which would be used to spawn additional models/rigs that don't fit into the existing mob / item / block categories. This could be implemented as just a "Models" category under mob spawner, but this would not be that intuitive given these are not mobs. It could also be another section alongside Mobs, (Meshswap) Blocks, and Items. 

Ideas of things to include (assumption is all of these would be custom, 3D models / rigs):

- [x] Rigged bows and crossbows
- [x] Boats with animatable oars
- [x] Minecarts, maybe with animatable wheels and toggles for Furnace, TNT, Hopper, and Chest
- [ ] Rigged book, with page turning and enchanted material toggle
- [x] Signposts with text ready for editing
- [ ] Item stand (possibly rigged)
- [ ] Rigged piston (this probably would be better suited as a meshswap block though)
- [x] Arrows
- [ ] Bowls
- [ ] Potions
- [ ] Trident
- [ ] Elytra
- [ ] Fishing rod rig

_See [more here](https://minecraft.fandom.com/wiki/Entity)_

**Comment by KittenCat1080ti** [comment]
From what I understand, In order to do this, I need to add a few classes to Mcprep_ui.py something similar to the Item spawn class? My first goal is to make the ui appear

**Comment by KittenCat1080ti** [comment]
![image](https://user-images.githubusercontent.com/71938947/96373266-5746d500-1139-11eb-93e8-c5fc92c444a6.png)
I Have added the draw class for the new button (I reused the Item code a bit) this code unfortunately, broke the whole MCprep panel & now it doesn't even appear, probably because of a bug in my code

**Comment by KittenCat1080ti** [comment]
Ok, I fixed that

**Comment by KittenCat1080ti** [comment]
Now It it almost works

**Comment by TheDuckCow** [comment]
Thanks for working on this! One thing to ask - should we call this "models" or "entities"? I think entities might make more sense, to make it more obviously distinct from what is included in the meshswap file. ie, entities will be things that do not appear as blocks in world imports.

And to map out the key next steps here (not sure where you're at now):

- The UI is one piece, looks like you are on your way with this one!
- Then, you'll want to create an `entity.py` file, see [this diff](https://github.com/TheDuckCow/MCprep/commit/57d090f6cb88c52f0d4fa6bfc666eed041d2dd37) for various files you'd need to edit in order to get a new file loaded in properly. Note this also included a refactor beyond just the addition of the material_sync function, but hopefully you can see the main things like where we register the module and how to load in `load_modules.py`.
- You'll want to make sure that "entities" are saved to their own global list in the `conf.py` file, and that their own properties (ie instead of scn_props.item_list, you'll have scn_props.entity_list and entity_list_index)
- Likewise, some reload handlers will also need to be made/edited (one for specifically reloading models, and another which is editing the general spawners button)
- You'll likely also want to add entity models to the Shift-A dropdown (also in the ui file, defined as a menu)
- Then, you'll want to implement the loading mechanism. I think it will look or be identical to the Meshswap spawning code. In fact, it may be ideal to reuse the meshswap code as much as possible, just passing in custom blend file path for where entities are saved. The ultimate action is about the same: load the name of collections from a blend file, where each collection name represents an entity (including potentially a rig within that entity, but not always).
- Finally - I see you forked [MCprep here](https://github.com/KittenCat1080ti/MCprep) which is great, when you are ready for a code review or want me to look and give more specific feedback, you can now make a pull request to the *dev* branch of MCprep (better than screenshots of code). You can continue making edits after pull requests are made by pushing commits to your forked code, so don't worry about there being multiple commits or reversions in your forked repo.
  - I suggest running `git status` and `git diff` on your repo before adding changes just to verify what changes you have been making. Apologies if you're well versed in git already and you know about this, otherwise happy to supply some related tutorials based on whatever OS you are running on.

Let me know if you have any questions, and feel free to take it one step at a time!

**Comment by KittenCat1080ti** [comment]
The mcprep panel is not being co-operative (or I am just being really dumb), So I am just leaving it alone for now and will access it from the shift-a menu, as a temporary measure so I can focus on making it actually spawn entities.

**Comment by KittenCat1080ti** [comment]
![image](https://user-images.githubusercontent.com/71938947/96503334-132eff80-1221-11eb-9c2c-177776a6524b.png)
I am getting this error in blender, and it is telling me It can't find bpy.ops.mcprep.reload_models in ops.py Where is ops.py located, I can't find it

**Comment by KittenCat1080ti** [comment]
Update: I fixed The UI, but I am having troubles with assigning a model path. I am not well versed in git, and only know the basics, I will look up how to run git status and diff. If you have any ideas on how to assign a model path, It would be appreciated :)

**Comment by TheDuckCow** [comment]
ops.py is blender core code, so what this really means is that the module wasn't registered or found. Looking in your latest snapshot, you [correctly register](https://github.com/TheDuckCow/MCprep/compare/master...KittenCat1080ti:master#diff-3c08c9b4879da102b26ef6acf4244bf5f5dbf2fa345786bcbcb053666c590678R1327) within the file itself, and I see you correctly [register here](https://github.com/KittenCat1080ti/MCprep/blob/master/MCprep_addon/load_modules.py#L148). 

Sanity check, did you try restarting blender between code updates? It could be the old modules were still loaded. Because at a glance it seems like it should be registering ok. Let me know if restarting doesn't help.

**Comment by KittenCat1080ti** [comment]
I restart each time I change anything, My best guess is I have typo somewhere

**Comment by TheDuckCow** [comment]
Closing this now as the feature is now polished with a UI wrapped around! Any future bugs or improvements can be added with new issue reports.
