### ISSUE TITLE
Playback error / traceback error assignee:dragonslayer06 

### ISSUE THREAD

**Issue by dragonslayer06** [TheDuckCow/MCprep#15]
I resent ly installed mcprep and every time I add it in to blender it gives me a traceback error please help me

**Comment by TheDuckCow** [comment]
@dragonslayer06 what is the error, can you please provide a screenshot? A known current bug causes issues on versions of blender older than 2.75, so first also try with a new version of blender.

**Comment by TheDuckCow** [comment]
Closing due to being stale, and also newest version of MCprep coming out increases compatibility.
