### ISSUE TITLE
Somehow when I spawn a player in Blender then it looks weird!

### ISSUE THREAD

**Issue by junaayd123** [TheDuckCow/MCprep#151]
Hello, I just wanted to tell you that when I spawn a player in Blender then the whole skin is swapped! It kinda looks like the face is on the hair and the sides of the player rig go to the legs! Please help.

**Comment by TheDuckCow** [comment]
Can you share any screenshots? Feel free to also join and post your questions on the community discord for more realtime help: https://discord.gg/j3aU4Rt

Side note, make sure you are using 1.8 style skin layouts, which have spots for second layers. Older skins that don't have the room for the second layer will not look right.

**Comment by junaayd123** [comment]
Thanks!
