### ISSUE TITLE
it wont let me check one of the boxes to enable the add on

### ISSUE THREAD

**Issue by medievalknightz** [TheDuckCow/MCprep#16]
please help me figure out how to check the box to enable add on it wont work

**Comment by TheDuckCow** [comment]
@medievalknightz  what is the error, can you please provide a screenshot? A known current bug causes issues on versions of blender older than 2.75, so first also try with a new version of blender.

**Comment by TheDuckCow** [comment]
Closing issue due to staleness, also the latest version of MCprep (3.0.1) resolved most enabling issues.
