### ISSUE TITLE
Add missing mobs - Community contribution challenge

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#160]
# MCprep Mob community challenge!

*Edited on 4/21/2021 to declare the community challenge.*

The following mob rigs are not yet available in MCprep. Let's see how many mobs can be submitted over the next two weeks! Challenge ends on May 9th, 2021.

- [x] Axolotl
- [x] Cave spider
- [ ] Donkey
- [x] Drowned
- [x] Glow squid
- [x] Goat
- [ ] Mule
- [ ] Piglin Brute
- [ ] Skeleton Horse
- [x] Stray
- [ ] Vex
- [ ] Warden
- [x] Zombie Villager
- [ ] (Other mobs e.g. from Minecraft Earth/Minecraft Dungeons)

*Boxes will be ticked as submissions come in.*

## About this Community Challenge

Use this challenge as an opportunity to push your skills with modeling and rigging!

### How do I join and submit a rig?

1) Develop a rig yourself. It should be original work, made in blender.
2) Create a new comment (reply) to THIS thread, attaching your blend file directly. Optionally attach a screenshot too so others can visualize your great work!
3) Include your name/title to be used in the [credits section](https://github.com/TheDuckCow/MCprep#credit). You may optionally supply a twitter/youtube/other social link.
4) In your comment, explicitly confirm: "I understand that I am providing this rig for use under the CC-BY (attribution) license". By doing so, you affirm you understand others may use or extend your rig without restriction, so long as they provide credit back to you.

Note: TheDuckCow will modify any submitted rigs slightly to work best with the MCprep addon, but otherwise will be provided as is.

*Found a rig that someone else made? Consider still commenting the link, and TheDuckCow can reach out to the owner.*

### I submitted my rig! But where can I show it off?

Share it on social media

### Will every submission be included in MCprep?

Not necessarily - while we will aim any  include a rig that is submitted, if it doesn't meet a minimum quality/usability bar (as judged by TheDuckCow) for general use by MCprep users.

### What if we get multiple submissions for a single mob?

That's ok! But please note this is not a contest, but a challenge to flush out what is missing from MCprep while also honing your rigging skills. Only one rig will be included in MCprep for any given mob.

You are encouraged to create a rig that doesn't have any submissions yet (ie does not have a check mark above), but if multiple submissions for the same rig come in, TheDuckCow will decide which rig to be included based on factors like usability.

### Can I submit a new rig for a mob that's already included in MCprep?

Yes, and it will be considered for replacement of an existing rig, but you are encouraged to focus on submitting rigs for mobs *not* currently in MCprep.

### What best practices should I follow when creating a rig?

- Use official Minecraft vanilla textures. We want the default mobs in MCprep to have a consistent feel and look.
- Make sure any textures are packed into the blend file.
- Name all bones and objects in your blend file. For bones that have left/right versions, use `.L` and `.R` suffixes so that tools like "paste flipped" work.
- Name the root bone of your rig `ROOT` or `MASTER`. The root bone should be placed such that the "tail" of the bone is at the same level as the feet when the armature is in rest mode.
- Don't create overly stylized rigs - excessive subdivision, custom textures, or special 3D extensions that make the rig stick out too much from anything else in MCprep may lead to it not being included. Some detail is good though!
  - Take a look at what's included in MCprep today to get an idea of what's expected.
  - The VMcomix rig is good example of what generally would be considered "too stylized", while the current Zombie rig is more on the fence.
- Avoid *excessive* driver use. Drivers slow rigs down, but they do have their place.
- Pro: Give it a fun initial pose! MCprep automatically clears poses when spawned, but users can uncheck this option to get either a default animation (e.g. like bats) or an initial pose (most any other rig).
- Pro: Use custom bone shapes for more natural controls (and avoiding users needing to use xray mode in order to animate)

### When will MCprep be updated with the new rigs?

There is not a specific determined date, but it will be included in the next v3.2.5 release.

### What's the reward for entering the challenge?

Mostly the warm fuzzy feeling of contributing back to MCprep! But we'll also do some shout-outs for everyone who joined, pointing back to this page as a record of that.

### I have more questions!

Please join our [discord server](https://discord.gg/mb8hBUC), and ask away under #contest-discuss.

**Comment by Roni-Raihan** [comment]
I want to contribute by distributing mob goat
[goat.zip](https://github.com/TheDuckCow/MCprep/files/6268579/goat.zip)

the vanilla goat texture file is already in the blen file

**Comment by TheDuckCow** [comment]
Writing this comment to indicate that this is the start of the official community challenge! @Roni-Raihan your goat entry is of course grandfathered in, thanks for serving as an example for the others how to post here!

**Comment by BreadcrumbIsTaken** [comment]
## Axolotl Rig WIP 🦞

![image](https://user-images.githubusercontent.com/63469489/116938627-ec19a780-ac1f-11eb-8d72-f3fd51f43684.png)

**Comment by BreadcrumbIsTaken** [comment]
## Axolotl Rig WIP 🦞

![image](https://user-images.githubusercontent.com/63469489/116938627-ec19a780-ac1f-11eb-8d72-f3fd51f43684.png)

**Comment by TheDuckCow** [comment]
Nice, thanks for posting the wip! loving those dangly little feet. Others, don't be shy about sharing WIPs too

**Comment by BreadcrumbIsTaken** [comment]
# (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ Here is the version 1 of the Axolotl Rig!!! 
[Axolotl Rig v1 By Breadcrumb.zip](https://github.com/TheDuckCow/MCprep/files/6424651/Axolotl.Rig.v1.By.Breadcrumb.zip)

I would like it if I can be credited as Breadcrumb and have a link to my [Twitter](https://twitter.com/Breadcrumb_Boi) :)

Also, 
I understand that I am providing this rig for use under the CC-BY (attribution) license.

Creative Commons has the best licenses :)

I hope you like the rig! I would like to know if I can submit more versions later on as I improve it.

**Comment by Roni-Raihan** [comment]
> I want to contribute by distributing mob goat
> [goat.zip](https://github.com/TheDuckCow/MCprep/files/6268579/goat.zip)
> 
> the vanilla goat texture file is already in the blen file

I understand that I am providing this rig for use under the CC-BY (attribution) license

and also for credit, please as TRPHB Animation. and a link for my YouTube channel : 
 https://youtube.com/c/TRPHBAnimation
thank you😁🙂

**Comment by BreadcrumbIsTaken** [comment]
> # (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ Here is the version 1 of the Axolotl Rig!!! 
> 
> [Axolotl Rig v1 By Breadcrumb.zip](https://github.com/TheDuckCow/MCprep/files/6424651/Axolotl.Rig.v1.By.Breadcrumb.zip)
> 
> 
> 
> I would like it if I can be credited as Breadcrumb and have a link to my [YouTube](https://www.youtube.com/channel/UCT1_5td4SWg67fhElGz1S4A) :)
> 
> 
> 
> Also, 
> 
> I understand that I am providing this rig for use under the CC-BY (attribution) license.
> 
> 
> 
> Creative Commons has the best licenses :)
> 
> 
> 
> I hope you like the rig! I would like to know if I can submit more versions later on as I improve it.
> 
> 
> 
> 

I would like to add that you can cycle through all the different Axolotl variants by clicking the Gear/Properties Bone and changing the value in the Custom Properties section.

**Comment by AustinP1990** [comment]
[Cave Spider v1.0.zip](https://github.com/TheDuckCow/MCprep/files/6431524/Cave.Spider.v1.0.zip)
This is a rig for the Cave Spider. For anyone else interested in tackling some of the other mobs, I made a video series of creating it from scratch in this playlist: https://youtube.com/playlist?list=PLUavIlZtpmPwGHGYnlIp69kRr-NnFJDOM

For anyone just wanting to use the rig, here is a demonstration of the rig being used: https://youtu.be/0xA4-yMr2KY
I made my first animation ever using this rig, and it is really fun to use. The walk action controller is wicked cool; you can get decent results very quickly.

Credit me as Austin Prescott and please include the link to the demonstration video, https://youtu.be/0xA4-yMr2KY.

**Comment by TheDuckCow** [comment]
Thank you everyone who contributed to this challenge! Great to see these awesome rigs, I made a little motivational render with them below. I will keep this issue thread open, as indeed we are still taking contributions for new rigs to flush out the missing mobs, but the next release will indeed include these three new entries. 

![rig_challenge_render_finished_compressed](https://user-images.githubusercontent.com/2958461/117814157-f3e5d700-b231-11eb-88fa-d6ec17e97d39.jpg)

**Comment by AustinP1990** [comment]
> [Cave Spider v1.1.zip](https://github.com/TheDuckCow/MCprep/files/6437775/Cave.Spider.v1.1.zip)
> The Cave Spider is the only mob I have ever made a mob farm for, so we go way back. Haha
> 
> For anyone else interested in tackling some of the other mobs, I made a video series of creating it from scratch in this playlist: https://youtube.com/playlist?list=PLUavIlZtpmPwGHGYnlIp69kRr-NnFJDOM
> 
> For anyone just wanting to use the rig, here is a demonstration of the rig being used: https://youtu.be/0xA4-yMr2KY
> I made my first animation ever using this rig, and it is really fun to use. The walk action controller is wicked cool; you can get decent results very quickly.
> 
> Credit me as Austin Prescott and please include the link to the demonstration video, https://youtu.be/0xA4-yMr2KY.
> 
> EDIT: Version 1.0 just had a simple emission material that I used for texturing. I updated v1.1 with the nodes that you use for other MCPrep materials. It has mostly unused nodes, but I just included it all anyway.

[Cave Spider v1.2.zip](https://github.com/TheDuckCow/MCprep/files/6459349/Cave.Spider.v1.2.zip)
I have updated v1.2 to work with versions of Blender older than 2.92.0.

**Comment by TheDuckCow** [comment]
Thanks again all for the contributions, the three rigs above this this point were included in the v3.2.5 release. I'm keeping this issue thread open and adding to the v3.2.6 milestone to see if we can continue to get new contributions before then.

**Comment by Roni-Raihan** [comment]
![untitled](https://user-images.githubusercontent.com/82071318/122042163-60915a00-ce0c-11eb-9343-46740325d89b.png)
working on glowing squid rig. happy to be able to contribute

**Comment by Roni-Raihan** [comment]
very happy to contribute 😀😁
the glowing squid texture file is already in the blen file.
[glow_squid.zip](https://github.com/TheDuckCow/MCprep/files/6659796/glow_squid.zip)

I understand that I am providing this rig for use under the CC-BY (attribution) license

and also for credit, please as TRPHB Animation. and a link for my YouTube channel :
https://youtube.com/c/TRPHBAnimation
thank you😁🙂

**Comment by TheDuckCow** [comment]
Thank you @Roni-Raihan for another fantastic contribution! Everything looks in order here, and for the curious here's a screenshot of the final state. Excited to get this in the next MCprep release.

<img width="761" alt="glow_squid" src="https://user-images.githubusercontent.com/2958461/122397366-e9acac00-cf46-11eb-83af-c3fcf8490211.png">

**Comment by A-Leaf6409** [comment]
![image](https://user-images.githubusercontent.com/88877599/129321164-274d8c48-edc6-4b94-b50d-4a99ba90f70f.png)
WIP Redstone Golem!

**Comment by A-Leaf6409** [comment]
![Redstone Golem Progress 3 out of 5](https://user-images.githubusercontent.com/88877599/129536904-30e46270-7429-4a7e-affc-2fcb08b21a19.png)
WIP Redstone Golem 3/5 completed!!

**Comment by TheDuckCow** [comment]
Love to see the progress, keep going! Would love to include in the next MCprep release (no ETA, there hasn't been a lot of recent development)

**Comment by thefunnypie2** [comment]
<img width="795" alt="Screen Shot 2021-10-01 at 7 31 21 AM" src="https://user-images.githubusercontent.com/91716611/135570456-1ac53416-b9a7-4e68-abdb-c61deae9589f.png"
<img width="576" alt="Screen Shot 2021-10-01 at 7 32 37 AM" src="https://user-images.githubusercontent.com/91716611/135570469-9ff8c316-a8ed-4370-80e1-f7c5296d93c3.png">
<img width="624" alt="Screen Shot 2021-10-01 at 7 32 55 AM" src="https://user-images.githubusercontent.com/91716611/135570518-c0a557bb-545d-491b-a580-bf9266d5b8cd.png">
>
the drowned,stray and zombie villager ri
[mcprep addon  3 missing mob rigs.zip](https://github.com/TheDuckCow/MCprep/files/7264393/mcprep.addon.3.missing.mob.rigs.zip)
g 
pngs and rigs in this zip file

**Comment by TheDuckCow** [comment]
@thefunnypie2 thanks! And please let me know what credit link/url you want me to use for your rig contribution! By default, it'll reference your username and link back to the comment above.

Also @A-Leaf6409 if you happen to have an updated or completed redstone golem, please consider updating and sharing it here! If you share before the end of the month, I'll be able to include it in the v3.2.6 release.

**Comment by TheDuckCow** [comment]
Closing this thread officially, taking the available mobs contributed so far. If anyone wants to contribute any of the missing mobs here, you can still create a new issue or reply here directly (even those it's "closed")!

**Comment by thefunnypie2** [comment]
hello I’m glad to tell you that I’m working right now on 4 new mobs ,for more details I’m making the donkey,mule,piglin brute and the skeleton horse,see ya soon

**Comment by thefunnypie2** [comment]
piglin brute WIP
<img width="526" alt="Screen Shot 2022-01-07 at 3 48 01 AM" src="https://user-images.githubusercontent.com/91716611/148478196-60bce913-7826-4123-843c-261831d8ac1e.png">

**Comment by thefunnypie2** [comment]
donkey WIP
<img width="624" alt="Screen Shot 2022-01-07 at 3 46 57 AM" src="https://user-images.githubusercontent.com/91716611/148478273-c52bbf91-82af-49e8-8770-9bdbb5b5c6dd.png">

**Comment by thefunnypie2** [comment]
mule WIP
<img width="606" alt="Screen Shot 2022-01-07 at 3 46 32 AM" src="https://user-images.githubusercontent.com/91716611/148478324-2fec8697-fc1e-49c8-95ae-f5240f41c512.png">

**Comment by thefunnypie2** [comment]
i hope you like the donkey and the mule and the piglin brute,last one is skeleton horse 🐴 💀

**Comment by thefunnypie2** [comment]
kinda working on it . . . 
<img width="646" alt="Screen Shot 2022-01-07 at 5 04 47 AM" src="https://user-images.githubusercontent.com/91716611/148484914-5e7ef408-5679-44d1-9f69-fa6edf33867c.png">
.
