### ISSUE TITLE
Can’t add mcprep to Blender

### ISSUE THREAD

**Issue by HeroMaster137** [TheDuckCow/MCprep#162]
Whenever I try to add the mcprep addon to blender and after I add it, I try to search it in addons, but I do not find anything, please help.

**Comment by KittenCat1080ti** [comment]
Could you include some screenshots? if you could be be more specific on how you installed the plugin that would be helpful. :)

**Comment by HeroMaster137** [comment]
![Screen Shot 2020-10-17 at 2 18 54 PM](https://user-images.githubusercontent.com/73035479/96353832-9404c480-1084-11eb-86c1-6f61223234ca.png)
![Screen Shot 2020-10-17 at 2 19 26 PM](https://user-images.githubusercontent.com/73035479/96353854-be568200-1084-11eb-8030-24692839183f.png)
I then pres add addon
![Screen Shot 2020-10-17 at 2 20 48 PM](https://user-images.githubusercontent.com/73035479/96353855-c57d9000-1084-11eb-83a7-22251631c742.png)

**Comment by KittenCat1080ti** [comment]
You see where it has "official" selected at the top? change that to "community" then it should show up.

**Comment by TheDuckCow** [comment]
Thanks Kitten for helping identify that, and indeed - that should be the issue here @HeroMaster137. Let us know if that worked!

**Comment by HeroMaster137** [comment]
Thank you, it worked
