### ISSUE TITLE
Addon Not activating

### ISSUE THREAD

**Issue by DeGraphics-Studios** [TheDuckCow/MCprep#169]
I have tried installing MC Prep on 2.90.1 but I keep getting an error message when I try to activate it.
<img width="671" alt="Screen Shot 2020-10-28 at 6 34 14 PM" src="https://user-images.githubusercontent.com/24575690/97504273-f09d9480-194c-11eb-94d7-093e99fb7f12.png">

**Comment by DeGraphics-Studios** [comment]
Update, the problem only seems to be on my MacBook Pro

**Comment by TheDuckCow** [comment]
Can you make sure you install the latest version of the addon? This looks like an error that was fixed a few versions ago. Try first deleting MCprep from user preferences, closing blender, then re-opening, and installing the latest.

**Comment by TheDuckCow** [comment]
Following up here, please let me know if the above helped!

**Comment by CoreB7** [comment]
having the same problem here, I'm from windows, blender 2.9

**Comment by CoreB7** [comment]
nvm, deleting the addon, closing, reopening and installing again works -.- thx
