### ISSUE TITLE
z button

### ISSUE THREAD

**Issue by DaviceXD** [TheDuckCow/MCprep#17]
Hi guys. I've installed McPrep, it works great. But when i press z 2 times, the blocks are white, and i can't changhe the colors. What can I do?? Thanks

**Comment by TheDuckCow** [comment]
How does it look in rendered view, is it fixed? Do you have texture-solid enabled? It may be that the active images showing in the realtime preview are off. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by DaviceXD** [comment]
Yes. I followed the instructions...

**Comment by TheDuckCow** [comment]
So does that make the issue resolved? It looks good on render then?

**Comment by DaviceXD** [comment]
Thank you, i solved :) i tried to render it and now it works, thanks!!

**Comment by TheDuckCow** [comment]
Great! Feel free to share on [twitter](https://twitter.com/TheDuckCow) or anywhere else what you make with it, I'd be happy to see!

**Comment by DaviceXD** [comment]
Surely!! It's so useful!!
