### ISSUE TITLE
Some mesh swapped torches emit less light after scrolling the timeline

### ISSUE THREAD

**Issue by drepman** [TheDuckCow/MCprep#175]
[Video demonstrating the issue.](https://www.youtube.com/watch?v=Y5lH0xJoIHE) This doesn't happen with all torches, although different torches seem to be effected every time I load a new file.

**Comment by TheDuckCow** [comment]
Thanks for sharing this with the video, and apologies for the delayed response. Definitely want to get this resolved!

**Comment by TheDuckCow** [comment]
Closing this as I have this fixed and will be included in the soon to be released MCprep v3.2.4.2 version.
