### ISSUE TITLE
Issue involving 2.91

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#177]
So when I install and enable MCprep in 2.91, it has this error. Is it a 2.91 problem?

![Screenshot 2020-11-25 223032](https://user-images.githubusercontent.com/75058058/100308870-ffd52980-2f6e-11eb-9968-5b51f80beff8.png)

**Comment by TheDuckCow** [comment]
Thanks for the screenshot. It looks like an issue in the core blender code, can you let met know if you are able to install any other addons (where the addon is a zip file, as opposed to a single py file)?

Also can you confirm you are using a daily dev build? Looks like it from the error popup, just want to confirm so I can test myself too.

**Comment by StandingPadAnimations** [comment]
It seems to only happen with MCprep as I'm able to install real camera, molecular, and UV squares fine. As for the version, it's the 2.91 full release which came out yesterday

**Comment by StandingPadAnimations** [comment]
Wait, it works now

**Comment by TheDuckCow** [comment]
Just confirming, this issue isn't a problem anymore right?

**Comment by TheDuckCow** [comment]
Closing for now - let me know if it crops up again! Or if you identified a conflicting addon.
