### ISSUE TITLE
Blender Freezes

### ISSUE THREAD

**Issue by BeepBot99** [TheDuckCow/MCprep#179]
Whenever I import something from Mineways, Blender freezes and says "Not Responding."

**Comment by TheDuckCow** [comment]
If it's a big world, this is expected - it takes time to import geometry. I'd say either wait until it finishes, or try exporting a smaller world. If you don't need the underground part of the world, remember to raise the floor of what is exported.

**Comment by TheDuckCow** [comment]
Going to mark this as closed for now - feel free to comment back if you're still running into issues.
