### ISSUE TITLE
jmc2obj

### ISSUE THREAD

**Issue by Minecrafty999** [TheDuckCow/MCprep#180]
As I saw on your video you are supposed to beadle to run the jMc-2obj-108.jar with MCprep but when I run it, it just opens the jar file code.

**Comment by TheDuckCow** [comment]
Can you share what operating system you are using, Windows or Mac or Linux? It could be more due to your operating system’s default behavior for Jar files (ie extracting, as opposed to running).

**Comment by Minecrafty999** [comment]
Windows

**Comment by Minecrafty999** [comment]
Is there an exe file I need to use?

**Comment by TheDuckCow** [comment]
Can you share what happens when you double click the .jar in windows explorer, does it run the .jar (executes) or tries to extract it?

There is no exe, the .jar is functionally an executable as long as you have java installed. Are you able to run jmc2obj on it's own even without using MCprep? If that doens't work, then it won't work in MCprep either.

**Comment by Minecrafty999** [comment]
On blender and just file explore and stuff it just opens the file code. I do have java installed.

**Comment by Minecrafty999** [comment]
Its uses notepad to show the code

**Comment by Minecrafty999** [comment]
I does not try to run nor extract it

**Comment by StandingPadAnimations** [comment]
Right-click it and select open with, then select the java app

**Comment by Minecrafty999** [comment]
ok

**Comment by Minecrafty999** [comment]
that worked! thx

**Comment by Minecrafty999** [comment]
Wait a sec

**Comment by Minecrafty999** [comment]
Now I cant load my world

**Comment by StandingPadAnimations** [comment]
Maybe you have to set the file path to the Minecraft worlds(in the .minecraft folder, there is another one called saves)

**Comment by Minecrafty999** [comment]
I did. and I know where the folder is. But mine is saved somewhere else. I moved it

**Comment by Minecrafty999** [comment]
I would send a pic if I could but cant

**Comment by StandingPadAnimations** [comment]
If you moved the saves folder, just set a new file path to it

**Comment by Minecrafty999** [comment]
I did but the load button was disabled

**Comment by Minecrafty999** [comment]
goto and export are also disabled

**Comment by StandingPadAnimations** [comment]
have you tried mineways?

**Comment by Minecrafty999** [comment]
ya. I'm watching the playlist TheDuckCow made. And I need to use jmc2obj now.

**Comment by StandingPadAnimations** [comment]
jmc2obj is basically mineways, it just uses java code

**Comment by Minecrafty999** [comment]
I mean I still want to follow along

**Comment by Minecrafty999** [comment]
And I might need it later so...

**Comment by Minecrafty999** [comment]
nvm. It's working
