### ISSUE TITLE
Just confirming, this issue isn't a problem anymore right?

### ISSUE THREAD

**Issue by googlevhs** [TheDuckCow/MCprep#181]
Im having a similar problem but where blender will not allow me to enable the plugin, it doesnt come up with an error it just doesnt allow me to check the box

**Comment by googlevhs** [comment]
Nvm i got it to work, it was blender

**Comment by TheDuckCow** [comment]
out of curiosity, any chance you got a screen grab of what the error was when it popped up? Good to know it was resolved, but someone else might run into it and not know what to do, so would love to understand more.

**Comment by googlevhs** [comment]
I simply redownloaded the mc plugin again and update my blender (i didn’t
know there was a new update from 2.9 to 2.91)
