### ISSUE TITLE
How can i change the placement of the eyes.

### ISSUE THREAD

**Issue by Lacosst0** [TheDuckCow/MCprep#184]
How can i change the placement of the eyes.If it impossible, can someone make the rig which can change the placement of the eyes. (Like black plasma studio rig). Thanks very much. I hope it will be in newer versions of mcprep
![blender_X2sTzqh02i](https://user-images.githubusercontent.com/68904262/106649069-22ed0c80-65a2-11eb-9c8c-130c0d3fc484.png)
![image](https://user-images.githubusercontent.com/68904262/106649138-35ffdc80-65a2-11eb-8842-ff7f33a3521f.png)

**Comment by TheDuckCow** [comment]
Hi, thanks for sharing the image. The Player rig would need to be redesigned a bit to support this, it may be something to consider just including the Black Plasma rig itself.

No immediate ETA, but remember that you can "install" rigs in MCprep for reuse, if you prefer the BPS rig.
