### ISSUE TITLE
Make the face controls optional in the Player rigs

### ISSUE THREAD

**Issue by TravisC671** [TheDuckCow/MCprep#185]
I love the way you set up the arms but some skins just don't fit with the face. if you could make a complex rig without the face and the warped geometry, that would be amazing.
you can see my skin here
https://namemc.com/skin/48dded7c785d6ecb

**Comment by TheDuckCow** [comment]
Hi there, thanks for opening the issue on this. I think enough people have asked for this now that it's reasonable to include. No ETA but I agree this is worth implementing.

One thing I am curious - would you want to see it as a separate rig in the list (less preferred from a maintenance/download size point of view), or is it ok if it is a slider option on the rig? Or simpler yet, just a hidden layer you can toggle in the outliner? Want to balance what people will naturally find and be intuitive.

**Comment by TravisC671** [comment]
I think the third item would be the best. I’m not looking for anything too fancy so whatever is easiest is good.

**Comment by TheDuckCow** [comment]
Great, thanks for the feedback! I tend to agree, simpler is better (and driver controls slow down blender the more rigs you have, making the outliner approach preferable).

**Comment by TheDuckCow** [comment]
Made this change locally. Both the Player and Slim Player have a second head object included, but initially hidden by default (both in viewport and render).
