### ISSUE TITLE
Viewport gradient disappears when I prep materials 

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#187]
When the world gets prepped, if the viewport is set to be a gradient, the gradient disappears.

**Comment by TheDuckCow** [comment]
Sorry for the delayed reply, my guess is this happens due to "Improve UI" which sets the world to texture mode. If you don't want this, try turning off "Improve UI" in the popup before prepping materials. Let me know if the issue persists even after that though!

**Comment by TheDuckCow** [comment]
Confirmed myself that this occurs. Setting is the same one described in [this video](https://www.youtube.com/watch?v=-jbcVGeYfIc), under Preferences > Theme, 3D Viewport, scroll down to Theme Space, and then select Linear Gradient. 

After running Prep UI, the gradient no longer appears, even when going back to solid mode.

**Comment by StandingPadAnimations** [comment]
Yep, it's due to switching to world. Switching to theme fixes it
![image](https://user-images.githubusercontent.com/75058058/124656791-437a0500-de67-11eb-8046-56778ee247ab.png)
