### ISSUE TITLE
Some Mesh Swap torches not emitting light.

### ISSUE THREAD

**Issue by staf-dierickx** [TheDuckCow/MCprep#192]
As the title says some Mesh Swapped torches don't work. 
I don't know what could be the problem but if I put in a new light source it works.
Other light sources also don't work like Jack-o'-lanterns.

![blender_htMW38c2JB](https://user-images.githubusercontent.com/33757638/111156691-52763800-8596-11eb-9066-bb26d03b79d9.jpg)
![blender_LmjLUQCkjH](https://user-images.githubusercontent.com/33757638/111156693-53a76500-8596-11eb-819c-bbc689785bfa.png)

**Comment by TheDuckCow** [comment]
Thanks for sharing this! I think there is an issue with the source meshswap blend file, need to do a bit of an audit and fix it. Pumkins are interesting that they aren't working, sanity check that they indeed are jack'o'lanterns? Also in that last screenshot, am I wrong in seeing that there actually is a lamp object there? Let me know what render engine you're using and if there is a difference being in rendered view.

**Comment by staf-dierickx** [comment]
I was using eevee and indeed, all the torches and jack o'lanterns have a lamp object in them. I would send the blend file if that's ok, but my windows got corrupted with the 20H2 update and all my files are gone. I'm going to try to recreate the problem, do a little testing myself.
If it is ok, I will attach a link with a blend file in a future comment.

**Comment by staf-dierickx** [comment]
i did a little bit of research on light sources etc. 
I put some .blend files and a few notes on [my google drive](https://drive.google.com/drive/folders/1kIbqkxIFGcm07WcRugmCUZZ1Dy7ZP1AN?usp=sharing). 
maybe i'm going to do some more research so check it several times if necessary.
[here's a link:](https://drive.google.com/drive/folders/1kIbqkxIFGcm07WcRugmCUZZ1Dy7ZP1AN?usp=sharing) https://drive.google.com/drive/folders/1kIbqkxIFGcm07WcRugmCUZZ1Dy7ZP1AN?usp=sharing

**Comment by TheDuckCow** [comment]
Thanks for sharing this. Some thoughts:

- I can see that the "optimized mesh" option was most likely used. Meshswap depends on reading values, so 
- There's a separate issue affecting torches in the source meshswap file, I'm planning to fix this in the next update. I'll see if it's affecting jack o lanterns too.

Let me know if you think there are other issues to flag! And thanks a bunch for that spreadsheet, going to use that to check through the source meshswap file.

![Screen Shot 2021-03-18 at 7 58 37 PM](https://user-images.githubusercontent.com/2958461/111712676-8070ac00-8824-11eb-828a-f7daf15476d6.png)

**Comment by TheDuckCow** [comment]
Closing this thread as I have locally made the change for torches in Meshswap, which will fix the title of this issue thread. Happy to carrying on talking about the other issues here or in a new issue if needed.
