### ISSUE TITLE
[Request] Prep mesh

### ISSUE THREAD

**Issue by lajawi** [TheDuckCow/MCprep#193]
Using Mineways, I imported a model into Blender, but when going into edit mode, I noticed something.
The mesh isn't good, it's really bad. What I mean by this, there are vertices crossing edges, but not connecting to them, overlapping edges etc.
![pic1](https://user-images.githubusercontent.com/51792807/111266080-52277c80-862a-11eb-98b6-ea4d9248c13f.png)
As seen in this picture, everything _appears_ to be normal, besides the wrong shading at the bottom, probably caused by said issue.
![pic2](https://user-images.githubusercontent.com/51792807/111266081-52c01300-862a-11eb-96b1-877144002d3c.png)
After moving selected vertex, however, as seen in this picture, we notice many edges and vertices aren't connected.

My wish is that there will come something like the `Prep Materials` but for the mesh, like `Prep Mesh`. This, of course, could be used for other meshes as well.
If importing files from Mineways via MCprep, it also could be activated automatically, so the mesh is optimal from the start.

- Credit to the model shown in the pictures goes to fWhip, even if you almost see nothing. I just don't want to get busted :)

**Comment by TheDuckCow** [comment]
Thanks for outlining this. Any chance you can manually create the most simple before vs after screenshots? That will help me understand more specifically what you are hoping to achieve. As I'm reading, I'm thinking something that ensures that al vertices have points they join against, and all points are joined together.

A related question, is what specific use cases does this help resolve? Adding the verts and slices is a means to an end, so understand the end goal might help me think of ways for MCprep to get you there even by a different route.

**Comment by lajawi** [comment]
> 
> 
> Thanks for outlining this. Any chance you can manually create the most simple before vs after screenshots? That will help me understand more specifically what you are hoping to achieve. As I'm reading, I'm thinking something that ensures that al vertices have points they join against, and all points are joined together.
> 
> A related question, is what specific use cases does this help resolve? Adding the verts and slices is a means to an end, so understand the end goal might help me think of ways for MCprep to get you there even by a different route.

I want the mesh to be as perfect and low poly as can be, without any of the wrong behaviors like in the pictures. Where meshes should be joined, they aren't, which, when editing, is a huge problem.

**Comment by TheDuckCow** [comment]
So I think those two things are actually somewhat in conflict, the reduced number of poly's as possible means also not having vertices always joined perfect as you need extra subdivisions. 

I could see about implementing a function which does a merge by distance and followed by an attempted select and delete 'internal faces', but it's not really reliable and highly dependent on the mesh output from either Mineways or jmc2obj.

Can you try and see if taking those two manual steps at least get you closer?

**Comment by TheDuckCow** [comment]
Let me know on the above, thanks!

**Comment by TheDuckCow** [comment]
Minor ping on this point, want to better understand what you are hoping would be implemented before I try to invest time in this/what use cases it enables.

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, feel free to comment back if you have thoughts!
