### ISSUE TITLE
Mesh-swapping is broken on some objects

### ISSUE THREAD

**Issue by HackerDaGreat57** [TheDuckCow/MCprep#194]
Some objects don't mesh-swap, and the same object can't be manually spawned. For example, I can clearly see a 3D crafting table in the mesh-swap .blend file, yet the 2D crafting table is still there in the world after selecting everything and clicking the meshswap button. Plus, I can't just delete the 2D crafting table and easily spawn a new 3D one, because it's not there in the meshswap blocks spawner. Copy-and-paste directly from the meshswap file is not convenient. The same issue happens on a number of other items in the meshswap file. Please fix this issue.
![Screenshot (812)](https://user-images.githubusercontent.com/70416002/111687406-79777880-87e7-11eb-9bba-93a35e1379aa.png)

**Comment by StandingPadAnimations** [comment]
That looks meshed swaped. It's not the default crafting table, it seems to have 3D bits. Also, it only works for blocks that came out of a exported world if this is from the BSS pack

**Comment by TheDuckCow** [comment]
It also matters what objects you have selected, if the materials are split into different meshes be sure to selected them all. 

Note: Manual spawning is only set up for the "group" meshswap blocks, which is why (at least at the moment) only some are showing up in the meshswap spawner.

**Comment by superhuman2020** [comment]
I am completely sure that I selected a crafting table. I exported my world with Mineways. Nothing else is there in the scene (Not even a camera). I tried the same with flowers, even those don't work.

**Comment by superhuman2020** [comment]
Oops, sorry if I caused some confusion StandingPadAnimations, but the screenshot included is a screenshot of the “mcprep_meshSwap.blend” that is included with the MCprep package.

**Comment by TheDuckCow** [comment]
Just checking in, I tested locally and found that the crafting bench indeed swaps as expected for me in both jmc2obj and Mineways, and within Mineways both for "separated" and "combined" versions of exports (where all textures are in different files vs one big image file). 

I'll try again with the latest version of Mineways in case something has changed, but double check it isn't working but subtle (the 3D features of the crafting block are not that exaggerated, at first I thought it didn't work either but then I zoomed in).
