### ISSUE TITLE
Skin Swapper Skins not showing up!

### ISSUE THREAD

**Issue by Whitepolarbear64** [TheDuckCow/MCprep#196]
I don't know what happened but all the sudden my skin swapper stopped working I am no longer able to see the skins. It is only for this project if I open a new one it is there. If I press reload nothing happens.
![image](https://user-images.githubusercontent.com/81723015/113229576-40b6b500-9265-11eb-8fde-57af84602059.png)

**Comment by TheDuckCow** [comment]
Can you try pressing the return arrow icon under advanced to reset it's path? You can also try clicking the folder icon and re-selecting the folder (it should have at least 1 image file there to work).

**Comment by TheDuckCow** [comment]
Just a follow up on this, let me know if any of the above steps helped!

**Comment by TheDuckCow** [comment]
Closing this in the meantime, let me know if it's still an issue.
