### ISSUE TITLE
Items in the spawner only showing my custom textures after updating.

### ISSUE THREAD

**Issue by KatCub27** [TheDuckCow/MCprep#199]
I've updated to the latest version of MCprep today, and now my items list in the spawner is only showing my custom texture items (with the wrong icons too). [Here is a screenshot of the list.](https://imgur.com/a/iaxsBCB)

**Comment by TheDuckCow** [comment]
Oh no! Can you try reloading the list (under advanced settings), and following that, try restarting and opening blender again (and frefrehs icons if you're opening an old file)? That might fix it. If not...

Where do you have your custom texture icons located (In another folder, ie not the default MCprep items folder)? Is this a new file, or an existing file you've opened?

**Comment by KatCub27** [comment]
This is an existing file I have opened. If I create a new one, the items list is just fine. I also tried reloading the list and that didn't change anything aside from reloading the icons next to the names (I don't even know why some of these are here, they're just block textures I have separately to replace textures like orange and yellow wool). The custom textures are located in a separate folder I have located in the overall folder I'm keeping the entire project in.

**Comment by KatCub27** [comment]
Update: Moving the specific folder that had all these textures has now emptied the items list and shows a "reload assets" button. I try clicking it but it doesn't do anything.
Also to note: the mobs and meshswap lists are untouched by this issue.
I think I will keep in mind to not have a folder like that in my project folders from now on when I use MCprep :p

**Comment by TheDuckCow** [comment]
Thanks for all the troubleshooting steps, seems indeed like it's not refreshing correctly when a custom folder is used.

Quick check - when you say items load fine when you open a new file, does that mean it also correctly loads your custom folder of items if you change it back to the same folder as that other blend file? Or just that it loads default items? See if you can load your custom ones in a new file too, and that any items that show up are also *images* in the folder in qustion.

I definitely want to solve this, might be helpful if you're able to do a screen recording. Even better if you can somehow replicate in a fresh file, it's harder to say what might be causing troubles with a prior save. Something to try in the recording (to show me, or maybe even help fix the issue): try pressing the reset button to the right of the path under advanced (looks like a return arrow); that should load the default vanilla items correctly, then set it back to your custom folder, and see if they load correctly then.

**Comment by KatCub27** [comment]
Sorry that it took a while to reply. I had some other things to attend to first. :)

**When you say items load fine when you open a new file, does that mean it also correctly loads your custom folder of items if you change it back to the same folder as that other blend file? Or just that it loads default items?**
So I thought I'd clarify first, the textures I had weren't supposed to be items. They were textures for specific blocks/mobs I have in my blender file (e.g. I replaced some of the block textures for the world obj with the wool textures, and the parrot mobs I did a skin swap with the parrot textures I had).

When I make a new file, it loads MCprep's default items correctly. I can also reload the textures as the "item" folder if I swap the folder directory back to the folder with my custom textures in it

**try pressing the reset button to the right of the path under advanced...then set it back to your custom folder, and see if they load correctly then**
Pressing the reset button fixed the items and reloaded the default items correctly (tysm for this! I had no idea that's what the arrow did). I also went back into my folders and changed it back to the textures folder just to see if it would load them again correctly (and they did, but of course they aren't meant to be items so they just spawn in as flat planes). Unfortunately, my screen recording seems to hate working with Blender, and I can't click anything in Blender while I screen record, [so here are a series of screenshots instead that are annotated](https://imgur.com/a/GWPuJfg). What is also unfortunate is that I cannot replicate this issue unless if I manually set the items folder location to my textures folder (which I did not do in the first instance after updating).

**Comment by TheDuckCow** [comment]
Thanks for trying all these steps! ... and super sorry for the long delayed reply on my part. From what I understand, it sounds like you got things working in the end, and it was more due to a "bad state" but resolved after resetting and re-applying the custom folder? Let me know and then I can close the issue, but if something still ins't working as expected please let me know.

**Comment by TheDuckCow** [comment]
Closing the issue in the meantime, but let me know if it persists.
