### ISSUE TITLE
I cant open MCprep on blender

### ISSUE THREAD

**Issue by Danieli12** [TheDuckCow/MCprep#20]
On blender when i go its just a folder 
![screenshot_1](https://cloud.githubusercontent.com/assets/27362709/24967162/dbb7d816-1fb1-11e7-8896-0c0e59fba71a.png)

**Comment by TheDuckCow** [comment]
Make sure that if it's downloaded and became unzipped, you must rezip it so it has a .zip extension. Some web browsers automatically "open" files or unzip folders that download which is why you probably see a folder instead of the original zip file.

**Comment by Danieli12** [comment]
Thanks So Much
