### ISSUE TITLE
TOO MUCH MEMORY

### ISSUE THREAD

**Issue by HackerDaGreat57** [TheDuckCow/MCprep#200]
I found yet another issue!

I have a large amount of grass (The world I'm importing has roughly 600-700 pieces of grass + 30 or so flowers) and when I meshswap, the memory usage of blender climbs up to 20,000MB on an 8GB memory computer. (Using virtual ram obviously) And virtual memory is too slow. Please try reducing the memory usage of mesh-swapped grass.

Maybe you could implement a "Optimize Grass" button that would bake the grass's wind simulation somehow, so the grass would have a pre-defined motion instead of memory and CPU spiking when trying to go to the next frame.

Forgive me if I'm thinking about this all wrong, I've only been working with Blender for a few weeks.

**Comment by TheDuckCow** [comment]
Hi there! I would said this is more or less functioning as expected. As per [this video](https://youtu.be/3gbrOkqmqRE?t=19), I would never recommend running meshswap on a large area of blender. Even if the meshswap operation somehow ran instantaneously, the blender interface just can't handle that many individual objects with those animated modifiers (at the very least, it would be crawling). 

Now that being said, there are still areas that could be improved, I agree with you there. I've thought about features like auto selected and separating only grass objects e.g. within 50m in the field of view of the camera. But I think a feature would 1) take awhile to develop, 2) be error prone, and 3) not necessarily be intuitive/give the 'right' control to users. 

Happy to hear your thoughts or suggestions, a newcomers experience is very valuable for me to understand (and, if nothing else, maybe you can think of way's we can better warn users to do what's suggested in the video linked above).

**Comment by HackerDaGreat57** [comment]
It's fine. I'll just close the issue. Again, no problem, cuz all I have to do is wait 5 years (Actually not a lot when I think about it) to get like 64GB of RAM, then I'll be good to go.

**Comment by HackerDaGreat57** [comment]
It's fine. I'll just close the issue. Again, no problem, cuz all I have to do is wait 5 years (Actually not a lot when I think about it) to get like 64GB of RAM, then I'll be good to go.
