### ISSUE TITLE
Rig not matching up with model

### ISSUE THREAD

**Issue by IJplayz** [TheDuckCow/MCprep#202]
So I am trying to make a player rig with Simple Player (also tried Simple Player Slim) and it makes the rig and the model, but they are far apart from each other. I tried reinstalling and no luck.
![image](https://user-images.githubusercontent.com/62681521/115968015-70667f00-a4ea-11eb-99c1-997f0dc8352f.png)

I just updated it yesterday, and I tried rolling back to that version, but it gave me errors.

**Comment by TheDuckCow** [comment]
My guess is that it is spawning the model at the cursor location, which is the default behavior. You can specify that it spawns at the origin by expanding the "redo last" menu bottom right directly after spawning. See [here for more info](https://youtu.be/xAtdxNiI0fA), where the different location options are specified.

**Comment by TheDuckCow** [comment]
Follow up here - is this issue still occurring for you?

**Comment by TheDuckCow** [comment]
Closing this in the meantime - let me know if still an issue.
