### ISSUE TITLE
Some transparent object turned black

### ISSUE THREAD

**Issue by Endertainer** [TheDuckCow/MCprep#203]
So I got these issues when I was working on one of my animations. The problem is that sometimes I got some transparent objects, especially grass & foliage, I got some of them turned black.
![untitled](https://user-images.githubusercontent.com/57242521/116399999-7d75cc00-a864-11eb-970a-5e6d520c8438.png)
I tried messing with the material and some settings but it just won't go away. Though this issue only occurs from a specific perspective. For example, if I turn the camera to look from up, the problem just goes away.

**Comment by Endertainer** [comment]
Ok, I finally found a resolve. It turns out that if I increase the transparency in the light path settings. The issue got fixed.

**Comment by Athmitsic** [comment]
This post is so old now but you are an absolute lifesaver. I have been fiddling and googling for about 30 minutes now and couldn't find anything to fix it. thank you so much.
