### ISSUE TITLE
no materials found to update please help me!

### ISSUE THREAD

**Issue by AnyOneCan1** [TheDuckCow/MCprep#204]
no materials found to update i can't put a skin
please help me

**Comment by AnyOneCan1** [comment]
<img width="100" alt="Screenshot 2021-05-05 214258" src="https://user-images.githubusercontent.com/83726509/117192864-e15f3e00-adea-11eb-97f7-62afe939ea91.png">

**Comment by TheDuckCow** [comment]
You need to have a material with an existing skin applied already in order for swap skin to work, as it only swaps in one image for another (so if there isn't one there already, it can't really do anything, since it's not a feature which creates or modifies materials otherwise).

**Comment by TheDuckCow** [comment]
Closing this issue, but let me know if you are still having troubles.
