### ISSUE TITLE
Swap resource pack not working

### ISSUE THREAD

**Issue by frazzleman10** [TheDuckCow/MCprep#206]
Ive been trying to swap the texture pack to the faithful 1.16 resource pack for my minecraft render, but when i click swap resource pack and select the folder it loads in but looks like this 
![image](https://user-images.githubusercontent.com/66959168/119255105-c4c85180-bbb1-11eb-961e-c45486291989.png)

**Comment by StandingPadAnimations** [comment]
Are you using mineways? If so, you have to select "export tiles to textures directory" when exporting(it's on the bottom section somewhere)

**Comment by TheDuckCow** [comment]
Indeed what StandingPad has mentioned is the most likely culprit, let us know if that helps!

**Comment by frazzleman10** [comment]
Thanks ill give that a go

**Comment by TheDuckCow** [comment]
Did that work for you? Also curious - did it not give you a warning popup when you tried to swap texturepack before using the "export tiles to textures directory" option? I coded it in so it would give a warning, but helpful to know if it's not triggering for some reason.

**Comment by frazzleman10** [comment]
I havent actually tried it yet, i took a break from blender, but no when i pressed swap resource pack it did not give me a warning

**Comment by SolomonGarrett258** [comment]
same happened in Blender 2.79, MCprep 3.2.5

**Comment by StandingPadAnimations** [comment]
Have you tried using Jmc2obj? It may work better

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime - there should have been some code in place to warn about using "scaled UVs", but in any event the proper course of action is to export to tiles from Mineways.
