### ISSUE TITLE
MCprep addon not working

### ISSUE THREAD

**Issue by thespeedofpeople** [TheDuckCow/MCprep#207]
https://user-images.githubusercontent.com/84731002/119375233-31aa1d00-bc80-11eb-8e55-91667e5e538c.mp4

And then it just closes blender help pls

**Comment by thespeedofpeople** [comment]
Version 2.78

**Comment by StandingPadAnimations** [comment]
Interesting. It could be because it's 2.78, there are some compatibility issues. Maybe try 2.92 and see if that works

**Comment by TheDuckCow** [comment]
Hi, can you share what is not working? From the looks, it seems everything is in order (and actually, blender 2.78 is still supported). If you are expecting the whole preferences panel to show up, you just need to press the triangle icon to expand it, it does not open automatically.

**Comment by TheDuckCow** [comment]
Quick follow up @thespeedofpeople, let me know what seems to be the issue

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, let me know if you continue to have issues.
