### ISSUE TITLE
blender2.93or3.0 install error

### ISSUE THREAD

**Issue by shadowcreeper-hash** [TheDuckCow/MCprep#211]
![Blender偏好设置 2021_6_5 12_14_01](https://user-images.githubusercontent.com/65867725/120879656-9148e680-c5f7-11eb-9ab0-9ad361ef647d.png)
😱😱😱😱😱😱

**Comment by TheDuckCow** [comment]
Closing this in favor of having a single issue on this topic, the release is coming this week: https://github.com/TheDuckCow/MCprep/issues/208
