### ISSUE TITLE
Items spawned in blender 2.93+ don't match pixel grid (alpha oddities and scaled faces)

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#213]
EDIT: It turns out, this is a general problem with MCprep on Blender 2.93+, but the same problem is not occurring in older versions of blender. It appears to affect all items spawned, not just non-square ones. You can see the issue clearly below when spawning a golden apple as one example (see how the faces created do not align to the pixel grid):

<img width="698" alt="golden apple non grid" src="https://user-images.githubusercontent.com/2958461/121353410-d4f36700-c8fb-11eb-87e6-c4dc9a70c516.png">

This could be a change in the Grid Add operator, as I'm noting the number of pixels across the apple here is 12, but the faces subdivisions is 13, so it could be an "off by one" error.

Original report below
-----

At the moment, non square items are generated in an odd way that isn't that useful. Specifically:

- The output mesh/object is still square
- The individual squares within this output square model do appear to be given an aspect ratio that would have been appropriate for the overall mesh (but if one where to just scale the mesh, this would stretch the individual faces in the wrong direction)
- The individual faces don't actually align with the pixel grid as a result.

**Screenshot references:**

Source image (non square):
<img width="50" alt="src" src="https://user-images.githubusercontent.com/2958461/121181971-9775d780-c830-11eb-83e4-4f325b34f4b8.png">

The imported "item" object (shows up square, image clearly stretched)
![overall_img](https://user-images.githubusercontent.com/2958461/121181947-8fb63300-c830-11eb-8a32-719438630271.png)

Seeing how the faces are scaled and not aligned to the pixel grid
![Screen Shot 2021-06-08 at 8 08 09 AM](https://user-images.githubusercontent.com/2958461/121182075-b5dbd300-c830-11eb-9f99-bf77323bce88.png)

**Comment by TheDuckCow** [comment]
This has been resolved now in the DEV branch thanks to https://github.com/TheDuckCow/MCprep/commit/701af65558ec9fc83cff8d3d70c998ea7a3f2e15

Will be included in the next MCprep release.

**Comment by StandingPadAnimations** [comment]
I've also noticed that when you swap textures, the UVs sometimes don't get aligned. I assume this is due to differences in the texture pack(this specific texture pack is Vanilla PBR):
![image](https://user-images.githubusercontent.com/75058058/125869131-89cd9214-3ccf-450f-b3e6-bb80ce85d1bf.png)

**Comment by TheDuckCow** [comment]
In this scenario above, I think the issue more has to do with lanterns being animated textures and, for performance reasons, I don't have MCprep animate textures by default. You should hopefully be able to fix by either ticking the "Animate textures" box (default off) when swapping resource pack, *or* just run the animate textures option under advanced later when you like. Let me know if that doesn't do the trick though.

**Comment by TheDuckCow** [comment]
Closing this issue as it's been resolved and pushed as part of the latest MCprep update
