### ISSUE TITLE
addon not working on blender 2.93 

### ISSUE THREAD

**Issue by TheMorzh** [TheDuckCow/MCprep#215]
when i trying to enable MCprep 3.2.5 in blender 2.93 it's not working
![Screenshot_3](https://user-images.githubusercontent.com/64780191/121570393-7aa4f400-ca2a-11eb-8caa-0b6c3908eeb2.png)
in blender 2.92 it's working properly
![Screenshot_4](https://user-images.githubusercontent.com/64780191/121571074-3c5c0480-ca2b-11eb-9e5e-695855239d90.png)

**Comment by TheDuckCow** [comment]
Can you try closing blender and re-opening again? And if that doesn't work, full uninstall MCprep from blender 2.93 (not just untick, but fully remove by pressing the x button and confirming), then close blender, and finally reopen and install fresh.

The addon definitely works in blender 2.93, as I am [seeing plenty of non-error usage](https://theduckcow.com/dev/blender/mcprep/mcprep-stats/) analytics coming through for Blender 2.93 + v3.2.5 + Windows (which I see you are using).

**Comment by TheMorzh** [comment]
strange bug, i just set "none" in betas on steam and now all works, sorry
