### ISSUE TITLE
I Installed the new Mcprep3.2.5 in Blender 9.3 .But it still shows me the same error when I tried to install the previous version(3.2.4).

### ISSUE THREAD

**Issue by DImonANimateZ** [TheDuckCow/MCprep#216]
@TheDuckCow 
![image](https://user-images.githubusercontent.com/85753497/121709941-b1e0d700-caf6-11eb-8d4d-d0615ba85464.png)

**Comment by TheDuckCow** [comment]
Firstly, try fully un installing all versions of MCprep (the fact that the panel still shows up even when it is unticked shows something has gone awry). Then, very important, **close blender**. Re-open, install one version of MCprep from the https://theduckcow.com/MCprep and tick the box to enable that version.

**Comment by DImonANimateZ** [comment]
Hey.nvm it seems to be working today.Thankyou for your reply though.

**Comment by TheDuckCow** [comment]
No worries! It's a common issue people face, python files don't fully get reloaded unless you restart blender.
