### ISSUE TITLE
Hi! Will you add Blocks(dirt,stone etc..) and other blocks like Lantern in the future to Mcprep?

### ISSUE THREAD

**Issue by DImonANimateZ** [TheDuckCow/MCprep#217]
@TheDuckCow It will be really usefull.So we dont need to be appending stuff.

**Comment by TheDuckCow** [comment]
Hi there! Yes, indeed it's planned and even some code already is in progress (thanks to some contributions):

https://github.com/TheDuckCow/MCprep/issues/77

Closing this as a duplicate thread, but feel free to weigh in on this other thread.
