### ISSUE TITLE
I cant select the checkbox.

### ISSUE THREAD

**Issue by 1percentbattery** [TheDuckCow/MCprep#219]
If i try selecting the checkbox this error message shows up..
![image](https://user-images.githubusercontent.com/85903895/121952102-a7018e80-cd10-11eb-853c-0f6e3a3fa03c.png)

**Comment by TheDuckCow** [comment]
Similar to https://github.com/TheDuckCow/MCprep/issues/218 please try restarting blender, and at worst, delete the MCprep addon, close blender, re-open, and re-install MCprep.

**Comment by 1percentbattery** [comment]
I tried restarting blender, removing the MCprep addon, and even uninstalling blender and none of this fixed it.

**Comment by TheDuckCow** [comment]
Okay thanks for trying these steps.  In this case, can you restart blender one more time, but then specifically screenshot the *first* popup that occurs? The screenshot included is what would show if "something went wrong" and then you tried re-ticking the box again.

**Comment by 1percentbattery** [comment]
There are not any other popups that appear other than the error popup.

**Comment by TheDuckCow** [comment]
Thanks for sharing that, though has me a little stumped. Do you encounter the same thing on blender 2.92? If by chance you are able to screen record start to end (ie from first opening blender and installing MCprep, after searching to affirm it wasn't already installed) that would help as well.

**Comment by 1percentbattery** [comment]
Yes i encounter the same problem with 2.92.
And here is the screen record.

https://user-images.githubusercontent.com/85903895/121969193-9f4de400-cd28-11eb-8a6f-864e8482e4b9.mp4

**Comment by 1percentbattery** [comment]
Wait. i got it. i just had to download 2.91.

**Comment by TheDuckCow** [comment]
Thanks for sharing this screen recording, it actually helped me pick up the specific error message in the first popup. Pasting it here for my future self, I'm actually going to re-open this as - while 2.91 works for you, I want to make sure the latest versions of blender work for everyone.

<img width="626" alt="first_enable error" src="https://user-images.githubusercontent.com/2958461/121988472-5e75bf80-cd68-11eb-9b77-2285b800a270.png">

Final question for you in the meantime:
- Did you previously have MCprep installed with your blender 2.92 or 2.93 versions?
- What about any older versions in the past?
- In blender 2.92 / 2.93, if you search for MCprep in user preferences, does it show up just once, or are there multiple?

**Comment by 1percentbattery** [comment]
Yes I had it installed on 2.92 on my old laptop and I recently got a new one.

No I never had it installed on any other versions installed in the past.

Just once.

**Comment by TheDuckCow** [comment]
Are you still running into this issue? If so, any chance you're will to do a live troubleshooting call e.g. through discord? It seems more than one person is running into this and it'll be easier for me to come up with other things to try through a call.

If not, maybe just let me know if this somehow works: Disable (no need to remove, just disable) other manually enabled addons, and then once more, remove MCprep, closing blender, and re-install.

Another thing to try: Can you share exactly what version of blender you are using? I also wonder if it's a dev version which is causing some issues (and if so, consider trying by re-downloading the official master version from the blender website). You can see the exact blender version top-right in the initial splash screen, just copy the screenshot here if you can. Other details like if it says nightly or has other characters after the version number are relevant too.

And to be clear, in terms of your *new* laptop, this is the first time you have been trying to install MCprep on it correct?

**Comment by tackattack** [comment]
any fix for this yet?

**Comment by TheDuckCow** [comment]
Closing this issue after much delay, since there's been a more recent release. If there's any enable-ing issues at this stage, will handle in a new issue thread (you can always link to refer back to this one though).
