### ISSUE TITLE
Redesign spawner panel UI

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#222]
With [entity](https://github.com/TheDuckCow/MCprep/pulls) & [generic block](https://github.com/TheDuckCow/MCprep/pulls) spawners coming, the Spawner panel is going to get too crowded to show all modes at once. Additionally, while most spawner features are enforced and should continue to only be accessible in Object mode, I do want to create a power user feature where spawning an item in pose mode automatically parents (and possibly repositions) the spawned object at the active bone. What this means is that there will be different poll contexts for the spawner categories, and so we have to think about how this structure will appear.

To reiterate the types of spawners we will have:
- Mobs (same as today, animatable rigs and player characters)
- Items (same as today, items that you can hold similar to in game)
- Blocks (Will be new, as defined by vanilla or even 3D resource packs)
- Entities (Will be new, custom made models, and sometimes rigged, like bows & arrows, boats, signs with text already setup etc)
- Meshswap (Same as toady; different to blocks, because these can have special animations and pre-setup modifiers. But will likely stay rather limited).
- Structures (Longer term feature idea, prefab structures like trees, houses, and more which are defined by blocks specified above)

## The New UI proposals

Current ideas, but open to input:

1. Keep it as a horizontal list with text
   - Listing more for completion; this is what we [have today](https://user-images.githubusercontent.com/2958461/123533179-30d23400-d6e1-11eb-916a-5d71216e5b7a.png), and what I'm saying is *not* feasible because all text would get truncated.
2. Keep horizontal list, but assign icons for each spawner type. 
   - The categories already don't exactly map to Minecraft in a meaningful way, so the icons will likely be too abstract and not clear what purpose they serve. I think text is better.
3. Move it to a dropdown list (ie similar to how the Mob Category under mob spawner is a dropdown).
   - This ensures that text stays readable and that the panel is still quite compact
   - However, it means that you won't see all spawners at once as they are hidden in a dropdown. New users may entirely miss that there are other spawners beyond the default first one (which is likely to be Mobs).
4. Move each spawner type into its own subpanel (similar to how you have collapsable subsections in different panels of the properties window).
   - This way, each spawner type can have its own draw poll and specific errors separate to others (ie if allowed in Pose mode or not). If they are all added as collapsed by default, it's also quick and easy to see the full names of all spawners available (instead of being hidden in a dropdown).

At this moment, I'm leaning towards option 4 above, but keen to hear what advice other might have. Additional considerations include making sure the change is intuitive for existing MCprep users, knowing that any video tutorials will be immediately outdated. This is ok, as long as things are just as clearly visible as before (which I think we get with option 4, but would lose with option 3).

**Comment by StandingPadAnimations** [comment]
Perhaps make a new panel here for easy access. The N panel is pretty small and it would be nice
![image](https://user-images.githubusercontent.com/75058058/125868957-20cc43f0-2463-447d-80c1-9c6eb6375044.png)

**Comment by TheDuckCow** [comment]
That's an interesting idea actually!

@StandingPadAnimations do you think it should be just one entire new tab for MCprep? I need to research how to create new categories, but most likely it would have to be at the very bottom. At worst, it would need to be located in one of the tabs (or split across multiple by context). 

I think the spawner issue remains though, still have to think how to show the 4+ different spawn modes. I could do one sub panel for each in this mode potentially though, just feels extraneous and a lot of nesting.

**Comment by StandingPadAnimations** [comment]
I think one tab should be fine(to avoid overwhelming users). Though perhaps for the spawn modes, there could be a drop down menu for them

**Comment by TheDuckCow** [comment]
To reiterate the current state of things, unless I come up with and commit to a different design, the next release will look like:

<img width="248" alt="spawner current" src="https://user-images.githubusercontent.com/2958461/147708302-e66a15da-fc16-427c-94ca-369d8d6f4ae8.png">

The next best simple approach would be converting the horizontal bar into a dropdown (I don't like this because someone who doesn't press the dropdown won't see all the other options), or just have individual subpanels for each (though the panel gets to be quite long if all are expanded).

**Comment by StandingPadAnimations** [comment]
What about a vertical bar?

**Comment by TheDuckCow** [comment]
Pre recent commit, I've gone for the following UI, so that Shift-A and the panel order+icons match. (Shift-A is still less convenient, since there's no current capability to search in that context, may find a way to improve this over time).

<img width="959" alt="updated ui" src="https://user-images.githubusercontent.com/2958461/147863697-db58742f-7fdb-4d5a-bdb8-b2fb3273a78a.png">

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime as I think this UI is good enough to not further delay a release.
