### ISSUE TITLE
Black water textures

### ISSUE THREAD

**Issue by Topmaster4545** [TheDuckCow/MCprep#225]
So I just started using blender a week ago. Since i was new to blender i went to youtube to find some tutorials. On one of the tutorials, i copied whatever the youtuber did. On the second episode (video link: [https://www.youtube.com/watch?v=b9ARMSvPhu8&ab_channel=Judothesurviver], the youtuber was using Mcprep on the world. I did what he said, but when i looked at the water it was black.
![Screenshot 2021-07-12 114649](https://user-images.githubusercontent.com/87324574/125317326-ecf94480-e306-11eb-8ff1-72ef4d4a08cd.png)
If theres any answers to make it to a normal water texture, please respond. Thank you!
(note: since im new I might have done something wrong?)

**Comment by StandingPadAnimations** [comment]
Can you send a screenshot of the material nodes? Without it, it's hard to tell what went wrong. Your best bet is to prep materials again. You should also choose the exporter you used since that may also be the issue. 
![image](https://user-images.githubusercontent.com/75058058/125868830-1063b360-a9d3-483e-aa7a-beb26fb54c12.png)

**Comment by Topmaster4545** [comment]
sorry i didnt reply eariler, i had other things to work on. Heres the screen shots
![Screenshot 2021-07-21 095844](https://user-images.githubusercontent.com/87324574/126501573-66f8fcda-6251-424c-ab4a-4c794e26bb82.png)
![Screenshot 2021-07-21 100006](https://user-images.githubusercontent.com/87324574/126501585-785a5488-b120-492d-ab0a-c2ae82b01670.png)
![Screenshot 2021-07-21 100050](https://user-images.githubusercontent.com/87324574/126501588-93194083-5675-46d7-ba2f-013cdfa68f43.png)
![Screenshot 2021-07-21 100025](https://user-images.githubusercontent.com/87324574/126501589-f10566da-37de-4030-9402-785c231dbc35.png)
.
I think these are the material nodes? And i choosed what exporter to use and prep materials after what i saw here, it didnt work.

**Comment by StandingPadAnimations** [comment]
Can you show the material nodes? From these, I can only assume it's as simple as switching the texture here: 
![image](https://user-images.githubusercontent.com/75058058/126527325-2fb8b88e-db06-476e-bc4c-6c1c8bc7a415.png)

**Comment by Topmaster4545** [comment]
ok like this?
![Screenshot 2021-07-21 131018](https://user-images.githubusercontent.com/87324574/126530607-2eb352da-dc59-4766-abb7-4670dd36b6e0.png)

**Comment by StandingPadAnimations** [comment]
The texture should be water.png without any number after. You should also purge all orphan data and then reprep ad see if that works

**Comment by StandingPadAnimations** [comment]
I'd say either reimport the world in a new file and then prep materials, or re-export(as a last resort)

**Comment by StandingPadAnimations** [comment]
I'll close this issue for now since it's been a few months and seems to mostly be a texture issue rather then an MCprep issue
