### ISSUE TITLE
Cant find MCprep for check it 

### ISSUE THREAD

**Issue by Naim00** [TheDuckCow/MCprep#226]
If i select the zip Folder to Install the add on it doesn’t show on.

I dont have the                                                 ◼️Objekt: MCprep

**Comment by StandingPadAnimations** [comment]
Did you type mcprep in the search bar? Also, what version of Blender and what version of MCprep?

**Comment by StandingPadAnimations** [comment]
can you send a screenshot(On Windows, use Shift, Windows Key, S. On Mac, use Shift, Command, 3)

**Comment by Whyyyy234** [comment]
Remember to install the zip version of mcprep and not the one that turns into a folder or unzipped. Safari unzips downloads automatically and to turn off you go to safari preferences and uncheck "open safe files after downloading".

**Comment by Naim00** [comment]
thanks for help, but i just tried it again and it worked.

**Comment by TheDuckCow** [comment]
Glad to hear it worked! And thanks all for helping troubleshoot here.
