### ISSUE TITLE
Skin changing on mobs?

### ISSUE THREAD

**Issue by TheAtlo** [TheDuckCow/MCprep#227]
Hello there! I'm sorry if this is well-documented somewhere, but i just can't seem to find it. I have a rig of an axolotl, and i want to change the color from pink to gold, but i can't find anyway to do this. Thank you in advance!

**Comment by StandingPadAnimations** [comment]
There should be a variant slider 
![image](https://user-images.githubusercontent.com/75058058/125868612-d4fb843e-fadc-423d-acd3-e36eb4b4ff12.png)

**Comment by TheDuckCow** [comment]
One other factor is: make sure to turn *off* prep materials when spawning the rig, otherwise the material nodes get reset (undoing any benefit the variant setting pictured above has).

**Comment by TheAtlo** [comment]
Thank you, it helped!
