### ISSUE TITLE
Water grided while using "Prep Texture"

### ISSUE THREAD

**Issue by SolomonGarrett258** [TheDuckCow/MCprep#228]
![0118](https://user-images.githubusercontent.com/86562845/126035451-000fde55-f3f9-4713-9929-f18e545b5f2c.png)
Blender version: 2.79
MCprep version: 3.2.5
Mineways version: 9.0.0
Cycles Rendering Engine

**Comment by StandingPadAnimations** [comment]
Weird. I'd recommend switching to 2.93.1(hint, you can select 2.7x keybinds if you want and most things remain in the same location).

**Comment by SolomonGarrett258** [comment]
> Weird. I'd recommend switching to 2.93.1(hint, you can select 2.7x keybinds if you want and most things remain in the same location).
I've tried that too. But this glitch still take place :(

**Comment by StandingPadAnimations** [comment]
Have you tried re-exporting the world?

**Comment by SolomonGarrett258** [comment]
> Have you tried re-exporting the world?

No. I'll try that later and see if this glitch can be solved

**Comment by TheDuckCow** [comment]
Hi there - to me this looks like the classic issue of using animated textures but in a mode where the textures from Mineways were not using the "export to tiles" setting. The result is that the UVs of the water are scaled really far in, and it appears like a near solid or 2-color image for the entire block. You can either try turning off animate textures, or re export from Mineways with the "export to tiles" option ticked (which will create 1 image on disk for each block face texture).

**Comment by SolomonGarrett258** [comment]
> 你好 - 对我来说，这看起来像是使用动画纹理的经典问题，但在 Mineways 的纹理没有使用“导出到瓷砖”设置的模式下。结果是水的 UV 被缩放得非常远，并且整个块看起来像一个近乎纯色或 2 色的图像。您可以尝试关闭动画纹理，或者从 Mineways 重新导出并勾选“导出到瓷砖”选项（这将为每个块面纹理在磁盘上创建 1 个图像）。

Thanks a lot. The problem has been solved. Appreciate it.
