### ISSUE TITLE
My MCprep says error.

### ISSUE THREAD

**Issue by DaMinecraftItsme** [TheDuckCow/MCprep#23]
Can someone please help me with my mcprep? When I try to add it it says error.

**Comment by TheDuckCow** [comment]
Can you upload a screenshot of the error? Can you also confirm what version of blender you are using, and finally - are you using the latest version from [theduckcow.com/dev/blender/mcprep-download](http://theduckcow.com/dev/blender/mcprep-download)?

**Comment by DaMinecraftItsme** [comment]
<img width="401" alt="capture" src="https://cloud.githubusercontent.com/assets/28122047/25509626/60b75442-2b88-11e7-89ab-6ee3fda20607.PNG">

My Blender Version is 2.74

And yes I am using the latest version

**Comment by TheDuckCow** [comment]
That's quite strange - I know exactly what causes the error (the fact that custom icons aren't available until blender 2.75), but MCprep v3.0.1 should have fixed that based on my own testing. In the meantime, I can asset that it will work if you use blender 2.75 and higher. Meanwhile, I'll look into whether v3.0.1 truly still doesn't fix these errors for older blender versions. 

Maybe as one last plug to try it - try completely removing the MCprep addon, closing blender, then installing the new 3.0.1 version and see if it works then.

**Comment by DaMinecraftItsme** [comment]
Thank You so much!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
