### ISSUE TITLE
Crop and kelp become pitch of black when far away

### ISSUE THREAD

**Issue by SolomonGarrett258** [TheDuckCow/MCprep#230]
![微信截图_20210720230427](https://user-images.githubusercontent.com/86562845/126351139-26a07b30-a2ba-499d-88ca-f032fe957d8a.png)

Blender version:2.79
MCprep version:3.2.5
Mineways version:9.0.0

**Comment by TheDuckCow** [comment]
This is an issue with cycles, you need to increase the number of transparency passes. What is happening is that each time a light ray goes through a transparent part of the mesh, it has to calculate it (counting as one pass), and once you get through the first default number (like 12 bounces if I recall) it stops calculating. Note: increasing bounces will increase render time, just be aware of that.

**Comment by SolomonGarrett258** [comment]
> This is an issue with cycles, you need to increase the number of transparency passes. What is happening is that each time a light ray goes through a transparent part of the mesh, it has to calculate it (counting as one pass), and once you get through the first default number (like 12 bounces if I recall) it stops calculating. Note: increasing bounces will increase render time, just be aware of that.

I thought I've increased high enough. Is 48 enough for this?

**Comment by TheDuckCow** [comment]
A good way to test is to save this render, then increase it even more to like 100, and see if it helps a little by comparing the two renders side by side (try using render layer slots in blender's image viewing on the Rendered Result image, pressing j to toggle back and forth between two; just be sure to press j once before starting the second render).

It would make sense for a shot like this that the number is quite high. Again, a light ray going through one transparent plane counts as one bounce. For a single block of crops, a light could go through anywhere between 1 and 4 planes (think: going through at a horizontal diagonal angle). Worst case scenario, you're only going 12 blocks back before you hit the limit.

**Comment by SolomonGarrett258** [comment]
> A good way to test is to save this render, then increase it even more to like 100, and see if it helps a little by comparing the two renders side by side (try using render layer slots in blender's image viewing on the Rendered Result image, pressing j to toggle back and forth between two; just be sure to press j once before starting the second render).
> 
> It would make sense for a shot like this that the number is quite high. Again, a light ray going through one transparent plane counts as one bounce. For a single block of crops, a light could go through anywhere between 1 and 4 planes (think: going through at a horizontal diagonal angle). Worst case scenario, you're only going 12 blocks back before you hit the limit.

Finally. It's solved. thanks
