### ISSUE TITLE
A problem with Add-on installation

### ISSUE THREAD

**Issue by NoLifeLT** [TheDuckCow/MCprep#234]
There is the McPrep bar on the side even though the add-on is not even enabled

![ed1a81689c3beb5f60a2173a93c26f76](https://user-images.githubusercontent.com/60213857/128178801-581f1af6-dcdf-459f-ac65-f17cbb96abb7.png)

When I try to enable the add-on this error pops up. I had the add-on for the older version. 

![6c1694db761a8c923947c8c6d53db3e1](https://user-images.githubusercontent.com/60213857/128178810-e7932dbc-26ba-42d2-ad54-ac58eade3dd1.png)

I tried to: 
Restarting pc
Restarting blender
Tried installing an older version
Removed the add-on through preferences and then installing it again
Deleting the McPrep folder in the addon folder

Nothing is working :(

**Comment by StandingPadAnimations** [comment]
What version of Blender is it? I assume 2.93?

**Comment by TheDuckCow** [comment]
Can you try restarting blender? The fact that I see an error popup indicates something else went awry, possibly on enable/disable where it failed to fully load/unload. I have been seeing this error recently also as people have attempted to update the addon without restarting blender, maybe this is a culprit here.

**Comment by NoLifeLT** [comment]
Blender just came out with a newer 2.93.2 version and everything got fixed! I am not sure what was the problem.
And I definitely tried to restart blender but it didn't help. I even restarted my pc and it didn't help either. 
So I don't know if I should close this thread since the only thing that fixed the problem was the new unexpected update haha

**Comment by TheDuckCow** [comment]
Ok very interesting, thanks for sharing those steps you went through. Any chance you tried to fully delete the addon, close blender, and reinstall and found that still didn't help? If not, that would be my guess - some python cache could have been sticking around messing it up.

**Comment by NoLifeLT** [comment]
I am pretty sure that I tried out everything. But maybe I restarted my computer before deleting the files. Well, I can't really test it out anymore haha. Hopefully, it doesn't happen again and if it does I will try to post about it again if I can't solve the problem

**Comment by TheDuckCow** [comment]
No worries at all - once again, thank you for your commentary here! I'm going to close the issue for now, but will keep this in mind to respond to other case by cases where someone has this issue.
