### ISSUE TITLE
Can not download old version

### ISSUE THREAD

**Issue by ZACHODXD** [TheDuckCow/MCprep#236]
I was trying dowload 3.0.0 version of MCprep but always download new how install ??? old version

**Comment by StandingPadAnimations** [comment]
MCprep still works in older versions. Just download the newer version

**Comment by TheDuckCow** [comment]
For some reason my reply didn't end up here, but you can download all [old versions of MCprep here](https://theduckcow.com/dev/blender/mcprep/releases/) if needed; but as StandingPad said, there has been no drop of support for older systems, so I'd love to know what motivated you to try an older version. Closing the issue for now, but would love to hear an answer on the question if you're able! (You can still reply after a thread is closed).
