### ISSUE TITLE
spowing costum mobs can be cursed 

### ISSUE THREAD

**Issue by Nicccolisaylors** [TheDuckCow/MCprep#238]
I have tried the posabilatys for this problem. first, it did not show the amintcer, I fixed that. 
but a new  problem happend. I was modifiying your addon with block bench. the other free mincraft progrom.  this is a texture of a zombie I made. 
![zombie1 0](https://user-images.githubusercontent.com/83309740/128616305-ecff9826-ee5f-451e-8388-00bbdfc02798.png)   
but when spwed it is the other zombie texture and loses an leage and both arms.  is this normal? plese update the spown problem  and add more fetures for installing mobs.

**Comment by StandingPadAnimations** [comment]
So wait, was the mob ever a in a blend file(i.e, you ported it to Blender before actually adding it to the spawner)? If not, try porting the model to Blender itself first before adding it to MCprep.

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime as being outdated, but let us know if there's still an issue you think we can address in MCprep itself.
