### ISSUE TITLE
Optimizer for MCprep

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#239]
Currently, MCprep does some small optimizations to scenes in Cycles, but it would be nice to have a optimizer built for MC animation. Maybe 2 options(Quality and Speed) for CPU, CUDA, OptiX, and OpenCL. In later versions of Blender, we could also take advantage of adaptive sampling(perhaps a flag that tells MCprep that the user is using a later version of Blender)

**Comment by TheDuckCow** [comment]
Would love to hear your thoughts of all the settings you'd apply! Let me know if you think differently, but this could be great for the "prep world" button (which tbh should probably be renamed to "optimize" or something like that, which is mostly what it does right now). We could definitely have a dropdown property for different "modes", and even be reactive based on Eevee or Cycles being selected.

**Comment by StandingPadAnimations** [comment]
I think it could have light bounce optimization. Firstly by setting max light bounces to 8 and transparency to 12 and some manual input for the other bounces like:
```
How many glossy materials do you have?
[ ] None or not a lot(1 to 2 light bounces)
[ ] a lot(2 to 3 light bounces)
```
Preferably this would be a slider for better visualization(at least for the user). I would also suggest adaptive sampling but it wouldn't be useful for 2.7x users. Ill try working on a concept for how it might look

**Comment by TheDuckCow** [comment]
Awesome, appreciate your willingness to mock it up! And yes, it shouldn't be a problem for use to insert some checks for "is blender 2.7x, then don't show XYZ option", MCprep already does that in a few places.

**Comment by StandingPadAnimations** [comment]
With Blender now getting Cycles X in the 3.0 release, the optimizer may also need another check for Cycles X features and changes

**Comment by StandingPadAnimations** [comment]
Ok, i'vs started work on it while testing some stuff for #273. I just need to iron out some bugs and make the UI easier to work with before submitting a pull request

**Comment by TheDuckCow** [comment]
Amazing, thanks a ton! Let me know if there's anywhere you are looking for inputs from me, and feel free to open a pull request even before it's ready (you can mark as a draft), just so I can see what you are doing and avoid overlap. On Apr 17, 2022 9:23 PM, StandingPad ***@***.***> wrote:
Ok, i'vs started work on it while testing some stuff for #273. I just need to iron out some bugs and make the UI easier to work with before submitting a pull request

**Comment by StandingPadAnimations** [comment]
I will close this now
