### ISSUE TITLE
Duplicate skin on all players.

### ISSUE THREAD

**Issue by Jeje2201** [TheDuckCow/MCprep#24]
Hi,
I have in my scene many players.
I added a sword from my files with the "append" button on blender. The item didn't got any texture, I clicked on "obj world import" and then the sword got texture on.
The problem? When I clicked on this button, it also (I think) linked all players with same 'info' 'id' idk how you call it but they have all the same skin ( the last one I added ) and when I change from one, it change for all, so I can't have anymore 1 different skin for each players..
I searched on internet some tutorials to unlink it or create a new material.
I did it, but since I do it, it change the skin on the little player, but doesn't affect the real one.
Here is an exemple : http://prntscr.com/f4z5cp
You can see 2 players got the same skin.
I clicked on the number "171" to make a single user copy of the skin and here is the exemple, the little skin changed, not the real one
http://prnt.sc/f4z7c5
Do you have any way to fix it ? 
Or does it mean if I click on this button after creating a new player mean all my work is just dead ?

Sorry for typo or misspelling, French here
If you need any infos or so, I will give you all I can

**Comment by TheDuckCow** [comment]
Hey @Jeje2201,

Thanks for using MCprep. The main thing I can think of is if you pressed the prep-materials button after importing the world and kept the "consolidate materials" button enabled. 
![screen shot 2017-05-06 at 10 18 25 pm](https://cloud.githubusercontent.com/assets/2958461/25777410/679c257a-32aa-11e7-950f-4a6c51868abb.png)

I see this affects all materials in the blend file which isn't entirely my original intention (I intended it to work essentially just on the selected materials). 

I may move to make that option *disabled* by default in the future. For now, make sure you just don't use combine materials if you have multiple skins, or fully rename the materials (as combine materials will consolidate e.g. mat.001 and mat.002 together, but not skin1 and skin2)

Let me know if that makes sense and solves your problem

**Comment by Jeje2201** [comment]
Oh, I just tried and it seem to not mess with other skin anymore even if I add a new item.
So thing is, if I want to add a new block/item and press the "obj world import" to give it texture, I just have to be sure to not check the "combine material" aka "Consolidate" and all skin wont update to the same skin, all seem to work. I just have to redo the work on the players I had before this problem but since you fixed the problem, I don't worry anymore for the next one I will create.
Thanks alot for your fast and pro answer.

**Comment by TheDuckCow** [comment]
Sorry about that - but! **try out the skin swapping feature**, it makes adding skins to characters very nice :) Just select all of the objects of a single character, and press e.g. skin from file and select the image to use.

![skin swapping](https://cloud.githubusercontent.com/assets/2958461/25778236/7cc89c3c-32c6-11e7-9016-4a15ff3f8688.png)

**Comment by Jeje2201** [comment]
I tried this way before, but I guess I didn't selected all of the objects of a single character because now **it's working perfectly**, skin apply perfect on each character and all the colors ( eyes, eyebrows, etc... ) apply for each players too! I don't have to re-do all the work and since there is more than 13 different characters, you made my day better haha! (Exemple of the previous screenshot who got fix http://prntscr.com/f52olc)
This is exactly what I need and there is no more any issue or problem since there is 2 ways to fix it! I hope people who got the same problem will see this to know how to fix it.
Thanks for your hardwork and for your complete answer!

**Comment by TheDuckCow** [comment]
Sure thing - I made the feature because it saves me a ton of time too :) Cheers - and message/[tweet at me](https://twitter.com/TheDuckCow) once you release or rendering something awesome with it - It looks great already!
