### ISSUE TITLE
Textures bug

### ISSUE THREAD

**Issue by JaanDev** [TheDuckCow/MCprep#242]
When I change a texture pack, all the texture get bugged, because the uv still thinks that it should use the atlas positions.

**Comment by TheDuckCow** [comment]
Can you share a screenshot of the output, as well what the textures looked like before swapping?

It could also be that you exported from Mineways and didn't tick the box to "export tiles", that's important in order to use this feature, as otherwise you end up with scaled UVs.

**Comment by JaanDev** [comment]
Hi, thanks for the response :)

Sadly, I can't send a screenshot right now, but maybe today evening or tomorrow. About Mineways, I'll try to use that option.

**Comment by JaanDev** [comment]
Awww man, it worked! Thank you very much!

I couldn't find an "export tiles" option though, but I exported the model texture to a separate folder.

Thanks for help again! :D
