### ISSUE TITLE
Asset Community Challenge (Oct 2021)

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#245]
# MCprep Asset community challenge!

We are seeking YOUR help to add new assets to MCprep! Show your skills, learn something new, and contribute back to MCprep by submitting to this October challenge. Bonus: Submissions for ["entities"] assets will be part of the upcoming [Entity Spawner](https://github.com/TheDuckCow/MCprep/issues/148) (timeline: Early November), however all assets will be evaluated to include in MCprep (see below for details).

We are looking for submissions of (these are ideas only):

- Entities (like rigged boats, text-editable signs, rigged bow and arrows), see [ideas here](https://github.com/TheDuckCow/MCprep/issues/148) **This is the preferred submission type, given the upcoming feature!**
- Mob rigs (like zombies or players), see [missing rigs here](https://github.com/TheDuckCow/MCprep/issues/160)
- Particle systems (like preset rain effects, explosions), see [ideas here](https://github.com/TheDuckCow/MCprep/issues/96)
- 3D modeled blocks for meshswapping (like custom wheat, 3D grass, flowers), see [missing here](https://github.com/TheDuckCow/MCprep/issues/117)

## How to enter this challenge

Anyone can join the challenge by following these steps:

1) Develop an asset yourself. It should be original work, made in blender. It should be something from Vanilla Minecraft in order to be considered to include in MCprep.
2) Create a new comment (reply) to THIS thread, attaching your blend file directly. Optionally attach a screenshot too so others can visualize your great work!
3) Include your name/title to be used in the [credits section](https://github.com/TheDuckCow/MCprep#credit). You may optionally supply a twitter/youtube/other social link.
4) In your comment, explicitly confirm: "I understand that I am providing this asset for use under the CC-BY (attribution) license". By doing so, you affirm you understand others may use or extend your asset without restriction, so long as they provide credit back to you or MCprep itself (which will include you in its credits).

## Deadline - Oct 31st!

To be part of the next MCprep release, and be celebrated as a challenge participant, post your entries by October 31st!

### I submitted my asset! But where can I show it off?

Share it on social media! We suggest you post it with a link to your comment on this thread (right click top right, copy link), and use the `#MCprep` hashtag.

### Does it have to be a Minecraft Vanilla [mob, block, item, entity, effect]?

Yes, if you want to create an asset that will be added to MCprep, it must be from Vanilla Minecraft. 

### Will my asset be included in MCprep?

If it's not one that already exists, then yes! The MCprep Helper team may need to edit your asset slightly to fit MCprep standards, but credit will still only go to you. If an asset is not to a minimum quality bar (as analyzed by the helper team), then we may ask for revisions or update it ourselves.

### Can I remake an asset already found in MCprep?

Yes, and it will be *considered* for replacing the existing asset. However, you are encouraged to focus on submitting assets *not* currently in MCprep. At a minimum, your contribution will live on in this repository.

### Can I enter multiple assets?

That would in fact be encouraged! Don't sacrifice quality, but having more entries means more assets available to future MCprep users (yay!)

### What if there are multiple submissions for the same asset?

That's ok! Please note this is not a contest, but a challenge to flush out what is missing from MCprep while also honing your 3d skills. However, only one version of any given asset will be included in MCprep to keep its download size optimized, decided on by the MCprep Helper team.

### What best practices should I follow when creating assets?

- Use official Minecraft vanilla textures. We want the default assets in MCprep to have a consistent feel and look, and be widely useable.
- Make sure any textures are packed into the blend file.
- Name any bones and objects in your blend file. For bones that have left/right versions, use `.L` and `.R` suffixes so that tools like "paste flipped pose" work.
- For any rigs: Name the root bone of your rig `ROOT` or `MASTER`. The root bone should be placed such that the "tail" of the bone is at the same level as the feet when the armature is in rest mode.
- Don't create overly stylized assets - excessive subdivision, custom textures, or (excessive) 3D extensions that make the rig stick out too much from anything else in MCprep may lead to it not being included. Some detail is good though!
  - Take a look at what's included in MCprep today to get an idea of what's expected.
  - The VMcomix rig is good example of what generally would be considered "too stylized", while the current Zombie rig is more on the fence.
- Avoid *excessive* driver use. Drivers slow blender down, but they do have their place.
- Make your assets to scale! You should be able to append it into an imported world where 1 blender unit = 1 meter, and have it fit without further scaling.

### When will MCprep be updated with the new assets?

The plan is to release the MCprep update in November 2021.

### What's the reward for entering the challenge?

Mostly the warm fuzzy feeling of contributing back to MCprep! But we'll also do some shout-outs for everyone who joined, pointing back to this page as a record of that. Expect a recap "challenge community" render to go out on social media and a potential youtube video too.

### I have more questions!

Please join our [discord server](https://discord.gg/mb8hBUC), and ask away under #contest-discuss.

**Comment by TheDuckCow** [comment]
With this, that concludes the community challenge - of course, MCprep will always take in new asset suggestions though. Will mark this issue as closed once MCprep releases with these assets.

**Comment by Ageofherosmedia** [comment]
[Shield.zip](https://github.com/TheDuckCow/MCprep/files/7755309/Shield.zip)

**Comment by TheDuckCow** [comment]
Closing this thread now as all the above have been integrated into the v3.2.6 release (to be released by the end of the year here). Thanks again all!

@Roni-Raihan your crack material is not part of this immediate release, I'm actually hoping to build more of a function out of this! I have to think a bit further how to wrap the UI around it or where to present it, but will notify you once I have (and maybe get your feedback). 

@Ageofherosmedia messaged separately about ensuring I get the right credit URL for you, which will end up in the README file.

**Comment by StandingPadAnimations** [comment]
For anyone still interested in submitting assets, just message on this thread. 

Some ideas for assets include:
* Replacing a rig. This is mostly if a rig is broken or could be better made
* A simple version of a rig. Basically, a rig that doesn't overwhelm the user
* A rig that doesn't exist yet. This could be rigs for new mobs or mobs that simply don't exist yet in MCprep

Here are some suggestions from TheDuckCow's message:
```

**Comment by zNightlord** [comment]
Start early and simple with the frog, taken from my MCB asset rigs @znightTrung on Twitter
How to use it? Frog has 3 types/variants so the body object use a Geometry Nodes modifier to switch that if it's fine for the time being. There is still something I want to add for it.
![image](https://user-images.githubusercontent.com/61040487/167669194-ab5127aa-2dbc-41a5-a384-ed1c1b3c16e7.png)
[MCB_Frog.zip](https://github.com/TheDuckCow/MCprep/files/8663043/MCB_Frog.zip)

**Comment by TheDuckCow** [comment]
Nice! @zNightlord are you planning to do more with the rig, or do you think it's ready to use as is? And is that the credit url you want then, https://twitter.com/znightTrung?

**Comment by zNightlord** [comment]
> Nice! @zNightlord are you planning to do more with the rig, or do you think it's ready to use as is? And is that the credit url you want then, https://twitter.com/znightTrung?
Sorry. It's already ready somehow. 
I was thinking about bring the Geometry Nodes switch to the Rigify rig layer panel for easy access.
It can modify the value but not really update the actually thing maybe that has something to do with current state of the API for GN. Or maybe just put it as a rig slider. 
The allay mob rig should be coming next.

**Comment by zNightlord** [comment]
[MCB_Allay.zip](https://github.com/TheDuckCow/MCprep/files/8793706/MCB_Allay.zip)
![image](https://user-images.githubusercontent.com/61040487/170879400-bb192cdc-fcff-487e-8f24-3333748c0462.png)
Since the Allay's arms quite tiny so I decided to not doing sharp bend on this one. Should this have facial later on?

**Comment by TheDuckCow** [comment]
Thanks for sharing both of these! I'll be taking a look. Generally I'm avoiding including geometry nodes in rigs at all just to ensure that there is good backwards compatibility, but I'll take some time later to do some quick QA and see if I run into any issues.

In terms of scripts, if there are any scripts that should go along with the rig, I end up putting that alongside the blend file with a .py extension, so that MCprep auto loads it. Even if it's coming from rigify, would need to be its own script so that it stays compatible with the way that MCprep can load scripts (but I can take a look at what that involves).

**Comment by DigitalDan-68** [comment]
Sending in the warden rig I recently made. The way it's rigged is more in line with the promotional trailers then what most would consider is the minecraft animation style. 
![image](https://user-images.githubusercontent.com/107087467/172513193-1f8e9793-b533-4894-8a7b-e29c4a833306.png)
The rig has full IK-FK Support for the arms and legs.
![image](https://user-images.githubusercontent.com/107087467/172513287-cd175cbf-efb6-42d6-8b20-9da787781213.png)
The legs have a Minecraft Dungeons style of bending.
![l9OWgCt](https://user-images.githubusercontent.com/107087467/172513474-184b9cc5-b1d5-47f6-b57b-0d1e590369f1.gif)
Has an animated material for the Heart and Sculk patches.
![image](https://user-images.githubusercontent.com/107087467/172513417-4b7d9311-0ca5-47f9-9d22-303fad4af8ac.png)
I've also included the Sonic Boom Attack, although this could probably be done a lot better.
![d58uWA9](https://user-images.githubusercontent.com/107087467/172513603-79299091-4345-47db-8d4a-0841cfaaa7ce.gif)

And that's everything, Here is the file itself: 
[Warden.zip](https://github.com/TheDuckCow/MCprep/files/8857628/Warden.zip)

I hope the rig is added and many others can use it!

Credits:
Rig by (Me) @DigDanAnimates on Twitter

**Comment by Roni-Raihan** [comment]
holiday has arrived, now back to work on unfinished projects including the cat rig. Planning to share this cat rig with MCprep 😄️
![untitled](https://user-images.githubusercontent.com/82071318/173562319-18048836-21c8-4126-bf04-bae9ab855db8.png)

**Comment by TheDuckCow** [comment]
Amazing @Roni-Raihan - if you happen to be able to share within the next ~3-5 days, then I can be sure it's included in the next MCprep release!

**Comment by TheDuckCow** [comment]
Hello all! On a going forward basis, please try to avoid using these settings when creating your rigs:

<img width="227" alt="Screen Shot 2022-07-04 at 10 29 17 AM" src="https://user-images.githubusercontent.com/2958461/177198634-0e2204cb-b16d-461a-a3b7-c4b608b31df6.png">

These were introduced in Blender 3.0, and it breaks backwards compatibility. As a test, you can always try importing your model into Blender 2.93 and see if your rig appears (if having trouble, open your rig in blender 3.0, then save as a new file, then open blender 2.93 and append the collection from the 3.0 file you just saved). It's a decent bit of manual effort for me to fix, but I'm working through it on these rigs submitted where needed.

To avoid using these transforms, you just need to make sure your source bone object has the right scale and orientation. This is required to continue ensuring MCprep works across a wide range of versions of blender. Believe it or not, following this allows me to continue supporting these rigs as far back as blender 2.78. Thanks!

**Comment by TheDuckCow** [comment]
Minor update, I actually have to take back what I said in the last comment - unfortunately, it appears that vertex group data is completely lost when going form blender 3.0 to 2.9 or earlier. There's no non-trivial workaround for this, aside from exporting rigs to FBX and reimporting. I may end up having to do this simply to provide backwards compatibility, but all aspects of customized blender controls (properties, drivers, advanced material animation, and custom bone shapes) would be lost during this conversion.

I strongly encourage anyone where possible to create their rigs in Blender 2.93 for the most compatibility, but knowing this problem won't go away, I'll be seeing about other tech alternatives.

**Comment by zNightlord** [comment]
Backport the Frog to 2.93:
Switching the geometry to a driver method. Now the variant switch is on the rig panel.
[MCB_Frog_293.zip](https://github.com/TheDuckCow/MCprep/files/9043751/MCB_Frog_293.zip)
![image](https://user-images.githubusercontent.com/61040487/177262633-18491863-64cc-483e-9591-87c73c947a5e.png)

**Comment by TheDuckCow** [comment]
You're a rockstar @zNightlord for doing this, thanks a million for helping us improve backwards compatibility! You also made some great notes for others who end up dealing with this (which will include me, too); full credit to you:

---
What to change: 3.0 -> 2.93 
EditBones: 
BendyBone ScaleIn and ScaleOut 0.0 -> 1.0 (3.0 added new Scale Z axis)
PoseBones: 
Bone Viewport display: Custom Shape Scale to 0.0 -> 1.0 (3.0 added new Transform settings) 
Constraint Local Space (Owner Orientation) -> Local Space possible breaking in rig certain case
Constraint Mix mode in 3.0 they split Mix mode to Full, Align and Split change it to the correspond Before Original or After Original

About the bone controller and losing vertex groups
how I deal with it is export the deform rig version of it with fbx to preserve the rig vertex group
and append the rig armature back from 3.0+ to 2.93

**Comment by Banana-Blu** [comment]
Here is the spyglass model! Sadly there is no rig
[Spyglass.zip](https://github.com/TheDuckCow/MCprep/files/9056424/Spyglass.zip)
.

**Comment by TheDuckCow** [comment]
Thanks @Banana-Blu! And though I appreciate not needing to be credit, all provided assets are given credit. If nothing else I will use your name Banana-Blue as you have registered here and link to your GitHub profile.

Model looks good, might not even really need a rig at all which is fine.

**Comment by Banana-Blu** [comment]
Ok, happy to have helped!

**Comment by Roni-Raihan** [comment]
I want to confirm a bit, I haven't finished the cat rig yet. But it's good enough because it's not that far, so I can pass it on at 2.93 😁

https://user-images.githubusercontent.com/82071318/178105398-28ced8ca-e7ab-43ce-b0b6-bb75ba774660.mp4

**Comment by TheDuckCow** [comment]
Nice work @Roni-Raihan, excited to see it when finished! If by chance you get it ready in the next couple days, I can include it in the next MCprep release, otherwise the release right after isn't a problem.

**Comment by TheDuckCow** [comment]
Minor FYI @zNightlord that I went through the rest of my standardization process, and I was able to make your frog rig even further backwards compatible (by creating some slight modifications to the script and a slight mod to how the material nodes work, as for some reason the Average vector node was behaving differently in blender 2.8 and 2.7). You'll see it once MCprep releases.

I'm going to work on the Warden rig update next, and then I'll get to doing the Allay (if you happened to have started on that please let me know!).

**Comment by TheDuckCow** [comment]
Small update. I've given up on trying to backport the Warden rig, it's too complex with too many constraints and properties, my time is not best suited here. And regardless, this issue is going to continue. So instead, I've outlined a workaround here that TL;DR surmounts to stripping the rig down to basics after an FBX export:
https://github.com/TheDuckCow/MCprep/issues/317

**Comment by zNightlord** [comment]
> Small update. I've given up on trying to backport the Warden rig, it's too complex with too many constraints and properties, my time is not best suited here. And regardless, this issue is going to continue. So instead, I've outlined a workaround here that TL;DR surmounts to stripping the rig down to basics after an FBX export: #317

I checked and backported it.
[Warden_293.zip](https://github.com/TheDuckCow/MCprep/files/9128247/Warden_293.zip)
![image](https://user-images.githubusercontent.com/61040487/179418328-df4bde36-9a6b-4fa7-937d-62ccfeb44031.png)
I forgot about sonic boom thing. It's missing texture for me.

![image](https://user-images.githubusercontent.com/61040487/179417800-c8502197-9577-451d-90ff-a057ab9843bf.png)

Here is the script i made for the boneshape issue, which take the 3.0 transformation and create another set of boneshape in world space similiar to how rigify handle it except for the mirroring but it is fine.
```py
import bpy
from mathutils import Matrix,Vector,Euler
C = bpy.context

obj = C.object
obj_matrix = obj.matrix_world

pbs = obj.pose.bones

for pb in pbs:
    sh = pb.custom_shape
    if sh is not None:
        pb_matrix = obj_matrix @ pb.matrix # pose bone to world space
        # get 3.0 bone shape transform
        T = Matrix.Translation(pb.custom_shape_translation)
        S = Matrix.Diagonal(pb.custom_shape_scale_xyz).to_4x4()
        R = pb.custom_shape_rotation_euler.to_matrix().to_4x4()
        # bone length uniform scale
        len_bone = pb.length #bone  length here
        len_scale = Vector((len_bone,len_bone,len_bone))
        L = Matrix.Scale(len_bone,4)

        # create new boneshape object
        new_sh = sh.copy() 
        new_sh.data = sh.data.copy()
        C.collection.objects.link(new_sh) #link it to the scene optional
        
        # align it to world space
        new_sh.matrix_world = pb_matrix
        # transfrom the boneshape 
        new_sh.data.transform(T @ R @ S @ L)
        
        # apply and clearing out the 3.0 transform
        pb.custom_shape = new_sh
        pb.custom_shape_translation = Vector((0.0,0.0,0.0))
        pb.custom_shape_rotation_euler = Euler((0.0, 0.0, 0.0), 'XYZ')
        pb.custom_shape_scale_xyz = Vector((1.0, 1.0, 1.0))
        # unfortunately this need to be false
        pb.use_custom_shape_bone_size = False
```

**Comment by TheDuckCow** [comment]
Absolute rockstar legend @zNightlord, this will definitely work much better than my quick workaround FBX version. Thanks for also sharing that script as well, will note that down and possibly create a more official guide for this. All this being said, I still will consider it at this point a "bonus" for future rigs to be made backwards compatible (and thus not block inclusion), but it's a good thing to do where we can.

I actually skipped including the sonic boom anyways, I'm thinking that should be an animated instance effect like TNT explosions (though still needs to be created, we can get there in the future).

**Comment by zNightlord** [comment]
[allay._293.zip](https://github.com/TheDuckCow/MCprep/files/9130331/allay._293.zip)
backport, fix a minor issue with the previous version have (wing naming is backward and also now it has the same naming as other wing rig in my wip rigs) add 90 sharp bend.

For the backport Warden, there is an issue I haven't fixed is the custom properties min and max value just need to reset it back to 0 and 1.

**Comment by Roni-Raihan** [comment]
finally finished. At first I wanted to make the cat's mouth open, and I tried to make one. but the results are not suitable because it turns out that the cat's mouth only consists of a few pixels. so i returned it.
the cat texture included in the blen file is just a jelly cat. but i think it's okay. if you want to replace it, the way is the same as usual.
![cat rig](https://user-images.githubusercontent.com/82071318/180220415-112ee98d-a8bd-46c1-9fcb-95c5e24ec0d5.png)
[cat.zip](https://github.com/TheDuckCow/MCprep/files/9159553/cat.zip)

**Comment by TheDuckCow** [comment]
Thanks for the contributions all!

Officially removing this from pinned issues as we now have a formal template for submitting [assets here[(https://github.com/TheDuckCow/MCprep/issues/new?assignees=&labels=enhancement&template=Asset-Submission.yaml), please use this moving forward (you can submit an initial version of your rig and update later if you want). 

A couple assets had some wonky scales, but don't worry I'll take care of fixing those. Just remember this for the future!

**Comment by StandingPadAnimations** [comment]
I'll link this issue template to MCprep Helpful Horse when I get the chance
