### ISSUE TITLE
jmc2obj 113 uses a different texture path from 112 

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#248]
It seems jmc2obj changed the texture paths in 113(alongside supporting json models). A small update may be needed

**Comment by mmdanggg2** [comment]
Yes, that should be the case. There are a couple of small deviations:
blocks.conf is still used to manually set certain models and textures but all textures come from and will be named as they are in the resource pack.
The only exceptions to this are entries in the textures.json this primarily modifies textures with tints but it is also used to create a tinted version of textures under different names. Currently this is only used for the on/off state of redstone wires and biome tints for grass.
```json
{"id": "jmc2obj:block/redstone_dust_dot", "sourceIdOverride": "minecraft:block/redstone_dust_dot", "tint": "700000"},
{"id": "jmc2obj:block/redstone_dust_dot_on", "sourceIdOverride": "minecraft:block/redstone_dust_dot", "tint": "FD0101"},
{"id": "jmc2obj:block/redstone_dust_line0", "sourceIdOverride": "minecraft:block/redstone_dust_line0", "tint": "700000"},
{"id": "jmc2obj:block/redstone_dust_line0_on", "sourceIdOverride": "minecraft:block/redstone_dust_line0", "tint": "FD0101"},
{"id": "jmc2obj:block/grass_block_top-desert", "sourceIdOverride": "block/grass_block_top", "tint": "D1FEB3"},
{"id": "jmc2obj:block/grass_block_top-forest", "sourceIdOverride": "block/grass_block_top", "tint": "72B247"},
```

**Comment by TheDuckCow** [comment]
This has now been resolved with https://github.com/TheDuckCow/MCprep/commit/8901a5bf9f974d424fff239bf7188042ad7bc452 and will be included in the upcoming release.
