### ISSUE TITLE
texture isuues 

### ISSUE THREAD

**Issue by nisarg1234** [TheDuckCow/MCprep#249]
there are black spots in certain areas when rendered using camera close the surface. the issue occures in flowers, grass, wheat and other such textures especially if many are one behind or close to one another. The issue is not limited to one file. issue occurs in both mineways and jmc2obj 112 as well. so mostly the issue is with mcprep. and unable to delete mcprep as well
![Screenshot (86)](https://user-images.githubusercontent.com/69861688/138706335-b22e28cb-034f-4c18-834a-5ea10dc72ed5.jpg)
![Screenshot (87)](https://user-images.githubusercontent.com/69861688/138706351-d624becd-6a96-4bd8-8e68-2b306a3a1c9a.jpg)
![Screenshot (90)](https://user-images.githubusercontent.com/69861688/138706362-afc37edb-a1fb-422f-82c7-4fff50234268.png)

**Comment by StandingPadAnimations** [comment]
For that issue, try using CUDA since GTX cards can't use Optix well(they lack ray tracing cores to take advantage of Optix).

**Comment by TheDuckCow** [comment]
Closing this now as it's more a troubleshooting thing, feel free to comment back (or join the [discord community](https://discord.gg/mb8hBUC) for more realtime help).
