### ISSUE TITLE
Can this be fixed

### ISSUE THREAD

**Issue by MaxBans** [TheDuckCow/MCprep#250]
Hi, how is this happening please. I think its a bug or how can i fix it. 

![139591806-c63310c1-2639-4adb-a840-827bc64516c7](https://user-images.githubusercontent.com/74257956/139591827-ec4efca5-a622-4746-9be3-6ca0fb51be1f.png)
)

**Comment by MaxBans** [comment]
I mean like why are the textures so weird

**Comment by StandingPadAnimations** [comment]
This seems like your exporter had a hiccup. Try re-exporting the world. If you're using jmc2obj, make sure you're using 112 since 113 and 114 are not yet supported

**Comment by TheDuckCow** [comment]
Checking in @MaxBans - is this issue still occurring, and does it persist even before prepping materials (if you first go into material settings?

**Comment by TheDuckCow** [comment]
Closing this thread in the meantime, feel free to comment back if there are updates.
