### ISSUE TITLE
Using some custom resource packs results in white grass block sides in viewport and renders.

### ISSUE THREAD

**Issue by drepman** [TheDuckCow/MCprep#251]
![Screenshot 2021-11-08 194445](https://user-images.githubusercontent.com/74347921/140858284-5380641f-c31d-46a9-990e-0316af8b5c85.png)

Title pretty much says it all. I assume this has something to do with the pack requiring Optifine for some features? Is there a work around to get the normal green sides, an option I'm not seeing, or is this just a straight up bug? Shows up in both cycles and eevee.

**Comment by StandingPadAnimations** [comment]
I assume it's due to the pack requiring Optifine features. As a work around you can go to materials and replace the side blocks with the top blocks

**Comment by StandingPadAnimations** [comment]
as far as I'm seeing, the pack requires the multiside grass thing from Optifine, which is not in MCprep

**Comment by TheDuckCow** [comment]
StandingPadAnimations is right. So generally grass is re-colored by the node group in MCprep which overlays a color. Normally dirt with side grass doesn't need this, as default texture packs apply a sort of default coloring, and thus by default MCprep doesn't colorize it further (as it would further distort other colors too). However, you can manually re-enable it. See the screenshot below (after prepping materials):

<img width="735" alt="unmute" src="https://user-images.githubusercontent.com/2958461/142742515-7b87b40d-375a-4c7d-9fa7-50ec42f3150c.png">

**Comment by TheDuckCow** [comment]
Just bumping this up @drepman, let us know if the above comments help in this case!

**Comment by TheDuckCow** [comment]
I'm going to close this thread in the meantime. I considered whether to mark this as a feature request, but the variance between resource packs makes it not easy to implement. I will aim to leave the "add color" node in even the [simple material](https://github.com/TheDuckCow/MCprep/issues/263) mode method to make this workaround easy.
