### ISSUE TITLE
Animated textures issue

### ISSUE THREAD

**Issue by trex1882** [TheDuckCow/MCprep#253]
I am running into an issue with animated textures where they seem to be on their side

https://user-images.githubusercontent.com/51657122/142089313-02e3ef9b-c3d4-4464-90cd-5ccd80563b8b.mp4

https://user-images.githubusercontent.com/51657122/142089330-c21f8c2d-555d-41f8-8391-668a03186adf.mp4

**Comment by StandingPadAnimations** [comment]
I see you are using Mineways. There's a specific setting you have to use when exporting the world(this also applies to swapping texture packs). This video from TheDuckCow should give more info:
https://youtu.be/uk3pqDF6RCY

**Comment by TheDuckCow** [comment]
This is correct - let us know if you have any further questions! If you want to easily re-export your world again and then choose that setting, you can actually drag and drop your original obj file onto Mineways to load it up, when you export be sure to just select the "export to tiles" option.

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, but please let us know if the above help did not address your situation!
