### ISSUE TITLE
Request: add generator(textures of mobs)

### ISSUE THREAD

**Issue by Timtaran** [TheDuckCow/MCprep#255]
ex. tropical fish

**Comment by TheDuckCow** [comment]
Can you share more details of what process or workflow you are solving for? is it just to be able to pick different colors for mobs (in which case, these may be features of the rigs themselves), or is it about being able to export *textures* for use elsewhere?

**Comment by TheDuckCow** [comment]
No need to close it if there's a use case you have in mind! These are just clarifying questions so I can get a better sense of what you are looking for and what feature(s) would help with it.
