### ISSUE TITLE
Torches are the wrong way around

### ISSUE THREAD

**Issue by Tiefseetauchner** [TheDuckCow/MCprep#256]
I have no idea how this could happen, but the torches are the wrong way around
![image](https://user-images.githubusercontent.com/48085877/146672003-cca9ef99-993b-4045-8d5a-2bce30e9f482.png)
Also they aren't on the walls, but that could be because I scaled the model down

**Comment by TheDuckCow** [comment]
Did you 1) make sure you selected the right exporter on import? (ie if your world is from jmc2obj, you selected jmc2obj)? Also did you move the world at all, or is it in it's original imported location?

**Comment by TheDuckCow** [comment]
Closing in the meantime, please comment back if you have any updates or can confirm the above point.
