### ISSUE TITLE
Help, it won't let me activate MCPrep in Blender 3.0

### ISSUE THREAD

**Issue by TrineArtz** [TheDuckCow/MCprep#259]
I have no idea what is happening, but wanting to activate MCprep in Blender 3.0 I get this error. I have already had MCprep in version 2.8 of Blender and it works correctly.

![image](https://user-images.githubusercontent.com/96548004/147147882-ab697423-301e-44ae-9559-54c435403a85.png)

**Comment by StandingPadAnimations** [comment]
Try manually uninstalling MCprep and installing it again

**Comment by TrineArtz** [comment]
> 

Ty!

**Comment by StandingPadAnimations** [comment]
No problem. I'll close this issue for now

**Comment by Mario675** [comment]
## Another fix for this kind of issue:
- `Verify Integrity of software files` in steam. This can fix missing assets.

## What was my error message about?
![image](https://user-images.githubusercontent.com/69184238/147296965-39eca493-f003-476d-99fb-821ce7a3a92c.png)
