### ISSUE TITLE
In-blender reported bugs

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#261]
Listing below a barrage of bug reports that have multiple loggers. I will attempt to resolve all of these bugs, knowing some of them are blender version specific. ID's listed here are from the MCprep issue reporting database, which I use privately to track fixes. These are ordered in frequency of reports and number of users. Likely not all will be resolved for the target milestone. These are the top 11 I am focussing on for this iteration, will edit if others are resolved and reference this on release update.

- [x] #262
- [x] `-MobC6QO1QmbzwxXV0XE`: moonmesh.parent = get_time_object()\nTypeError: bpy_struct: item.attr = val: Object.parent ID type does not support assignment to itself\n
- [x] `-MrYyXulO3-4rR0Dlfo-`: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte\n, This is actually an issue with the obj files themselves, but MCprep could do better about telling the user something useful like "Try re-exporting your world" or "World cannot be read, may be corrupted". At the risk of PII I may consider also logging filenames, since this happens frequently enough it's worth understanding what people are actually attempting to do (are they selecting .zip files or something?)
- [ ] `-MfrrPFH3udKVFiitSLr`: context.object.material_slots[mat_ind].material = mat\nAttributeError: bpy_struct: attribute "material" from "MaterialSlot" is read-only\n
- [ ] `-Mpl6MOu1M6JEgEpTfaS`: enum "Non-Color" not found in ('Linear', 'sRGB') (many variations of this one, may not be able to do much about it)
- [ ] `-MhJp--Z7JIfZnnw45w1`: During item spawning (from list or file): RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect\n, I am doubtful I'll be able to find a simple fix for this one and seems very contextual. A geometry nodes alternate may be viable, though not backwards compatible. 
- [x] `-MoSSh6nd09YGfF7gEp_`: loops_uv = tuple(uv for (_, _, face_vert_tex_indices, _, _, _, _) in faces\n File "<addon_path>/import_obj.py", line 738, in <genexpr>\n for uv in verts_tex[face_uvidx]
- [x] `-MhwacqY_LI2NQ-7TijV`: asum += data[fnd][image.size[1]*row + col]\nIndexError: list index out of range\n (likely related to the above)
- [x] `-MgRXi1HSdOt7R23ZAZx`: method, block = self.block.split("/")\nValueError: not enough values to unpack (expected 2, got 1)\n, should more gracefully recover from this, though may be a legitimate upstream bug.
- [x] `-MhtywSS5IU1Wwc9WvlI`: RuntimeError: Error: Image 'water_still-seq-temp.001' could not be saved to 'textures\water_still\water_still_0001.png'\n\n, Let's at least create a better logging statement and more narrowly capture what error occurred to give a useful instruction (e.g. permission error? diskspace?)
- [x] `-Mm8BSy1cLw9UgTAdlAt`: Looks like an os path based issue: ...mcprep_default/assets\minecraft\textures\block\grass_block_side.png': No such file or directory\n\n
- [x] `-Mp-x0eXahGbiDeA3mkM` mcmeta = json.load(mcf), raise JSONDecodeError("Expecting value", s, err.value) 
- [x] `-MfnEBOpGxyEReFtGtNU`  load_linked\n act = context.selected_objects[0]

If anyone is curious about how issue tracking works, please see [more information here](https://theduckcow.com/dev/blender/mcprep/reporting-errors/).

**Comment by StandingPadAnimations** [comment]
* `-MrYyXulO3-4rR0Dlfo-`: I'd suggest having a try catch loop to handle the errors
* `-Mm8BSy1cLw9UgTAdlAt`: This seems interesting. I'd assume filepaths were done in a cross platform way(though this could be a Windows issue). I'll take a closer look once I get back from vacation
* `-Mpl6MOu1M6JEgEpTfaS`: This one is also pretty interesting. If the reports have Blender versions, which version has this issue the most. This might be fixed with a try catch loop. My suspicion is that it's a issue in older versions of Blender.

**Comment by StandingPadAnimations** [comment]
All of these seem interesting, but I'll have to take a look when I get back

**Comment by TheDuckCow** [comment]
Sounds good! I'll not focus on those ones first, but if I do finish other tasks up I'll comment back here before working on them to avoid any overlap. No rush and no worries if you don't end up having time, appreciate your willingness!

**Comment by TheDuckCow** [comment]
FYI I'm going to start tackling a few of these which are most critical, I'll be fixing the following at a minimum hopefully:
- -Mq_H0YG4q07eAC8CDlp
- -MobC6QO1QmbzwxXV0XE

Any that you get to that I don't can still be included in a near-after update of course! And if I end up ambitiously solving more than the two above, I'll tick the boxes above as complete.

**Comment by TheDuckCow** [comment]
Marking `-Mm8BSy1cLw9UgTAdlAt` resolved with https://github.com/TheDuckCow/MCprep/commit/55719ce2b1faa3d007f6b2c69c7d0083ac26a90a

**Comment by TheDuckCow** [comment]
Marking `-MhtywSS5IU1Wwc9WvlI` as "done" but really nothing was or could be done. It could be due to any number of OS issues, and specific errors are not passed forward by the function call to save the image constructed. Very few people have run into this.

**Comment by TheDuckCow** [comment]
Marking this issue as closed; not all were resolved, but enough that we shouldn't hold up future development as well as other now more commonly auto reported bugs.
