### ISSUE TITLE
Create a default "simple" mode for material generation

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#263]
At the moment, the default prep material shaders for Eevee and Cycles contain nodes that are relevant for only specular PBR packs, while the majority of users are using only default or simple Minecraft texturepacks which do not need all the extra features.

The consideration here is to make a simple shader that has pretty much just the bare minimum nodes connecting to a principled shader (for versions of blender where the principled shader is available).

Current ("Specular workflow"):
<img width="960" alt="current" src="https://user-images.githubusercontent.com/2958461/147326862-10fdc94f-0a90-4d17-8758-d9e830b4f62b.png">

Proposed ("Simple non PBR"):
<img width="794" alt="proposed" src="https://user-images.githubusercontent.com/2958461/147326870-cc52e550-7219-4976-8139-68c05b6b7eaa.png">

Note in the proposal, color is connected to emission, but emission is set to zero. It would be set to 1 for emissive materials. Note the displayed layout still has a separate transparent node: yes it would be simpler to use the alpha channel in the Principled node, however earlier versions of blender (which people still use) didn't have the alpha socket yet, so will need to see if I have time to implement the extra check against to see if the alpha socket is there to decide if we need to use a transparent shader node or not.

**Comment by StandingPadAnimations** [comment]
Instead of using material nodes for emission, lamps may be a better option. It'll make it easier for EEVEE users, and Cycles users won't have to deal with as much noise

**Comment by TheDuckCow** [comment]
Thanks for the comment! As per other chat, I think that will take a bit more time and consideration to implement, and can be moved into its own feature issue thread. Especially due to things like the [limit of 128 lamps](https://docs.blender.org/manual/en/latest/render/eevee/limitations.html#:~:text=are%20currently%20supported.-,Lights,supported%20at%20the%20same%20time.) in an Eevee scene (a single 12x12 grid of glowstone would blow through that limit; how would it work for a lake of lava?). Adding lamps should probably be its own function/operator, though it could always be added back into prep materials as a tick box, similar to animate textures.

**Comment by StandingPadAnimations** [comment]
I think in areas where there's 2 or more faces with the same material, an area lamp could be used. If there's a single block on it's own, then one lamp per block. I'll also look into removing light sources that don't contribute much(like if they're a certain distance or behind the camera) in the optimizer

**Comment by TheDuckCow** [comment]
Per comment mentioned issue above, it will be important that the simple material mode still includes the "add color overlay", since that will be critical to continue working with resource packs containing desaturated textures.
