### ISSUE TITLE
Blender 2.7 default material is broken for cycles.

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#272]
For some reason the dropdown for "simple" material is still showing up for blender 2.7, when it shouldn't since the principled node had different inputs or didn't exist (depending on the blender version). Logic needs to be added back in to ensure that the simple option doesn't even show up for blender 2.7

Blender internal continues to work fine as it used different branching logic.

**Comment by StandingPadAnimations** [comment]
I'm just doing a quick check over the code in the `prep.py` file. I think it may be related to this:
https://github.com/TheDuckCow/MCprep/blob/500a48d96cdc10f8d13172d6ac087a0cbfba2972/MCprep_addon/materials/prep.py#L107-L117

It seems that Blender will only check if the engine is Cycles or EEVEE, and not the version of Blender

**Comment by TheDuckCow** [comment]
Spot on - though I'm actually thinking it's still useful to show the other two PBR options instead, so might be that we need to set a conditional on the enum (make it a function that returns enum options based on blender version), but then also modify the operator execution code to error out if a bad selection is still inadvertently made (e.g. if called via a python script or something).

**Comment by TheDuckCow** [comment]
This has been resolved, but not released yet - will close issue when the patch is out.

**Comment by TheDuckCow** [comment]
Marking this closed with the imminent release.
