### ISSUE TITLE
How to change textures?

### ISSUE THREAD

**Issue by Timtaran** [TheDuckCow/MCprep#275]
![изображение](https://user-images.githubusercontent.com/60805088/149143788-cbb1bea0-f1d2-439d-be17-83ce5a0a844f.png)
![изображение](https://user-images.githubusercontent.com/60805088/149143890-217f4f09-dec2-4b80-a62a-c552a6e9a608.png)
![изображение](https://user-images.githubusercontent.com/60805088/149143949-35de369a-30c3-4ea5-94a2-a2939004589a.png)

**Comment by StandingPadAnimations** [comment]
Just swap the image out. 

I'll close this since this isn't really something to do with MCprep. If you need more help I would recommend joining the MCprep server: https://discord.gg/mb8hBUC

**Comment by Timtaran** [comment]
thx) sorry for spam in issues
