### ISSUE TITLE
Error Texture  again?...

### ISSUE THREAD

**Issue by SomethigSometing** [TheDuckCow/MCprep#277]
Ok so... 
Yesterday when i started working on a blender for the first time , a problem showed up.  I'm trying to solve it all day but I found no success to it.
I searched the internet and found on this page the same problem from another user under the name Ahmadqura and the problem was  solved. But I didn't figure out how to solve it. If anyone knows how to solve it pliz help!
I"m using blender v.2.78.a.

![image](https://user-images.githubusercontent.com/97842664/149667511-933a2ed9-9f51-4ca9-acc6-ab68c16a1b6c.png)

**Comment by StandingPadAnimations** [comment]
First off, I would recommend Blender 3.0 since it eliminates any other variables that could be causing this issue.

However, I assume you're using Mineways? Just export with the "export tiles to textures directory" enabled(it's on the bottom left hand corner of the export options)

**Comment by SomethigSometing** [comment]
I'm sorry but I couldn't understand when you said. I only have export ... like:
![image](https://user-images.githubusercontent.com/97842664/149675247-8a02e1d0-3e42-4352-95c3-62460d69ad53.png)
and also 
![image](https://user-images.githubusercontent.com/97842664/149675287-968c671a-094f-40d0-9ab3-9e9650ad262c.png)
And i also want to ask is there more programs for exporting other then mineways?

**Comment by StandingPadAnimations** [comment]
When I say export, I meant when you export your world from mineways

Also, there's a world exporter called jmc2obj which I would recommend over mineways

**Comment by SomethigSometing** [comment]
Ok. I figured out what you had in mind but still no success.
but I thought a bit and is it possible that this problem  have to do anything with all this ...
![image](https://user-images.githubusercontent.com/97842664/149676886-4839acb8-e2d5-445f-90f1-465cce9417c3.png)
this does show on my screen after i export the world but i go get the right file for 
further work.

**Comment by SomethigSometing** [comment]
Thank you for all your time StandingPadAnimations.
![image](https://user-images.githubusercontent.com/97842664/149678128-afb4dfc7-1ab6-4600-8a93-2264b5056240.png)
I managed to solve the problem.!
