### ISSUE TITLE
ValueError: register_class(...): problem with installing the add on

### ISSUE THREAD

**Issue by SkyDraco-8bit** [TheDuckCow/MCprep#278]
I am using mcprep for a while, but when it came to 3.0, i re installed mc prep, but i get this error whenever i press the "enable addon" button : 

![image](https://user-images.githubusercontent.com/80839516/150209053-0ac688bd-c881-4a43-bfe9-2ff7ea704cd0.png)

i tried removing and re installing the add on twice but it didnt worked
i am with the 3.3.0 of mcprep

**Comment by StandingPadAnimations** [comment]
MCprep 3.3.0 is too old. You have to update to the newest version for Blender 3.0 compatibility

**Comment by TheDuckCow** [comment]
Actually to clarify, *MCprep* version 3.30 is the latest, though yes you are encouraged to use blender 3.0 where possible, which I can see you are using from the screenshot.

Try just restarting blender first, or reinstalling MCprep, and see if that resolves the problem.

**Comment by StandingPadAnimations** [comment]
Thanks for the correction. I thought MCprep was on 3.6.0 for a second

**Comment by SkyDraco-8bit** [comment]
Ok, i aldready  deleted, re-installed the add-on and restarted blender without working but i just launched blender and it mysteriously fixed it himself, also anyway thanks for awsering so quickly, mc prep is extremely useful for my works, i was really worried of not having it working anymore, you are doing a great job !

**Comment by TheDuckCow** [comment]
Glad to hear it's working! Sometimes a good 'ol restart is all these things need. Glad to hear it's useful.
