### ISSUE TITLE
PrepMaterials function

### ISSUE THREAD

**Issue by Czutrix** [TheDuckCow/MCprep#279]
At first when Im importing jmc2obj world to blender all of textures are blurry image_1
But when Im clicking in Mcprep tools prep materials it looks like in image_2
What should I do ?
![image_1](https://user-images.githubusercontent.com/98060830/150416225-608dc3f0-f058-4eed-a929-74229eb11af7.png)
![image_2](https://user-images.githubusercontent.com/98060830/150416237-6968e7d6-6fa7-4d6b-8c5e-6e8b26cdf1e5.png)

**Comment by Czutrix** [comment]
I know that its obvious but image_1 is the upper one
and image_2 is at the bottom

**Comment by StandingPadAnimations** [comment]
Judging from the MCprep panel, you just need to update MCprep. Until recently, jmc2obj support for versions 113 and above wasn't in MCprep due to file path changes 113+ brought

**Comment by Czutrix** [comment]
Thanks It works
