### ISSUE TITLE
Where is the pose mode section

### ISSUE THREAD

**Issue by Czutrix** [TheDuckCow/MCprep#281]
Hi I wanted to make some animation but the pose mode is gone. Can someone explain ?
![Zrzut ekranu 2022-01-21 o 21 49 07](https://user-images.githubusercontent.com/98060830/150598497-3445be5c-8b54-4fae-8ebc-a4850da65358.png)

**Comment by TheDuckCow** [comment]
You need to select the armature first, the little figure looking item in the outliner. I see you have the world object active righ now. See [this tutorial](https://www.youtube.com/watch?v=0l--8XaOA4g&list=PL8X_CzUEVBfaa9PD9lWm4HdQCxUhl62Zb&index=9) for more info
