### ISSUE TITLE
How to use "Create MC Sky"

### ISSUE THREAD

**Issue by Zachadactyl** [TheDuckCow/MCprep#284]
So I have used static sky and dynamic sky + meshes, but it got really hard when I went to dynamic sky (what I want) and the sun was out of the viewport, render, and camera.  I found by setting view, sun could _kind of_ be blaced in desired location, but it was way too hard.  How to fix this and use It right?

**Comment by TheDuckCow** [comment]
Sorry for the delayed reply here! Can you share more specifics, potentially including screenshots, of what you are hoping to do and why you're not able to get there? Is it because you want to rotate the sun horizontally along the horizon?

**Comment by TheDuckCow** [comment]
Let me know if you can give any other specifics, thanks

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, but let me know if you have any more info or need help still.
