### ISSUE TITLE
Can't install MCPrep

### ISSUE THREAD

**Issue by SorcererAssassin** [TheDuckCow/MCprep#286]
First I had an issue with my exported world not showing up. I wanted to reinstall MCPrep, but I'm getting an error, trying to enable it.

- First Issue
![Schermafbeelding 2022-03-11 120645](https://user-images.githubusercontent.com/60132536/157950198-65704f41-6cc8-40f3-85a9-790f815123b5.png)

- Error
![Schermafbeelding 2022-03-11 205632](https://user-images.githubusercontent.com/60132536/157950042-c1135662-7453-45f8-952e-e0f0630f86b3.png)

**Comment by StandingPadAnimations** [comment]
What version of MCprep are you using? Have you tried uninstalling and manually installing the newest version? Also, when importing jmc2obj worlds, this is a normal issue. The easy solution is to press F3, and type, "Geometry to Origin".

**Comment by SorcererAssassin** [comment]
I use the latest version of MCPrep as well as Blender, recently installed.

**Comment by SorcererAssassin** [comment]
I got MCPrep to work again, but another issue occurred. I did the 'Geometry to Origin' but it made my world look like this
![Schermafbeelding 2022-03-12 140927](https://user-images.githubusercontent.com/60132536/158019206-a4d03b8a-e496-4695-8c38-7c9ee6ee0877.png)

**Comment by StandingPadAnimations** [comment]
I did notice that the obj was split by block. Perhaps that's the issue (MCprep doesn't split objs from jmc2obj, only Mineways)

**Comment by SorcererAssassin** [comment]
I did something wrong on my end. It's fixed completely. Thank you so much!

**Comment by StandingPadAnimations** [comment]
No problem
