### ISSUE TITLE
Add armor to the Player and Slim Player rig

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#293]
There have been **many** requests to add armor to the default Player rig in MCprep. While there have been other discussions about whether a new default rig should be used instead of this one, in the meantime this continues to be an issue people face. 

Armor could be supported in a few ways:
- Add objects for each set of armor types to the rig itself, hiding based on slider selection (driver driven).
- Add only one set of armor objects, and create a custom UV slider for the different colors. Ideally driver driven.
- Add only one set of armor objects, and create a function in MCprep swap out different armor images accordingly (possibly per resource pack too, although that quickly gets tricky since the model geometry won't line up properly).

This would not address issues about adding armor to other rigs. There is also the consequence of this making the Player rig even a little bit slower, since more geo and drivers slows things down, but not unreasonably so.

**Comment by th3pooka** [comment]
So i'm unsure how to specificly solve some of these problems, but here is my character armor switcher. This might help answer some things. [https://drive.google.com/file/d/1-dBmTF3IkFVfhQNRaBPoD4xBTnGqcv0K/view?usp=sharing](https://drive.google.com/file/d/1-dBmTF3IkFVfhQNRaBPoD4xBTnGqcv0K/view?usp=sharing)

**Comment by Snipercupcakes** [comment]
You should add a separate spawner tab in mcprep called armor spawner you need to select player armature and you spawn a type of armor on it. Because I have a lot of trouble doing UV and control-p stuff

**Comment by zNightlord** [comment]
> You should add a separate spawner tab in mcprep called armor spawner you need to select player armature and you spawn a type of armor on it. Because I have a lot of trouble doing UV and control-p stuff

Armor spawner tab is cool but it's not generally a good idea. Is it like spawning many user define armor models preset? You still have to do UV with that
Or is like just like option 3 just simple replace the texture with predefine UV? 
About the UV part it's like pooka example, switching possible minecraft armor and an additional socket for custom armor texture still follow the minecraft UV layout. 
But I rethink about it there should be an option for UV vector input just in case the user need to use another UVmap for that texture.

**Comment by Snipercupcakes** [comment]
Take a look at https://www.youtube.com/watch?v=nNGmucesYQM&t=0s their plugin has an armor inserter and it is very cool. I use that rig.

**Comment by zNightlord** [comment]
> Take a look at https://www.youtube.com/watch?v=nNGmucesYQM&t=0s their plugin has an armor inserter and it is very cool. I use that rig.
"Is it like spawning many user define armor models preset? You still have to do UV with that" 
I know. it's cool since I already saw some early prototype of it before. But I don't know about how others can use flexibility
because you has option to make custom 3d model, do the UV, weight paint and store the asset somewhere for the rig seperately and bring it in... expand and share their asset.

Although It does goes along with the existing spawning system. Option 1 and 2 can integrate well with this since they are just simply object with additional shader or maybe geometry nodegroup

**Comment by Snipercupcakes** [comment]
It spawns armor OBJs on your character, even if there is UV it will be automatically done for you.

**Comment by Snipercupcakes** [comment]
From the cycles rig

**Comment by zNightlord** [comment]
I forgot about Leather has dye hue and the overlay part too. Thinking 
Change a little bit about the node group thing. Now they are all node groups now with 3 sockets. 
[Player FancyFeet A2 v2.6.0 - TheDuckCow.zip](https://github.com/TheDuckCow/MCprep/files/9084705/Player.FancyFeet.A2.v2.6.0.-.TheDuckCow.zip)
https://streamable.com/kb5xds

**Comment by TheDuckCow** [comment]
This is the last task to finish up ahead of releasing 3.4. My current thoughts for this release is to avoid bloating the default player rig on its own, and provide these groups as their own importable assets. This may require some code to attempt to auto target it back to a rig already imported/selected.

Another approach more consistent with other rigs would be to build the switcher in natively, I can see if collection layers will work well for this or get in the way (that would be a no code solution, and require no special treatment).

**Comment by TheDuckCow** [comment]
Marking this as complete. Sorry @zNightlord that I ended up simplifying the setup a fair bit to make it work well with importing inside MCprep and work out of the box, was running into various oddities having the main meshes parented to different empties vs the main rig. We could always look at updating in a future version to be more seamless (or, as I've long been thinking, just update to an entirely different and improved rig that is good for general usage).

**Comment by zNightlord** [comment]
> Marking this as complete. Sorry @zNightlord that I ended up simplifying the setup a fair bit to make it work well with importing inside MCprep and work out of the box, was running into various oddities having the main meshes parented to different empties vs the main rig. We could always look at updating in a future version to be more seamless (or, as I've long been thinking, just update to an entirely different and improved rig that is good for general usage).

I'm looking forward to the simplified setup.
The empties is just use for grouping (_I don't know how to deal with groups in 2.7_) and have somewhere to put the driver temporary. All of that could be move somewhere or put inside the rig.

There is one more thing about the leather armor still a bit maybe confusing in the solid mode preview is extra overlay pad, I don't know is it better to duplicate geometry and offset that layer than put it as material.

**Comment by TheDuckCow** [comment]
I'm taking the approach of being ok it won't work well for 2.7x users in this case, it will fail to import as I don't want to deal with the process of re processing to bring into 2.7x (it's a process not unlike what you did to go from 3.0 to 2.9). Your ideal of moving things to the side would have worked well though, so I appreciate the thinking ahead.

If you are curious, here's the final file. The guidance is that users, while not ideal, simple change the viewport and render visibility for the sub collections themselves manually, since they are put into place. This meant we lost the custom properties you made (sorry about that) in favor of forcing users to use the viewport settings. We could create drivers for each and map that to an armor bone in the main arma to streamline it some, that could certainly be a fair update for another revision in the future.

[Player FancyFeet v2.6.0 armor - TheDuckCow zNightlord.blend.zip](https://github.com/TheDuckCow/MCprep/files/9248979/Player.FancyFeet.v2.6.0.armor.-.TheDuckCow.zNightlord.blend.zip)

**Comment by Typhoonyt** [comment]
What
