### ISSUE TITLE
I can't import texture packs

### ISSUE THREAD

**Issue by MortBlox** [TheDuckCow/MCprep#296]
Every time I import a texture pack it says "Detected scaled UV's (all in one texture), be sure to use Mineway's export tiles for textures". It only worked once, but that was the first time I imported the world

**Comment by TheDuckCow** [comment]
Sorry for the delayed reply. Be sure to use Mineway's "Export Individual Textures To..." feature. Otherwise, the UVs being "all in one image" won't work with changing texture packs, which are for individual files.
