### ISSUE TITLE
water shader

### ISSUE THREAD

**Issue by 5alidshammout** [TheDuckCow/MCprep#298]
I'm trying to make the water realistic like https://www.youtube.com/watch?v=X5r-VYZx__A
but how to do it, should I do that to water_still or water_flow?

**Comment by StandingPadAnimations** [comment]
Both

**Comment by TheDuckCow** [comment]
I would do it to water still, after having used the "animate textures" feature. Notice that video on blender is fairly old, using the Principled shader node would get you more realistic results these days, though you'd have to play with more settings. On May 13, 2022 1:47 AM, 5alidshammout ***@***.***> wrote:
I'm trying to make the water realistic like https://www.youtube.com/watch?v=X5r-VYZx__A
but how to do it, should I do that to water_still or water_flow?

**Comment by 5alidshammout** [comment]
does jmc2obj combine the water to one object?

**Comment by StandingPadAnimations** [comment]
It's still 2 materials. All materials are based on the textures

**Comment by StandingPadAnimations** [comment]
I would suggest joining this server for further assistance: https://discord.gg/tzu7bA56 

GitHub issues are primarily for MCprep related issues

**Comment by 5alidshammout** [comment]
ok, thanks anyway!
