### ISSUE TITLE
Tab Won't Open

### ISSUE THREAD

**Issue by SpaceSquidSS** [TheDuckCow/MCprep#3]
So I was able to do it great, worked well. When I went to render an animation, everything was pink. So I thought I would just do the prep materials thing. Then I realized the whole tab was GONE. I reset Blender, redownloaded the file, and a bunch of other stuff and couldn't get it to work. It might work if I made a new project, but I don't want to have to restart. HELP!!!

**Comment by TheDuckCow** [comment]
Hello @SpaceSquidSS, are you sure you re-enabled the addon after downloading/re-opening blender? If you restart blender it won't keep the same addons enabled unless you press "save user preferences" after pressing the tick box. As for pinkness, prep materials won't help that (most likely) as it sounds like your textures are simply missing. Make sure your imported world sits in the same position relative to its texture files from the time it was imported.
