### ISSUE TITLE
Mob spawner mesh and material colors intertwining to make a new issue

### ISSUE THREAD

**Issue by aguywithoutultrainstinct** [TheDuckCow/MCprep#300]
while this issue may have been discussed before, i would like to address it again as i do not know either way. so lets get to business, as as i was working with the mcprep mob spawner i took a look at the iron golem, and the eyes and eye socket as well as the unibrow were completely white in the materials preview shader while the solid viewport shade had the base color applied correctly,and the same applies to all others that have the same issue(like the vindicator, and piglin as well as others) i will attach 2 files of both viewport editors to show you the issue and hope that this gets fixed, good day to you
![Screenshot (441)](https://user-images.githubusercontent.com/105763881/168947753-776541b5-d86f-46ff-93a5-15aaa3bc77c4.png)
![Screenshot (442)](https://user-images.githubusercontent.com/105763881/168947755-dcaf5239-770e-4cb8-9d55-82e13db8e038.png)
![Screenshot (443)](https://user-images.githubusercontent.com/105763881/168947756-328ee068-6731-4f60-af00-21e9f75f275a.png)
![Screenshot (444)](https://user-images.githubusercontent.com/105763881/168947757-45837570-a9e0-4ea1-9bc1-b384fce20016.png)
![Screenshot (445)](https://user-images.githubusercontent.com/105763881/168947759-783a2e52-8e46-46a7-80a1-ed6858f4f6f0.png)
![Screenshot (446)](https://user-images.githubusercontent.com/105763881/168947763-14740751-3180-4525-b114-b1e054624d74.png)

**Comment by aguywithoutultrainstinct** [comment]
guess im fixing it myself

**Comment by StandingPadAnimations** [comment]
Sorry for not seeing this before, this is mostly a BSS issue (since MCprep uses the BSS pack for most rigs)

I think the eye and unibrow materials don't have color. Solid view doesn't use materials for color but instead textures (or I guess someone manually colored it in solid view). 

Your best bet is to just make edit the materials with the colors you need

**Comment by aguywithoutultrainstinct** [comment]
just as i thought, dont blame em but the color select tool should fix that right up. thanks man

**Comment by StandingPadAnimations** [comment]
No problem. If more help if needed, you can join the MCprep server: https://discord.gg/q6C5aaBv
