### ISSUE TITLE
Won't let me enable addon in blender

### ISSUE THREAD

**Issue by Derpeh** [TheDuckCow/MCprep#302]
As you can see, it won't let me click the check mark on the addon.
![Blender Preferences 5_27_2022 10_43_20 PM](https://user-images.githubusercontent.com/106416903/170806760-cca4e212-0630-4d28-b445-98f9ad79021c.png)

**Comment by StandingPadAnimations** [comment]
Have you tried reinstalling MCprep by installing the zip file? Also I would recommend trying Blender 3.1 as it's the latest release and might help

**Comment by StandingPadAnimations** [comment]
Closing issue. Reopen if you need further help. Alternatively, you can ask for help on the MCprep server: https://discord.gg/q6C5aaBv
