### ISSUE TITLE
I have problem on site

### ISSUE THREAD

**Issue by Tkmboy** [TheDuckCow/MCprep#304]
on website downloading server not opens please fix it

**Comment by StandingPadAnimations** [comment]
Downloading works for me, so it may be an internet issue

If you can't download from the website, you can still download the addon here on Github: https://github.com/TheDuckCow/MCprep/releases/tag/3.3.1

**Comment by Tkmboy** [comment]
than you


ср, 8 Июн 2022, 22:49 StandingPad ***@***.***>:
