### ISSUE TITLE
Adding title screen camera setup

### ISSUE THREAD

**Issue by Tiefseetauchner** [TheDuckCow/MCprep#309]
I made a little script that creates Cameras to render the title panorama, and I had the idea of implementing it in MCprep, but I didn't wanna spend too much time implementing it and learning real addon dev and then have you guys say you don't want it, so I made it a [basic gist](https://gist.github.com/Tiefseetauchner/384d9b2a04ffec15e461e96bbc6bf956) (with usage instructions)

The idea is, you spawn in 6 cameras in the right orientation, make the render res square, render them, and they should line up

I feel like adding it in here might fit, but again, idk if you want that functionality, and I don't know where you'd want to implement it. Tho I'm happy to implement it, I have nothing to do atm. I'd personally put it in the Shift+A menu somewhere, but again, idk

*Fingerguns*

**Comment by StandingPadAnimations** [comment]
Looks pretty useful for resource pack developers, and the code seems to be mostly complete. @TheDuckCow Would it be possible to squeeze this in the next update?

**Comment by TheDuckCow** [comment]
Thanks for sharing this! I was going back and forth thinking, hmm, it's very niche and how will people discover this... Any code added to MCprep needs to have corresponding tests created, and continually maintained. 

That being said, it's < 100 lines of code and is not complex! The main question I'm looking for brainstorming help on is, where do we add this feature? Maybe another button under world tools? Or another advanced featured hidden under the World Imports panel (e.g. under Animate Textures or Combine Textures)?

Then to make it an end-to-end feature, probably would want to have a filebrowser popup where you can select the output folder.

----
ps love your subtle promotion in the default description, I'll make a point to keep that if it stays in its current form ;)

pps hmmm maybe in the farther future, I start releasing custom MCprep panorama textures along with the version artwork of https://bit.ly/MCprepSplash... that could be a fun way to use the feature and help continually test it.

**Comment by TheDuckCow** [comment]
> I'd personally put it in the Shift+A menu somewhere, but again, idk

I'm actually thinking of something more where it just uses the current position of the active camera, spawns in all the cameras, renders out the stuff, and then cleans up after itself (so the pano cameras don't remain after). This way it's truly an end to end experience, just pick your folder output and let it run. So aside from where the user clicks the button to start this custom render (maybe even from the render window??), does this user flow make sense? Would you use it like that?

**Comment by Tiefseetauchner** [comment]
> Maybe another button under world tools? 

That was actually my first idea, but it kinda feels odd and might confuse people

> I'm actually thinking of something more where it just uses the current position of the active camera, spawns in all the cameras, renders out the stuff, and then cleans up after itself (so the pano cameras don't remain after). This way it's truly an end to end experience, just pick your folder output and let it run. So aside from where the user clicks the button to start this custom render (maybe even from the render window??), does this user flow make sense? Would you use it like that?

I would, and that was my first idea of how to implement the feature, but it ended up more complicated than I bargained for implementing myself. 

I really like the idea with the active camera, that would give people a good sense of where their pano would be created

There has to be an input field where you enter your resolution, and it'd have to be obvious that it's a square image. I can already see issues à la "Why can't I render this in a custom 25:51 resolution?" (I know from experience that people don't reed their popups)

We'd have to save the current render resolution, change it to the square one, render the cameras and change it back

Another thing that'd have to happen is checking for cameras named "panorama_0-5". Tho if we do render it instantly, we would have the cameras as a variable, so the name doesn't actually matter in a single-step system. Just something to consider if we let the user create and render in two seperate steps

**Comment by TheDuckCow** [comment]
Great then I think we are aligned! Indeed, we need to cache a number of values ahead of time, also including which initially active camera. In terms of resolution, what if we just infer that from the current render resolution width? By default though, that would mean images are 1920x1920 which is perhaps excessive. Otherwise yes, we could make it a popup to just select the resolution (which defaults to 1024 px square, or whatever you think a good default would be).

If we render instantly we don't need to worry about camera names, though it could be start and auto clean up old cameras in case e.g. blender crashed in the middle. I think I prefer that over creating and rending separately.

**Comment by TheDuckCow** [comment]
Meant to ask this - is this something you have an interest in getting guidance to contribute directly as addon code, or would you prefer one of us (myself or Standingpad)? I'm fine either way, I figure I would ask.

**Comment by Tiefseetauchner** [comment]
I'll gladly try and implement it myself, I did do something similliar in function before, and I'll see how far I get copying other parts of MCprep for the addon parts, and I'll take this convo as a reference for how to implement what. Any tips about what to keep in mind that is MCprep specific would be appreciated tho

I'll start with just resolution and folder selection, and make a PR based on that, and we'll see from there

**Comment by TheDuckCow** [comment]
Great! A few points to give some direction:

- I'd say the bulk if not entirety of your code can exist inside the `world_tools.py` file
- Be sure to check out the [contributor guide here](https://github.com/TheDuckCow/MCprep/blob/master/CONTRIBUTING.md); let me know if you run into any issues using the compile scripts (big time saver imo)
- Feel free to get start and ask for mid-way feedback before you're done, if you want to validate direction or are unsure of anything.

From a structural point, I would do something like so:

- Make one class for the operator (as one always does)
- Make the execute function pretty small, and just have it call out to other functions defined as part of the same operator class
- I'd imagine functions for: create cameras, render cameras, and cleanup cameras.
- You are probably going to run into some funniness with the rendering step. I have good experience in this area, so I can share more details once you get there. For now, you could make the "render cameras" step just be a pass through (and not actually do anything).
    - If you want to get a head start on the rendering setup, you could see how I [approached it here](https://github.com/TheDuckCow/blender-community-render/blob/main/community_render.py#L1537) (where it gets registered [here](https://github.com/TheDuckCow/blender-community-render/blob/main/community_render.py#L2411) and how it ultimately triggers rendering [here](https://github.com/TheDuckCow/blender-community-render/blob/eede9c26ec226ab6094bc24c7620a315df0134f9/community_render.py#L1335)); a key point is to ensure users can still press "esc" to cancel the render. 
    - The main tactic is before starting a render, you need to add a "render finish" callback function which then controls whether another render starts or the operation finishes up.


Let me know if you have any questions, I suggest making it in a few steps with a few commits at a time!

**Comment by TheDuckCow** [comment]
Hey so sorry for the silence from my end @Tiefseetauchner, it's been a busy time moving. To be up front it may be another week before I can get back to looking at this in detail, but at that point I'll do some deep testing and come up with more explicit recommendations on how to address the rendering part.

**Comment by TheDuckCow** [comment]
Officially merged!
