### ISSUE TITLE
Not closing the file explorer window if the user accidently clicks an MTL file

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#313]
Often times I will accidently click the MTL file instead of the OBJ, which throw an error but also closes the file explorer window. It would be more convenient and less annoying to throw the error in the file explorer window itself and allow the user to select the correct file

**Comment by TheDuckCow** [comment]
I like the idea of improving the experience if someone barely miss-clicks the MTL file. What if we did a better detection of whether the same-named OBJ file exists, and use that instead? But then still pop up the error if it can't be found. If we always re-open the file browser, I think the user would miss the pop-up error and think there was something wrong with MCprep.On Jul 2, 2022 3:27 PM, StandingPad ***@***.***> wrote:
Often times I will accidently click the MTL file instead of the OBJ, which throw an error but also closes the file explorer window. It would be more convenient and less annoying to throw the error in the file explorer window itself and allow the user to select the correct file

**Comment by StandingPadAnimations** [comment]
I think if the corresponding OBJ file doesn't exist at all, then it's safe to close the window as both files need to have the same name

**Comment by StandingPadAnimations** [comment]
Adding on top of this, I think MCprep should also fix the origin for jmc2obj OBJs. Right now users have to set the geometry to the origin.

Either that or we could open an issue on the jmc2obj GitHub (since this seems to be an exporter thing)

**Comment by TheDuckCow** [comment]
Setting the improvement of misclicking mtl for v3.4.1

As for recentering, what's the specific issue? The object being centered in the world if the export setting "centered" is used, or where it puts the origin within a properly world-centered object? I wonder if it has to do with the new height change where values can go negative.

**Comment by StandingPadAnimations** [comment]
With jmc2obj worlds, the actual world tends to be extremely far away from the origin. While the fix is easy (F3 > geometry to origin), it's a bit annoying to have to do that for each time a world is imported

**Comment by StandingPadAnimations** [comment]
This has been implemented in #334. As for OBJ centering, jmc2obj can do that in export settings (although I'm not sure why it's not default)

**Comment by TheDuckCow** [comment]
Hey @StandingPadAnimations any chance you could cherrypick your commit which fixes this allowing of MTL selection to auto correct to the obj? If not, I'll make the quick change.

Ideally, no other changes are brought in via this cherry pick change. Looking to do this by the end of this week.

**Comment by StandingPadAnimations** [comment]
I think I'll reimplement it since it's simple enough (just replaces the file extension)

**Comment by TheDuckCow** [comment]
Just a followup ping, planning to release an MCprep update hopefully in a couple days, this would be a nice-to-have improvement in (otherwise, can do in the following release after)

**Comment by StandingPadAnimations** [comment]
Whoops, forgot about this. I'll get the changes done by either tomorrow or tuesday (I'm out of town right now but today's the day I come back)

**Comment by TheDuckCow** [comment]
Great - I have a tutorial that's uploaded and ready to release on Effects that I want to go out after 3.4.2 does; even though this doesn't relate to the effects spawner, still a good thing to bring in!

**Comment by StandingPadAnimations** [comment]
I'll put this under #372 since it already deals with OBJs anyway

**Comment by StandingPadAnimations** [comment]
Done
