### ISSUE TITLE
Mixamo

### ISSUE THREAD

**Issue by KBCats** [TheDuckCow/MCprep#320]
I need to use mixamo animations for a new project and cannot figure out how to use it, when I tried before all methods I could find on the internet, either a tutorial or fix would be insanely appreciated

**Comment by zNightlord** [comment]
I have some interest in this recently. This may help with the task of having shareable animation library. https://github.com/TheDuckCow/MCprep/issues/164
This depends on your already existing rig so there are two ways to achieve this.

1) Use Mixamo bone rig structure. 
I know Mixamo has an addon that help building the control rig from the import skeleton. You still need to fix some problems like weigh, the rig controls dont have certain thing that a minecraft rig should have or shouldn't have.

Resulting you throw your existing work (existing rig or tool made specially for the rig) into the bin. 

2) Retargeting workflow.
Use your existing rig and match the minecraft rig structure to the rig that has animation and bake the animation.

Result still using the your rig, existing tools.

They both still need to do animation cleanup, especially for the look of minecraft character.

If you ask me, I choose the second method since I have more control what to extend to the rig system I currently have.

**Comment by KBCats** [comment]
> 

Are there tutorials for this im still working my way around blender

**Comment by KBCats** [comment]
> I have some interest in this recently. This may help with the task of having shareable animation library. #164 This depends on your already existing rig so there are two ways to achieve this.
> 
>     1. Use Mixamo bone rig structure.
>        I know Mixamo has an addon that help building the control rig from the import skeleton. You still need to fix some problems like weigh, the rig controls dont have certain thing that a minecraft rig should have or shouldn't have.
> 
> 
> Resulting you throw your existing work (existing rig or tool made specially for the rig) into the bin.
> 
>     2. Retargeting workflow.
>        Use your existing rig and match the minecraft rig structure to the rig that has animation and bake the animation.
> 
> 
> Result still using the your rig, existing tools.
> 
> They both still need to do animation cleanup, especially for the look of minecraft character.
> 
> If you ask me, I choose the second method since I have more control what to extend to the rig system I currently have.

DO you have any tutorials on this? im still working my way around blender

**Comment by KBCats** [comment]
> I have some interest in this recently. This may help with the task of having shareable animation library. #164 This depends on your already existing rig so there are two ways to achieve this.
> 
>     1. Use Mixamo bone rig structure.
>        I know Mixamo has an addon that help building the control rig from the import skeleton. You still need to fix some problems like weigh, the rig controls dont have certain thing that a minecraft rig should have or shouldn't have.
> 
> 
> Resulting you throw your existing work (existing rig or tool made specially for the rig) into the bin.
> 
>     2. Retargeting workflow.
>        Use your existing rig and match the minecraft rig structure to the rig that has animation and bake the animation.
> 
> 
> Result still using the your rig, existing tools.
> 
> They both still need to do animation cleanup, especially for the look of minecraft character.
> 
> If you ask me, I choose the second method since I have more control what to extend to the rig system I currently have.

Do you have any tutorials on this? im still working my way around blender

**Comment by zNightlord** [comment]
Yes there are many tutorials covered about this topic, you just need a little search. 
This is not for Minecraft specific so you need to change out certain things like I mention above there are 2 route that you can choose and why for it. 
If you have an existed that you prefer using choose 2, my assumption is you don't so 1.

I'm not sure about going into details here but you can find more support in the MCPrep discord server.

**Comment by KBCats** [comment]
> Yes there are many tutorials covered about this topic, you just need a little search. This is not for Minecraft specific so you need to change out certain things like I mention above there are 2 route that you can choose and why for it. If you have an existed that you prefer using choose 2, my assumption is you don't so 1.
> 
> I'm not sure about going into details here but you can find more support in the MCPrep discord server.

Are their any specific tutorials you’d recommend?

**Comment by zNightlord** [comment]
> Are their any specific tutorials you’d recommend?

CGDive, they have a playlist covered about Mixamo.

**Comment by KBCats** [comment]
> > Are their any specific tutorials you’d recommend?
> 
> CGDive, they have a playlist covered about Mixamo.

alright i’ll work on it tmr it’s 2am

**Comment by TheDuckCow** [comment]
Closing this issue as it's more of a 3D animation concept thing than an MCprep-specific issue - but feel free to keep communicating here if that's helpful!
