### ISSUE TITLE
Spawning a grass block results in many sides being translucent.

### ISSUE THREAD

**Issue by lizardpeter** [TheDuckCow/MCprep#321]
![grass_issue](https://user-images.githubusercontent.com/53446060/181317563-b26ea00d-c01b-4872-ae9b-bafee79b9194.png)

I could be doing something incorrectly, but when spawning in the grass block and some other blocks, there are weird transparency issues. I am using Blender 3.2 and Cycles.

**Comment by StandingPadAnimations** [comment]
Are you using a GPU and if so what type (Nvidia or AMD) and have you updated your drivers?

**Comment by lizardpeter** [comment]
> Are you using a GPU and if so what type (Nvidia or AMD) and have you updated your drivers?

I've tried on both an NVIDIA RTX 2080 Ti and NVIDIA GTX 1080. They both are on the latest driver. My other Blender renders seem to be fine. This is a strange issue!

**Comment by StandingPadAnimations** [comment]
What version of MCprep are you using?

**Comment by lizardpeter** [comment]
> What version of MCprep are you using?

3.3.1

**Comment by StandingPadAnimations** [comment]
Can you show the material of the grass block itself as well as some of the steps you did that caused the issue?

**Comment by StandingPadAnimations** [comment]
Ahh. It may be related to #267

**Comment by StandingPadAnimations** [comment]
Closing this for now. If you still have issues, just reopen the issue
