### ISSUE TITLE
Issue template for future reports and motivation behind it

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#322]
# Template (if you just need the template to post an issue)
```
Issue: ... 
Steps to reproduce:
1. ...
2. ...
3. etc.

MCprep version: ...
Blender version: ...
Hardware (this only applies if you're using a GPU for now): ...

Screenshots (if applicable): ...
```

# Explanation for template:
Short answer: It gives the most information for debugging

Long answer: Before this, a lot of times we've had bug reports submitted that often contained too little information. While many contain at least a screenshot (btw, thank you to those who submitted a screenshot for any issues you've posted, they help a lot), quite a bit just say what the issue is.

The thing is, we MCprep developers need some basic info, including:
* Blender version: some versions of Blender are just really annoying to deal with, or aren't supported by MCprep
* MCprep version: older versions of MCprep can contain bugs that have been fixed in newer releases. 
* Hardware: in my experience, some GPUs (mainly AMD) tend to receive driver updates that mess up some stuff. We need to know if this is specifically a GPU driver issue (which can be determined by setting the render device to CPU temporarily and seeing if the issue resolves itself)
* Steps to reproduce: this is by far the most important (along with screenshots). If the reported issue does indeed turn out to be a bug, we need to know how to reproduce the bug so fixing it becomes less of a pain
* Screenshots: we need visuals. Just like all of you, we're human, and we can't tell just based on a short description what the issue is

# Motivation 
While this may be more tedious to write, this actually makes the experience better for both us and the bug reporter. For us, we have more info to use while troubleshooting and debugging. For the reporter, we don't have to ask them as many questions 

# Faq
Q: What happens if I don't use the template above?
A: For the most part, the troubleshooting process will be more painful to deal with. It's just easier to use the template. That being said, for now, we will continue to accept those issues, but we'll refer to this page and won't start the process until the reporter updates their issue with the necessary info

Q: What if I don't remember how I caused the issue?
A: Your best bet is to drop the blend file on the report and we'll take a look at it in our own time. It may take longer though

Q: How do I check my MCprep/Blender version?
A: The Blender version should be on the bottom right-hand corner as of 2.8+. The MCprep version is in preferences on the MCprep module itself

Q: What if I use a fork of Blender like Bforartists or experimental builds?
A: Most forks should list the version they use as a base either on their website/documentation or in the actual software itself. If you're using an experimental build, support may be limited. 

Q: Can I try fixing the bug myself in the meantime?
A: By all means go ahead. MCprep is open source for this reason. Refer to [the contributor guide](https://github.com/TheDuckCow/MCprep/blob/dev/CONTRIBUTING.md) for more details

Q: Is there a Discord server for MCprep?
A: Yes, [here's the link](https://discord.gg/mb8hBUC)

**Comment by TheDuckCow** [comment]
I like this idea - maybe we should use the more official features of GitHub to increase the chance of people using this?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by StandingPadAnimations** [comment]
Sure thing, I'll also link this issue for an explanation on the template

**Comment by StandingPadAnimations** [comment]
Actually I just saw this new beta feature for public repos: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

This will definitely be easier for people to use

**Comment by StandingPadAnimations** [comment]
I have since added the template and removed the original from this issue
