### ISSUE TITLE
Tnt Smoke Doesnt have a texture (pink)

### ISSUE THREAD

**Issue by Banana-Blu** [TheDuckCow/MCprep#326]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I downloaded mcprep 3.4.0, and tried it. I spawned a tnt and discovered that the smoke has no texture

### What steps are needed to produce the bug?

Open the weather/particle spawner tab, and spawn a tnt

### What version of MCprep are you using?

Mcprep 3.4.0

### What version of Blender are you using?

Blender 3.2

**Comment by StandingPadAnimations** [comment]
This seems to be a common issue. Try to uninstall and reinstall MCprep and see how that works

**Comment by TheDuckCow** [comment]
Is the issue just that the smoke is gray, or showing as pink? It should have been generated by the Image Seqeunce effect actually, but there's a chance it's lost connection.

**Comment by Banana-Blu** [comment]
> 

It is pink

**Comment by TheDuckCow** [comment]
Thanks for clarifying - will make a point to update the QA script to auto detect this before future releases.

In the meantime, you could try selecting the individual smoke particles and running prep mateirals with "replace missing" enabled, might work for you. (Using prep materials on the overall collection will reset the animated material, the flickering white)

**Comment by TheDuckCow** [comment]
Should be resolved in the upcoming release, will re-open if this appears to not be the case.
