### ISSUE TITLE
The Particles Are Blurry or Have a Blurry background

### ISSUE THREAD

**Issue by Banana-Blu** [TheDuckCow/MCprep#328]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I spawn a particle (example: sonic boom) it has a blurry thing in background, and when the particle isnt animated its blurry and it becomes defined in random frames

### What steps are needed to produce the bug?

Go to the particles tab and spawn a random particle

### What version of MCprep are you using?

3.4.0

### What version of Blender are you using?

3.2

**Comment by TheDuckCow** [comment]
The blurry thing in the background is just an empty preview texture, used to help you understand what texture a given empty relates to. You can disable it right after spawning an effect (and it will stay that way for the remainder of the session).


<img width="330" alt="Screen Shot 2022-08-04 at 12 18 41 PM" src="https://user-images.githubusercontent.com/2958461/182935229-d226877e-0843-47dc-8734-4033c1e33b2d.png">

**Comment by Banana-Blu** [comment]
> The blurry thing in the background is just an empty preview texture, used to help you understand what texture a given empty relates to. You can disable it right after spawning an effect (and it will stay that way for the remainder of the session).
> 
> <img alt="Screen Shot 2022-08-04 at 12 18 41 PM" width="330" src="https://user-images.githubusercontent.com/2958461/182935229-d226877e-0843-47dc-8734-4033c1e33b2d.png">

Thanks for the info!

**Comment by StandingPadAnimations** [comment]
Closing as it seems like the issue has been resolved
