### ISSUE TITLE
Glowing furnace textures

### ISSUE THREAD

**Issue by gildas64** [TheDuckCow/MCprep#335]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

furnace textures appear to be glowing even if the furnaces are not active
![image](https://user-images.githubusercontent.com/67906219/185743754-161e2f83-282c-4909-b011-f7f97c11c09f.png)
![image](https://user-images.githubusercontent.com/67906219/185743774-d7fff769-8e83-4dc9-a15e-85a6292b12d3.png)

### What steps are needed to produce the bug?

open up a world containing any types of furnace (smoker, blast furnace, normal furnace) and then prep materials

### What version of MCprep are you using?

MCprep 3.4.1

### What version of Blender are you using?

Blender 3.4.0 Alpha

**Comment by StandingPadAnimations** [comment]
Does the issue also occur in Blender 3.2 or Blender 3.3 (which has just entered beta)? Since this 3.4 is in alpha right now, I assume this is a Blender 3.4 thing.

Have you also tried prepping materials with the simple option (which only does the bare minimum needed)? I've seen a similar issue with planks, but that might be related to the texture pack I'm using.

**Comment by gildas64** [comment]
> Does the issue also occur in Blender 3.2 or Blender 3.3 (which has just entered beta)? Since this 3.4 is in alpha right now, I assume this is a Blender 3.4 thing.
> 
> Have you also tried prepping materials with the simple option (which only does the bare minimum needed)? I've seen a similar issue with planks, but that might be related to the texture pack I'm using.

yep this also happened on previous version too and also i don't know about the prepping materials with the simple option and i did not use any texture packs since it also caused some problems for me

**Comment by gildas64** [comment]
update: i just tried exporting the world using jmc2obj and it fixed the problem?

the furnaces doesn't glow anymore and not only that it fixed some problems too such as untextured banners

so i think it's safe to say it's just the mineways exporter that's causing the problem here

**Comment by StandingPadAnimations** [comment]
> update: i just tried exporting the world using jmc2obj and it fixed the problem?
> 
> the furnaces doesn't glow anymore and not only that it fixed some problems too such as untextured banners
> 
> so i think it's safe to say it's just the mineways exporter that's causing the problem here

Yeah, Mineways is not a good exporter; it tends to cause more issues than necessary.
