### ISSUE TITLE
Faces at the edges of upside down stairs not being generated

### ISSUE THREAD

**Issue by ThePoptartCrpr** [TheDuckCow/MCprep#34]
I recently noticed that when a block is beside an upside down stair, its face adjacent to the side of the stair is not generated, like so at the bottom of this image:

![2](https://cloud.githubusercontent.com/assets/25708063/26703024/84e30a86-46dc-11e7-8537-00d5dc963e1e.png)

It is simply blank. The face is not generated.

(I'm not exactly sure if this is an MCprep or a Mineways issue, however I felt that it was more likely an MCprep issue so I posted it here. If this is a Mineways issue instead, please let me know and I'll report to them instead.)

**Comment by TheDuckCow** [comment]
Hello, this actually would be a Mineways issue as it's to do with how they export the meshes, MCprep doesn't create geometry, only improves materials or swaps existing geometry with 3D custom models. I would reach out to them, as I note I recall this is something I experienced with Mineways at some point as well (though for ladders and the block behind). 

Feel free to also try jmc2obj to see if you get better results.

**Comment by ThePoptartCrpr** [comment]
All right, thanks!
