### ISSUE TITLE
Better BFA Compatibility 

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#340]
While most of MCprep's functions work fine in BFA, some don't due to BFA using the master branch of Blender and not the Release branch. This issue will keep track of issues in BFA that need to be resolved in some way or another.

As of September 15th 2022, this includes:
* Setting volume homogeneous 
* Improper PBR setup, including random materials becoming emissive*
* Remove useless nodes**
* Remove emissive nodes**

*This may be an MCprep issue itself and would need to be tested on the Release branch
**Features not yet in MCprep master, but has worked previously during testing

**Comment by StandingPadAnimations** [comment]
Since I'm on the BFA development team and use BFA as my daily driver, I'll be able to check and fix issues MCprep has with it. This will allow MCprep developers and contributors to not have to install BFA just for testing (although it would be preferable)

**Comment by TheDuckCow** [comment]
I've gone ahead and labeled this `enhancement` since it would be a potentially new build compatibility. As always, so long as this does not complicate or reduce functionality for primary blender build users, I'm all for increasing compatibility.

**Comment by StandingPadAnimations** [comment]
Closing this Bforartists (BFA) support would be more difficult now (Bforartists bases their releases off of the Blender alphas, which now have massive API differences). In addition, they've (or to be more accurate, the lead maintainer) also shown extreme hostility towards Linux, due to which I've left Bforartists development
