### ISSUE TITLE
Snow and rain particle objects disappear after reload

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#343]
This is a known issue, ironically first uncovered by the [winning submission](https://theduckcow.com/2022/winner-mcprep-version-artwork-contest/) of the MCprep version artwork contest. The mesh objects for the rain and snow particles after spawning particle weather is not marked as a fake user nor added to scene, thus after restarting or reopening the blend file, the objects are lost. Really, blender should be better about knowing the objects are used in particle systems and not think they are unused, but alas here we are.

Affects v3.4.1 and v3.4.0

The solution can be one of a couple approaches:
- Automatically mark any objects referenced in just-imported particle systems as fake-users (so the objects are not removed)
- Add the objects into the scene, but to a disabled collection (like other aspects of MCprep does). This would also make it easier to  edit the particle, and even better, potentially avoid creating new meshes for each particle import (not that this would happen often or that the mesh is dense to necessitate it).

**Comment by TheDuckCow** [comment]
For anyone seeking an immediate workaround, see how to mark the particle as a Fake User:


https://user-images.githubusercontent.com/2958461/200186524-c4d18f2b-84a3-41fd-88a3-e927fbd7f30d.mp4

**Comment by TheDuckCow** [comment]
To be honest, I'm not sure I'm totally following what the force reload script is fixing for.

In this case though, really the thing that needs to happen is marking the object as a fake user and/or adding it to the scene so it's not garbage collected, any other solution would probably solving a symptom versus the cause. Should be a simple enough fix, just need to get to it.

**Comment by StandingPadAnimations** [comment]
> To be honest, I'm not sure I'm totally following what the force reload script is fixing for.

In files where assets have been loaded in, it's not possible to reload assets, hence force reloading

**Comment by TheDuckCow** [comment]
Marking this as closed as assigning fake user is working. It is true it won't fix existing files that were saved before, but it's a one-time fix for users to reload, and there would be a ton more code (which could itself have bugs) in trying to automatically re-connect a particle object to an empty particle system.
