### ISSUE TITLE
Problem wit emission

### ISSUE THREAD

**Issue by Czutrix** [TheDuckCow/MCprep#354]
I wanted to create a glowing lapis ore for my render but when I spawned this block from mcprep addon and then went ito shading tab when tried to edit whole block I just edited bottom part of the block.
![Uploading Zrzut ekranu 2022-11-1 o 22.02.44.png…]()

**Comment by TheDuckCow** [comment]
Did you mean to close this issue @Czutrix or are you still having trouble? Please re-open if so, thanks!

**Comment by Czutrix** [comment]
no

**Comment by TheDuckCow** [comment]
You might need to re-upload your screenshot since it's not showing up for me. But generally, I think would just need to ensure all faces of the block are using the same material, and then just edit that one material directly in the shader editor. You may need "assign faces" to all be the same lapis block material.

**Comment by Czutrix** [comment]
@TheDuckCow I'm reuploading the screenshot for you but I think I will also post a video with more details
![Zrzut ekranu 2022-11-1 o 22 02 44](https://user-images.githubusercontent.com/98060830/199573271-cd3ddc41-e6cc-4ed8-a1c7-ef637f4afaa0.png)

**Comment by TheDuckCow** [comment]
I'm going to close this as this is more of a blender usability topic. IN terms of what you are doing, I highly suggest you actually load this block into a scene to see how it reacts to everything else, and also make sure you are using Cycles (if you want the emission to have an effect on anything more than just the direct camera look; eevee won't by default be able to light other objects nearby).

**Comment by StandingPadAnimations** [comment]
On the topic of mesh lighting: mesh lights create a lot of noise in Cycles, so it's advisable to just use lamps.

Hopefully in a future version of MCprep we'll be able to implement a feature where users will be able to add lights to whatever material they want, but that's not a priority for now
