### ISSUE TITLE
Reload Effects Missing in the UI

### ISSUE THREAD

**Issue by Lev02** [TheDuckCow/MCprep#355]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I have a blender project where MCPrep 3.2 was installed. I upgraded to MCPrep 3.4.1 and I still can't spawn a weather (rain, snow, etc.). However if I open a new blender file I can do it. I tried:

1). Reloading assets but there is no such button for "Effects + weather" spawner. 
2). Reinstalling MCPrep.
3). Restarting blender.

![image](https://user-images.githubusercontent.com/50963313/201070995-cea09ef5-ea30-4631-932e-d3341f8b0833.png)

How can i get weather in my spawner?

### What steps are needed to produce the bug?

1). Old project with MCPrep 3.2 or lower
2.) Install MCPrep 3.4.1 to the project

### What version of MCprep are you using?

MCPrep 3.4.1

### What version of Blender are you using?

Blender 3.3.1

**Comment by Lev02** [comment]
Fixed it by typing 

`bpy.ops.mcprep.reload_effects()`

in "Scripting" tab.

![image](https://user-images.githubusercontent.com/50963313/201092122-6717decf-14d8-4ddb-8b0a-38b6138af3f0.png)

It would be nice if "Reload effects" button was added to the UI.

**Comment by StandingPadAnimations** [comment]
Huh, if reload effects isn't in the UI, then that's a bug.

**Comment by Lev02** [comment]
> Huh, if reload effects isn't in the UI, then that's a bug.

![image](https://user-images.githubusercontent.com/50963313/201345132-164a3ac3-77ea-49ff-ab19-dfdfd36537e6.png)

**Comment by StandingPadAnimations** [comment]
Closing this as this is already fixed on the dev branch
