### ISSUE TITLE
Possibility to put a custom resouce pack?

### ISSUE THREAD

**Issue by SharkblackFr** [TheDuckCow/MCprep#356]
### Name of asset submission

Hello,
I would like to know if it is possible to load a custom resource pack of version 1.18 that adds blocks.
Like the resource pack generated with itemadder

### Quality checks

- [X] I have used only vanilla textures (or created images that are derived from vanilla textures)
- [X] This is a vanilla minecraft asset/mob/effect
- [X] I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
- [X] If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
- [X] I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.

### Confirmation

- [X] By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.

**Comment by StandingPadAnimations** [comment]
I think you used the Asset Submission format for a feature request lol

Anyway, by "adding blocks", did you mean custom blocks that don't exist except with mods or something else?

**Comment by SharkblackFr** [comment]
Sorry I made a mistake
 yes custom blocks not added by a mod but by a resource pack.
it's thanks to the itemadder plugin that I have a resource pack with extra blocks.

**Comment by zNightlord** [comment]
Yes it's possible since resource pack model are simply json, so you can use the import model (.json) under Block model spawner.

**Comment by SharkblackFr** [comment]
So I can export from mineways directly from my build and get it back into blender provided I have imported my models?

> Yes it's possible since resource pack model are simply json, so you can use the import model (.json) under Block model spawner.

**Comment by zNightlord** [comment]
> So I can export from mineways directly from my build and get it back into blender provided I have imported my models?
> 
> > Yes it's possible since resource pack model are simply json, so you can use the import model (.json) under Block model spawner.

Not really sure what you mean? 
If you mean you got a world build with the resource pack on, export it and put it into Blender. The answer is NO. That's not how geometry world exporter work, especially Mineways. 
Minecraft world don't actually store the model resource pack inside and Mineways design don't actually do "custom block" (what you are referring to custom block resource pack plugin is custom model item)     

The import model (.json) spawn the "block" model by reading the json. _I personally find it's confusing with the model and mesh swap_ 

> JSON model importing has a few issues right now though

Since it's from resource pack, it won't be any issue hopefully. Because they don't do any weird complex model parent reference

**Comment by StandingPadAnimations** [comment]
> So I can export from mineways directly from my build and get it back into blender provided I have imported my models?
> 
> > Yes it's possible since resource pack model are simply json, so you can use the import model (.json) under Block model spawner.

No, Mineways (not sure about about jmc2obj) doesn't support JSON model exporting. You would have to import the JSON models in Blender and place then manually

**Comment by SharkblackFr** [comment]
ah that's my problem because I use mostly custom blocks. I will look at jmc2obj thanks

**Comment by TheDuckCow** [comment]
Closing this issue based on where this convo landed
