### ISSUE TITLE
Blender 3.4 Mix RGB Changes 

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#358]
@TheDuckCow pinging you on this issue since it relates to compatibility

Blender 3.4 has just been replaced, and with it the Mix RGB node has been replaced with a new Mix node. While Blender 3.4 should in theory convert Mix RGB automatically, it would be best if we don't have to rely on that conversion, considering how many materials MCprep works with.

**Comment by TheDuckCow** [comment]
Oof. Thanks for the heads up, seems I have a lot of code to be updating even outside MCprep ha.

Does @zNightlord 's change completely address this to our knowledge, or just a subset?

**Comment by StandingPadAnimations** [comment]
> Oof. Thanks for the heads up, seems I have a lot of code to be updating even outside MCprep ha.

Same here, I got some error porting in one of my Rust projects 😅

>Does @.zNightlord 's change completely address this to our knowledge, or just a subset?
The change introduced is a function that handles the difference between 3.4 Mix and the old Mix nodes (including sockets). As far as I can tell through my quick skim, it should essentially be seamless (though I haven't done a full review of the code yet).

**Comment by zNightlord** [comment]
Merged. You can close this issue now  👍
