### ISSUE TITLE
Mobs won't load correct 

### ISSUE THREAD

**Issue by Balu2004** [TheDuckCow/MCprep#359]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

![Zombie f](https://user-images.githubusercontent.com/121390481/209473038-e5ea859f-b01f-4a6b-aa32-38e8ac284017.png)
![Parrot f](https://user-images.githubusercontent.com/121390481/209473047-e00a52d7-77f1-4848-8916-46a87efa2f6d.png)
![Llama f](https://user-images.githubusercontent.com/121390481/209473055-cec3fce1-51c3-45ac-8220-73fe07c6c6aa.png)

It deosn't happen to all mobs and I didn't try which are working and which are not working. 
I just tried a few of them. 

I also removed and reinstalled Mcprep but that also hasn't fixed the problem. 

I use a Huawei Matebook D16 with an AMD Ryzen 5 4600H with Radeon Graphics.

I hope you can help me with that problem. 

### What steps are needed to produce the bug?

1) I just loaded the mob with Mcprep into Blender. It doesn't matter if you do it with the help of Shift + A or via pressing N to open the side menu. 

### What version of MCprep are you using?

Mcprep 3.4.1

### What version of Blender are you using?

Blender 3.2

**Comment by StandingPadAnimations** [comment]
Seems to be an issue with the clipping settings. Press N, go to view and send a screenshot of your clipping

**Comment by Balu2004** [comment]
![blender_XnvU83i7Er](https://user-images.githubusercontent.com/121390481/209507579-f9ec008c-1602-4435-aa45-5d5585e454e7.png)

**Comment by zNightlord** [comment]
This can close. Resolved in the Discord server
![image](https://user-images.githubusercontent.com/61040487/213439897-c42c30f6-36cd-4634-ac9f-c28e66a910a8.png)
