### ISSUE TITLE
Prep Materials Not Working

### ISSUE THREAD

**Issue by iron-coder12** [TheDuckCow/MCprep#365]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

So I am new to Blender and MC prep. I am following a tutorial by Black Plasma studios. So i am in material mode and when i click Prep materials i get an error

![image](https://user-images.githubusercontent.com/79589166/214915497-bebe7a24-d1af-45b8-a680-be7c4edfff97.png)

### What steps are needed to produce the bug?

I imported the .obj file of my world. I then hit A to select everything and go into MC prep choose mineways because thats what i am using and then i click prep materials

### What version of MCprep are you using?

2.1.3

### What version of Blender are you using?

2.7

**Comment by StandingPadAnimations** [comment]
We only support 2.78 and above (and even then we don't suggest using 2.7x). If you want to take full advantage of MCprep's features, it's recommended to use Blender 3.4 (the latest stable release). 

I should also point out that the BPS tutorial is extremely ancient. The most recent tutorial (for Minecraft animation specifically) is from 2.9 (which you can follow in 3.4 with very little issues): https://www.youtube.com/playlist?list=PLkN2rUqk0BtWVTVZomXYdJPrMnooovMKy

**Comment by StandingPadAnimations** [comment]
Also your version of MCprep is extremely outdated. The latest release is [3.4.1](https://github.com/TheDuckCow/MCprep/releases/tag/3.4.1)

**Comment by iron-coder12** [comment]
yes
