### ISSUE TITLE
Prep Materials with mineways not working

### ISSUE THREAD

**Issue by RandomUser35235** [TheDuckCow/MCprep#37]
I have my world imported and I'm in materials mode or whatever, and pressing "Prep Materials" does nothing. It says "0 objects modified" I have everything selected. I'm using Blender 2.78c.

**Comment by TheDuckCow** [comment]
Do you have the world objects selected when you press the button?

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by RandomUser35235** [comment]
If those are the objects that are imported from the Minecraft world, then yes.

**Comment by TheDuckCow** [comment]
When you get a chance, can you share a screenshot of the overall blender screen and then also confirm that these objects actually have existing materials with images (under texture tab or in an image node if cycles) already?

**Comment by RandomUser35235** [comment]
![image](https://user-images.githubusercontent.com/29438421/27196839-b6aebd58-51d1-11e7-90fd-6778e71e4e44.png)
It didn't seem like there were any textures at all.

**Comment by TheDuckCow** [comment]
For testing purposes, can you change it to blender internal and then click on the material tab with the world selected and then click on the texture tab, or look to see if any images are loaded into the image / uv editor?

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by RandomUser35235** [comment]
All I see is just a bunch of squares with a checkerboard pattern on them with no name.

**Comment by TheDuckCow** [comment]
Can you please pack the blend file and share here (you can upload files) so I can take a look? Thanks 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by RandomUser35235** [comment]
[RandomCrappyAnimation.zip](https://github.com/TheDuckCow/MCprep/files/1079506/RandomCrappyAnimation.zip)
Here.

**Comment by TheDuckCow** [comment]
Sorry for the long delay getting back to you, but I notice that there are no image references in the file - it doesn't even indicate there are *missing* images. Somehow the model was imported without any image information, unless it was since removed. What did you use to export the world, jmc2obj or Mineways? Did you make sure to export with materials?

**Comment by themoviea** [comment]
I can't prep materials because when i click it, it closes blender. please help me. I cant screenshot it.

**Comment by TheDuckCow** [comment]
@themoviea what version of blender were you using, and what version of MCprep?

**Comment by TheDuckCow** [comment]
Closing the issue in the meantime since no responses, let me know if either you @themoviea or @RandomUser35235 are still having issues.
