### ISSUE TITLE
A Standard Header for OBJs

### ISSUE THREAD

**Issue by StandingPadAnimations** [TheDuckCow/MCprep#371]
This proposal has been modified in the comments, from a new file format to a standard header

~~Technically this is more of a world exporter thing, but I'm opening it here since I think we need input from both the MCprep side and world exporter side.~~

# The Problem
~~Right now a lot of things like texture paths have to be hard coded on the MCprep side. As we saw with Jmc2obj 113, hard coding these paths isn't a good option. In addition, we don't have a way to distinguish between the use of a texture atlas and the use of individual textures.~~

# Proposed Solution
~~A new JSON like file format that would be exported alongside the OBJ and MTL files, containing this information. It would look something like this (subject to change):~~
```json
{
	"version" : 0,
	"world_exporter" : "WORLD_EXPORTER_IN_CAPS",
	"texture_type" : "ATLAS or INDIVIDUAL_TEXTURES",
	"obj_path"  : "/path/to/obj",
	"mtl_path" : "/path/to/mtl",
	"texture_paths" : {
		"standard_texture_name" : "/path/to/texture/"
		...
	} 
}
```
~~For `standard_texture_name`, it would be the name of the block in all lowercase letters, and with underscores for spaces. Examples include:~~
* Diamond Ore -> `diamond_ore`
* Oak Planks -> `oak_planks`
* Glass -> `glass`

# Why a New File Format?
~~By creating a standard file format, it allows us to write less code while still supporting many world exporters. In addition, world exporters can give extra, exporter specific information and tools like MCprep can use the `world_exporter` variable to take advantage of this extra info.~~

~~In addition, it prevents what happened with Jmc2obj 113, where MCprep for a while couldn't support OBJs exported with it due to texture path changes. By moving texture paths to a standard file format, issues like this would be eliminated, and world exporters could make changes without having to worry about backwards compatibility.~~

~~I'm curious what y'all think with this idea, any thoughts?~~

**Comment by StandingPadAnimations** [comment]
@TheDuckCow just curious about your thoughts

**Comment by TheDuckCow** [comment]
I'm always wary of inventing new file formats, but if it can be universally aligned on by _both_ Mineways and jmc2obj, there there might be some utility.

Not sure if you've come across this yet, but something fantastic that Eric did with Mineways is have it append "comments" in the OBJ output which already define how the obj was generated. If anything, it would be convincing jmc2obj to adopt the same convention. I would be happy to help promote the proposal if we can define it further, I'm *technically* part of the jmc2obj github org.

It still leaves it up to MCprep to parse both systems, but it seems decently feasible (compared to getting both Mineways & jmc2obj to agree to use our proposed file format _and_ implement it to specification the same way we hope).

Let me know what you think of this idea @StandingPadAnimations

**Comment by StandingPadAnimations** [comment]
I think that's a far better idea, since it's one less file for users to keep track of

I think we should also have somewhere some documentation on the convention for other world exporters to utilize, if they so wish

**Comment by TheDuckCow** [comment]
Great. Let's formalize the request here to see we're on the same page, then we can move the convo over to jmc2obj.

In terms of format, I'll start by sharing what Mineways does. Below is the "header" of an OBJ file I generated quite awhile ago  (wow, on the eve of the pandemic hitting...). All the header lines are prefixed with a `#` to indicate a comment. The rest are close to equivalenet to script inputs that you would use to run Mineways programmatically.

```
# Wavefront OBJ file made by Mineways version 7.10, http://mineways.com
# Minecraft world: TestNewWorld1_15_2
# Terrain file name: default
# Color scheme: Standard
# Mon Feb 17 14:57:06 2020

# Selection location min to max: -70, 3, -36 to -58, 255, -25
#   Non-empty selection location min to max: -70, 3, -36 to -58, 7, -25

# Set render type: Wavefront OBJ absolute indices
# Units for the model vertex data itself: meters

# 698 vertices, 577 faces (1154 triangles), 166 blocks, 85 billboards/bits
# block dimensions: X=13 by Y=6 (height) by Z=12 blocks
# File type: Export tiles for textures to directory textures
# Texture output RGB: YES
# Texture output A: YES
# Texture output RGBA: YES
# Export separate objects: YES
# Individual blocks: no
#   Material per object: YES
#   Split by block type: no
# G3D full material: no
# Make Z the up direction instead of Y: no
# Create composite overlay faces: no
# Center model: YES
# Export lesser blocks: YES
# Fatten lesser blocks: no
# Create block faces at the borders: YES
# Make tree leaves solid: no
# Use biomes: no
# Rotate model 0.000000 degrees
# Scale model by making each block 1000 mm high
# Data operation options:
#   Fill air bubbles: no; Seal off entrances: no; Fill in isolated tunnels in base of model: no
#   Connect parts sharing an edge: no; Connect corner tips: no; Weld all shared edges: no
#   Delete floating objects: trees and parts smaller than 16 blocks: no
#   Hollow out bottom of model, making the walls 1000 mm thick: no; Superhollow: no
# Melt snow blocks: no
#   Debug: show separate parts as colors: no
#   Debug: show weld blocks in bright colors: no

# Full world path: Z:\Users\patrickcrawford\Library\Application Support\minecraft\saves\TestNewWorld1_15_2
# Full terrainExt.png path: default
# Full current path: Z:\Users\patrickcrawford\Documents\GITS\bitmisc\mcprep_stats
```


For jmc2obj, I think it would be a matter of coming up with a similar standard header annotation, and then make a line by line dump of all the settings that can be configured by the user. The tricky thing is that it would be something that easily gets out of date, and if the developers aren't paying attention, will become outdated if someone adds a new flag for instance. But that would be part of the discussion.

**Comment by StandingPadAnimations** [comment]
I think we could add some form of versioning, perhaps something like `# Version: 1.0`. Beyond that, everything seems perfect

**Comment by StandingPadAnimations** [comment]
I've already noticed that Mineways has slightly different ways of saying the same feature. For example the following in the example above:
```
File type: Export tiles for textures to directory textures
```

Is this in a OBJ I exported today:
```
File type: Export individual textures to directory tex
```

This will being some issues

**Comment by TheDuckCow** [comment]
Meant to close this / package as part of the prior release. We have an initial foundation here, will expand on over time.
