### ISSUE TITLE
Can't 'check' the Object: MC Prep box

### ISSUE THREAD

**Issue by Jonny654** [TheDuckCow/MCprep#38]
I tried to install the addon but when I transferred it into blender it wouldn't let me check the box for Object: MC Prep. I don't know what I did wrong. I am using v2.66

**Comment by TheDuckCow** [comment]
Please try using blender 2.72 (released 2014-Oct-23) or newer, the latest released is 2.78. It's hard to support such old versions of blender but you'll be getting a lot better results if you use a more recent version! Let me know if that works.

**Comment by Jonny654** [comment]
Oh wow didnt know I had an old version... My mistake thank you
