### ISSUE TITLE
This doesn't make sense

### ISSUE THREAD

**Issue by ScorchingDragon** [TheDuckCow/MCprep#4]
Im downloading MCprep_addon_v2.1.3.zip on my Mac OS X but aster that, I don't know what to do. Please help me!

**Comment by TheDuckCow** [comment]
Please take a look at the readme file located below, it shows you need to install the addon in blender by going to the use preferences window/addons 

https://github.com/TheDuckCow/MCprep

**Comment by ScorchingDragon** [comment]
Thanks!
