### ISSUE TITLE
Prepping materials makes everything pink

### ISSUE THREAD

**Issue by Jondor123** [TheDuckCow/MCprep#40]
So I put my world into blender, and that worked fine. Selected mineways in the mcprep tab then clicked on prep materials. When I did that it made everything pink. I even tried downloading the older version, 2.1.3  (The one where a guy on youtube used and it worked, I was also using the same version of blender). Then I did the same thing and click on prep materials and it still made everything pink. Does anyone know what causes this and how to fix it? Any help would be much appreciated!

![screenshot_61](https://user-images.githubusercontent.com/30361018/28487458-39012956-6e80-11e7-8856-4d33e125d52e.png)

**Comment by Jondor123** [comment]
I opened a new blender file, had the render mode Blender Render and imported the map. It started out as just white but when I changed it to textures it was just pink. I didn't mess with anything else.

**Comment by Jondor123** [comment]
Also what do you mean by the textures, or lost the link to them?

**Comment by Jondor123** [comment]
Actually nevermind, I managed to get it working. I know what you meant by the texture file, and I must have moved the obj file without moving the texture file as well. Thanks for the help!

**Comment by TheDuckCow** [comment]
Yup, it happens. In the future I may include a popup helping earn people if this is detected.
