### ISSUE TITLE
Create env file for dev flag loading

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#400]
I'd like MCprep to move to having an environment file. One which, when absent, means the addon works in "prod" mode. But if present in the install folder, means its parsed for settings and feature flags. I hate how I have to create commits to flip/flop the dev=true/false, and this would get around that.

We could decide if there are any other settings included, but for now the most critical one would be the `dev` flag. Beyond that, philosophically, it should only be used as a way to represent building a custom addon in some way; it should not be seen as a way or alternate source of assigning settings or preferences (where relevant, we should just expose more settings in user preferences).

FYI @StandingPadAnimations

**Comment by StandingPadAnimations** [comment]
Should be simple enough with `json` (`.env` is not natively support iirc). I'll add this for #348

**Comment by StandingPadAnimations** [comment]
Oh wait, hold up, I didn't see the build part

What we could do is have a folder called "patches" (ignored by Git) that are applied by the compile scripts. Patches are commonly used in the Linux world, but as far as I know they only require Git. 

https://about.gitlab.com/blog/2021/03/15/patch-files-for-code-review/

Of course this still suffers from Git being, well Git, but as long as we keep it to small parts of the code I think it'll be fine

**Comment by StandingPadAnimations** [comment]
Btw all this would need is us changing dev locally, and do:
`git diff > dev-build.patch`

Then:
`git apply dev-build.patch`

**Comment by StandingPadAnimations** [comment]
So from a compile.sh standpoint, I think we could add a flag like `--dev-build` that applies the patches, and otherwise ignore them

**Comment by TheDuckCow** [comment]
Hm I'll have to think about that, not sure I like a git diff as much. But let's first get the new internal refactor in with the flags, then we can think more about this dev vs prod flag.

**Comment by StandingPadAnimations** [comment]
Yeah I just realized that git diffs would bring more issues as time passes, so I have an alternative solution (albiet from the land of C) 

Preprocessor statements. We could have the compile scripts call a preprocessor that goes ahead and removes parts of the code depending on the arguements. We could combine this with a text file that has the flags we want to pass. 

Advantages:
- Simple
- Easy to implement 
- Can write preprocessor directives directly in the code

Cons: 
- Linters may not understand preprocessor directives (and consider them comments) 
- Harder for new programmers 
- Adds an additional script to building

**Comment by StandingPadAnimations** [comment]
Alright here's an early test of preprocessing

![video](https://user-images.githubusercontent.com/75058058/226142949-16e1b536-1a55-49b2-b903-99782851b4d4.mp4)

**Comment by StandingPadAnimations** [comment]
Alright so I've made a GitHub repo for it. It still doesn't support directories but that's the next logical step

https://github.com/StandingPadAnimations/python-preprocessor

**Comment by TheDuckCow** [comment]
Just wanted to quickly comment, I think this is a little more complicated that what we really need, though I appreciate the experimentation! The bare minimum in my mind is just parsing for/detecting if a "dev.txt" file exists in the addon folder next to the init file, and the code just checks for the existence of this file (with some extra steps to delete it if a new installed happened and it's not part of the files newly installed).

(The next level beyond that would be actually parsing the file for values, which is probably worth doing from the get go anyways, but can be a simple .ini or json parser tbh)

This is extending from the philosophy that one should be able to ship all code to different environments without modification, hence moving to use config files if anything needs to change between those environments (hence, the external file, and when lacking, represents prod).

**Comment by TheDuckCow** [comment]
Ah though on a further look..... maybe this is pretty close already to what you mean? I may be misunderstanding what you meant by preprocessing. I see the [file here](https://github.com/StandingPadAnimations/python-preprocessor/blob/main/main.py) is doing similar to what I'd expect we'd want to do in terms of just parsing a file and extracting values to put into a dataclass, which is good.

End guidelines remains though, I'm biased towards the least complex solution where possible.

**Comment by StandingPadAnimations** [comment]
> Ah though on a further look..... maybe this is pretty close already to what you mean? I may be misunderstanding what you meant by preprocessing

In the C++ world, preprocessing is the stage done by the compiler before actually compiling. Basically it uses directives to decide what code to keep/remove

**Comment by TheDuckCow** [comment]
Right right. So let me know if you are on the same page of this net result:

1. Developer has the repo local and any env_dev.ini or other files already
2. They run the compile.sh/bat script (with a flag to specify environment, ideally defaulting to dev actually)
3. It then starts copying files into the build folder locally (current functionality)
4. It copies the env file (with the environment specific settings including dev flag) into the build folder, or no file if prod
5. Then the script creates the compiled addon, the zip file, containing this env file
6. On blender startup, the installed addon would check if there is a new environment file (likely named `env_update.ini` or similar, created in step 4) to overwrite the existing env file. If other files were detected as being updated but there's no env_update file, just delete any existing env file
7. And finally, the addon checks for the env file and if found, loads the settings it specifies.

Let me know if this makes sense! I can also share and example where I've done this before.

**Comment by StandingPadAnimations** [comment]
Makes sense, I'll get a working prototype done in the next couple of days. The new MCprepEnv class should help in this case as well

**Comment by TheDuckCow** [comment]
Yeah exactly, I think it would be a subset of vars would be in the env.ini/json that get loaded into the dataclass

**Comment by StandingPadAnimations** [comment]
I just realized this is issue number 400

**Comment by TheDuckCow** [comment]
Woo! Also, is this technically done now @StandingPadAnimations?? I'm losing track a bit of what made it into milestone-3-5-0 at this point.

**Comment by StandingPadAnimations** [comment]
Yep, it's already been implemented (just pass -d to the build script)
