### ISSUE TITLE
Force blender restart if update detected

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#402]
If we detect an update occurred, either due to a manual install or the automated installer, we should *force* the user to restart blender by only showing "Updated, restart blender" in the MCprep panel.

Alternatively to this, we could explore triggering the "reload all scripts" function, though that affects all scripts and not just MCprep.

This will help eliminate the issues that get reported around updating due to people not restarting, while also helping users actually avoid problems in the first place.

**Comment by TheDuckCow** [comment]
This video shows the final functionality in practice (FYI to @StandingPadAnimations who I've marked as a reviewer):


https://user-images.githubusercontent.com/2958461/227726838-bea96713-f514-417a-b34e-5fb715b15b70.mp4

**Comment by StandingPadAnimations** [comment]
I find every panel telling the user to restart Blender absolutely hilarious

**Comment by TheDuckCow** [comment]
ha yeah it does feel a bit excessive, but certainly gets the point across.

Another option I suppose would be to have all other panels conditionally not appearing. Normally I don't like appearing and disappearing panels (it's very unintuitive for users), but in this case it would actually be reasonable I suppose. What do you think, worth the change?

**Comment by StandingPadAnimations** [comment]
I think it would be a much better idea. It also means we could add more information like "Restarting Blender is a must for updates to properly apply and not cause issues"
