### ISSUE TITLE
Warden causing Reload Mob errors in 2.8x and 2.9x

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#403]
For some reason, 2.8x and 2.9x users are encountering errors when importing specifically the warden rig:

```
File "<addon_path>/mobs.py", line 206, in execute
 update_rig_list(context)
 File "<addon_path>/mobs.py", line 148, in update_rig_list
 _add_rigs_from_blend(blend_path, blend_name, category)
 File "<addon_path>/mobs.py", line 65, in _add_rigs_from_blend
 with bpy.data.libraries.load(path) as (data_from, data_to):
 OSError: load: C:\Users\{REDACTED}\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MCprep_addon\MCprep_resources\rigs\hostile\Warden - DigDanAnimates.blend failed to open blend file
```

I see no reports for Blender 3.x implying it's a compatibility problem. This is likely rig asset fix we need to make.

This accounts for 122 of the 704 bugs reported in the last few days. As a breakdown of current bug reporting:

- 494 (70%) are due to the material conversion issue.
- 122 for THIS warden rig issue (17%)
- 76 for the block material failing to import (10%)
- Only 12 for truly anything else (~2%) (mostly reloading errors or more unique fatal issues like MCprep props not being registered, I'd bucket under reloading blender issues)

**Comment by TheDuckCow** [comment]
There is also a more general improvement that should happen, apparently the issue is happening actually during "mob reloading", so really any flaky mob model will break the loading of all of them. We should likewise make mob lading much safer during the reading of a blend file, fail by skipping that single entry.

**Comment by StandingPadAnimations** [comment]
> I see no reports for Blender 3.x implying it's a compatibility problem. This is likely rig asset fix we need to make.

*I sense a perfect "first contribution" type issue for new developers*

**Comment by TheDuckCow** [comment]
I would agree would ordinarily be a good first contrib, but there's some strong urgency behind this one that we'll want to resolve it in the next couple days.

I just did a test myself, and I'm not seeing any issues loading the warden rig there. I am using blender 2.90. Looking back at the error reporting database, I see:

- Only one error for a linux user (likely a fluke)
- 153 (all others) are from windows users,
- 0 Mac user reports (but mac users are also already a minority).
- Reports coming from blender versions including the full list below

Full blender version list with at least 1+ report (so once again, seems like a pretty even spread of version ≥ 2.80 and < 3.0)

```
(2, 93, 9)
(2, 93, 8)
(2, 93, 6)
(2, 93, 5)
(2, 93, 4)
(2, 93, 3)
(2, 93, 2)
(2, 93, 15)
(2, 93, 14)
(2, 93, 1)
(2, 93, 0)
(2, 92, 0)
(2, 91, 2)
(2, 91, 0)
(2, 90, 1)
(2, 90, 0)
(2, 83, 5)
(2, 83, 20)
(2, 83, 2)
(2, 83, 0)
(2, 82, 7)
(2, 80, 75)
```

We will need to see if we can reproduce this on a windows machine, I'm scratching a head a bit on why I can't get the error. The volume of errors is very substantial, so a large quantity of people for sure are running into this.

**Comment by CFeeney333** [comment]
![image](https://user-images.githubusercontent.com/96747360/226611216-21d008f8-41c2-4b39-bd66-eb2e4e74b2d2.png)
hmmm.... happened for me on windows. blender 2.93. when i click reload mobs
if the problem is with the model/rig, how can we fix the issue?

**Comment by StandingPadAnimations** [comment]
What I find strange is that the error is saying Blender couldn't open the file. I wonder if Blender has some form of internal logging we could take advantage of

**Comment by CFeeney333** [comment]
#405 gave the issue a look over myself here, so no worries
