### ISSUE TITLE
Will not let me tick the box to activate.

### ISSUE THREAD

**Issue by SomePerson11** [TheDuckCow/MCprep#41]
It installs fine, but it will not let me tick the box so I can't use it.

Please help me. :(

**Comment by TheDuckCow** [comment]
Can you take a screenshot of the error that pops up? What version of blender are you using? It should be version 2.72 or newer

**Comment by SomePerson11** [comment]
Oh, I only use 2.66.
Whoops

**Comment by TheDuckCow** [comment]
Yup that's fairly old for blender standards, 2.66 was released early 2013 - I highly recommend downloading the last version from blender.org, it will have many more stable and useful tools for you, along with more general addon support.

**Comment by SomePerson11** [comment]
For some reason, any version like 2.72 or higher will not work.

**Comment by TheDuckCow** [comment]
Can you please share he screenshot of the error message here?

**Comment by SomePerson11** [comment]
![thing](https://user-images.githubusercontent.com/30365353/28741103-52f63ed6-744e-11e7-97ff-2f9db2e502ba.PNG)

**Comment by TheDuckCow** [comment]
Ah you mean a problem with blender itself. I'm sorry not sure how much I can help with that since that's not related to MCprep directly but rather to what blender itself supports. What operating system and version are you on?

**Comment by SomePerson11** [comment]
I use windows 10.
And I use all three.
I need admin password for MSI, and that message comes up for ZIP files and EXE installers.

**Comment by TheDuckCow** [comment]
I recommend following this and see if this page can help with the issues, it seems to be more of a computer problem/admin setup/antiviral problem than a blender problem as I know blender of course works on windows 10.

http://tipsarea.com/2015/08/05/how-to-fix-the-application-was-unable-to-start-correctly-0xc0000022-error/

**Comment by TheDuckCow** [comment]
Closing for now due to not being an MCprep issue, but you can still comment back if needed.

**Comment by SomePerson11** [comment]
Okay, thanks anyway.

**Comment by SomePerson11** [comment]
It didn't work.
