### ISSUE TITLE
Weird grass texture when rendered in Cycles

### ISSUE THREAD

**Issue by DraxDoomer** [TheDuckCow/MCprep#413]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Ive had this problem for a while when I am trying to make a barebones mc world for an animation and renders. This happens after I change the textures of the mineways imported world to use the barebones texture pack using the "Swap Texture Packs" features on mcprep. The grass looks fine when unrendered but when rendered in cycles it looks weird (look at screenshots). It seems to be fixed when I delete a grass face that seems to be duplicated but doing that for a lot of grass is going to take ages. How do I fix this?

Unrendered:
![grassunrendered](https://user-images.githubusercontent.com/129639006/229329155-2318f95a-7f32-4dc5-86f1-28006dafa235.JPG)

Rendered:
![grassrenderedproblem](https://user-images.githubusercontent.com/129639006/229329161-709aca67-37ac-47bf-85bd-0979ec18a8f1.png)

### What steps are needed to produce the bug?

1) I imported the world using Mineways
2) I MCPrepped the world
3) I selected the world and click the "Swap Texture Pack" button on MCPrep and then went into the barebones texture pack file
4) I rendered the scene in Cycles

### What version of MCprep are you using?

MCPrep v3.4.3

### What version of Blender are you using?

Blender 3.4

**Comment by StandingPadAnimations** [comment]
It's a known issue with Mineways OBJs in Blender, just do the following:
- Select the whole OBJ
- Go to edit mode
- Select all of the faces with A
- Press M, and select "Merge by Distance" 

MCprep doesn't do this to avoid users using lower end hardware from going "why is MCprep taking so long" or "Blender keeps crashing"

**Comment by DraxDoomer** [comment]
Ah i see

And I did what you suggested and I still have the error, sorry

**Comment by StandingPadAnimations** [comment]
Yeah then there's not much that can be done. This is more of a Mineways
issue rather then an MCprep one.

Personally, I would suggest using jmc2OBJ, since that tends to have less
of these issues.

**Comment by DraxDoomer** [comment]
Aw welp. Thx for the help anyways

I want to use jmc but for some reason it won't work on my computer. Apparently just when I run jmc, it seems to be using up a lot of ram when its not supposed to. But ye I know I should not discuss this too much here and since this is supposed to be related to MCprep.

**Comment by StandingPadAnimations** [comment]
Just curious, are you using the Java installation from java.com? If so,
then jmc2obj will only have access to 4 GB of RAM, hence why it may seem
like it's using a lot when it actually isn't.

Try Adoptium, which are OpenJDK builds provided by the Eclipse
Foundation: https://adoptium.net/temurin/releases

If given the option to select between Hotspot and OpenJ9, choose Hotspot
for compatability reasons (before you ask, Java is more like C and C++
in implementation these days, in that there's a standard and people make
"implementations" according to that standard).

**Comment by DraxDoomer** [comment]
Yeah i just realised yesterday i have been using 32-bit java which only allocates 4GB of ram. I downloaded the 64-bit version from the java website itself and now jmc is working. 

Thx for helping anyways.
