### ISSUE TITLE
Glitch When Importing Villager Rig

### ISSUE THREAD

**Issue by Mnazz10** [TheDuckCow/MCprep#416]
I've Imported A Villager Rig Into My Blender Project But It Gets Glitched Every Time.

https://user-images.githubusercontent.com/80792110/230642611-512e4fef-4311-41c5-ae45-120275f01669.png

I've Tried The Following:

- Making A New Project
- Redownloading MCprep
- Upgrading Blender

I've Imported Other Mobs And Their Rigs Are Fine.
I Need A Way To Fix This Problem.

**Comment by zNightlord** [comment]
When spawn the villager uncheck Prep material, that villager has some custom shader so prep material clear it.

**Comment by Mnazz10** [comment]
I don't Know If I Did It Wrong Or It Doesn't Work But Here Is How I Did It:


https://user-images.githubusercontent.com/80792110/230695757-878ccd57-9b1d-44f2-94a2-14a2abdc9a94.mp4

**Comment by 1328302541** [comment]
I had the same problem

**Comment by StandingPadAnimations** [comment]
@Mnazz10 you're supposed to use the bug report form, so I'll have to close this issue (you will still be able to comment on it though)

That being said, this is a known issue, and #430 has a fixed rig
