### ISSUE TITLE
Odd materials

### ISSUE THREAD

**Issue by Thebayu** [TheDuckCow/MCprep#42]
When I imported a world for some reason in material view leaves look nice and green but in rendered view leaves, water, and tall grasses appear whitish. How can I fix this?

**Comment by TheDuckCow** [comment]
My guess is that the grass material is using a desaturated mask or its using the alpha mask instead of the color. To assist further, can you select the leaves and take a screenshot of the material setup (and if it's cycles, of the node layout)

**Comment by Thebayu** [comment]
Here: https://imgur.com/a/TFvqS, https://imgur.com/a/MBXcL

**Comment by Thebayu** [comment]
How do I fix it?

**Comment by Thebayu** [comment]
Kind of urgent.

**Comment by TheDuckCow** [comment]
Sorry - it's a holiday weekend here in the US. Looking at the screenshots, I'm still trying to understand the issue. I may be best able to help if you share (and **package the blend file**) and upload here (you can attach files directly here, also true for images...).

But as it is in the second screenshot, I see you're using blender internal. Thus I'd take a look at the texture tab, my guess is there may be more than one layer or something odd for the transparent materials.

Followup question - *where is the world exported from, and did you use the [exactly recommended settings](https://raw.githubusercontent.com/TheDuckCow/MCprep/master/visuals/exporterSettings.png) for exporting*?

**Comment by Thebayu** [comment]
I did not change any export settings, I will get the blend file in a few minutes.

**Comment by TheDuckCow** [comment]
I would first test exporting with the recommended settings. if the issue persists, then share the file resulting (again, be sure to pack it)

**Comment by Thebayu** [comment]
What are the recommended settings, and how do I "pack" it?

**Comment by TheDuckCow** [comment]
These are the recommended settings:
https://raw.githubusercontent.com/TheDuckCow/MCprep/master/visuals/exporterSettings.png

Also, make sure if you haven't before to watch the video about importing (video for jmc2 obj, but process applies to mineways in same way with the mineways settings)
https://www.youtube.com/watch?v=iRixJzraHFI&t=26s

You pack a  blend file by going to file > external data > Automatically pack. (and then save and send)
