### ISSUE TITLE
Chest Not Working

### ISSUE THREAD

**Issue by Abbimation** [TheDuckCow/MCprep#427]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I tried to open the chest but the bones doesn't work.

### What steps are needed to produce the bug?

1.Recreate the chest

2. Recreate the bones

3. Add rotation, scale, etc to the bones.

### What version of MCprep are you using?

3.4

### What version of Blender are you using?

3.4z

**Comment by StandingPadAnimations** [comment]
If you're referring to mesh swap (which I assume you are), select the chest, then press F3, then type "Make Instances Real" and press enter

**Comment by TheDuckCow** [comment]
Closing this issue in the meantime, but let us know if this did not solve your problem.
