### ISSUE TITLE
Mcprep turning objects invisible.

### ISSUE THREAD

**Issue by imHugHug** [TheDuckCow/MCprep#428]
I am using Blender 2.76 (long story why I need to use an old version) and MCprep 3.2.5.1.

i imported my .obj file from mineways. When I use the prep materials button on the mineways tab it works fine and everything is assigned a material and texture. However, when I go to render using F12 a bunch of objects are not rendering. As in the are invisible. If I dont use prep materials and try a render I can see the object but obviously everything is all white and unusable. 

Why is the prep materials turning my brown terracotta, and all wood and logs invisible when I try and render? 

There are no render restrictions on. Its almost like everything brown is being keyed out.

**Comment by StandingPadAnimations** [comment]
MCprep 3.2.5.1 was released 2 years ago and as such is no longer supported. In addition, 2.76 (released back in 2015) is also no longer supported by MCprep (and the rest of the 2.7x series will be unsupported with MCprep 3.5 as mentioned in #399). As such, I will be closing this issue.

That being said, on the bottom of the Render tab, there is a section called [`Post Processing`](https://docs.blender.org/manual/en/2.79/render/post_process/panel.html)  (at least in 2.79+, there doesn't seem to be a manual for 2.76 on the official Blender docs). See if disabling `Sequencer` and/or `Compositor` helps.
