### ISSUE TITLE
Automatically set imported material textures to "closest" instead of "linear"

### ISSUE THREAD

**Issue by Entropy159** [TheDuckCow/MCprep#436]
### Check against existing requests

- [X] I have checked existing feature requests, and my idea is different

### Describe the context

Whenever I import a world from Mineways into Blender, the textures are all blurred because the interpolation mode is always set to linear. I have to manually go to every material and set it to closest. It would be nice if it automatically did that for me.

### How do you imagine your feature works?

I think it should happen as it's importing the world. As it's assigning the textures to the materials, it would just set the interpolation mode to closest.

### What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.

The only workaround I can think of is to manually set the interpolation mode for every material.

**Comment by StandingPadAnimations** [comment]
That's what prep materials is for (the main feature of MCprep advertised)? By default it's set to "Simple" which retains the simple node setup OBJs have on import. 

We can't override the OBJ importer in Blender itself, that's beyond the API (and frankly it would be a bad idea anyway if a bug occurs). While as can add extra code for MCprep's world import before and after importing the OBJ, we reserve that for things that require having access to the OBJ files themselves (like allowing OBJs to be imported for ACES or fixing accidental clicks on MTL files). 

I'll closed this issue, but you're welcome to comment on this issue
