### ISSUE TITLE
Prep materials not working on MCPrep

### ISSUE THREAD

**Issue by Anonanon2323** [TheDuckCow/MCprep#44]
Dear all,

I am having problems with MCPrep. I am on Cycles Render, Texture view etc. 

Screenshot:

<img width="2048" alt="Image 1" src="https://user-images.githubusercontent.com/39518740/40355319-fafdc5e2-5dad-11e8-9366-23c0db894c6c.png"></img>

When I click Prep materials, it says modified x materials, but nothing changes. Do I need minecraft installed for this to work? I don't have it ... maybe this is the problem. I am following Black Plasma Studios' tutorial on YT.

GitHub is giving me problems uploading the file, because it is SOOO big.

I've tried improving UI, Mesh swapping, nothing works. I have even tried tricking the computer into thinking I have Minecraft by downloading MC Assets; if there is a place in the computer I can put this so it tricks further that would be great. I used Mineways to get the file.

Thanks for any help!

**Comment by TheDuckCow** [comment]
Hey there,

Did you take a look in rendered mode? Your screenshot is of solid mode, which won't normally show textures/colors unless you change other settings. Be sure to add a light and see if the materials show up then. If it's all pink, then the files maybe got moved or mis-located after importing. 

Let me know if that helps at all. You can also further see if you open a UV image editor and any of the images appear there (again, if they don't or are blank, it points to the textures being misplaced).

**Comment by Anonanon2323** [comment]
@TheDuckCow,

I'm a bit of a beginner at MC Animation with Blender, and this will sound weird, but I don't really understand the comment above! Thanks for the trouble, but could you tell me which buttons to press?!?!

**Comment by birawaich** [comment]
The button that needs to be pressed:
<img width="2048" alt="screnshoot_marked" src="https://user-images.githubusercontent.com/27787788/40579482-335fa81a-6128-11e8-91c1-8b0665ea6329.png">
There select __Rendered__ as the option. Then follow @TheDuckCow 's Comment ;)

If you are new to blender I can highly recommend reading the official blender manual:
[Official Blender Manual (English)](https://docs.blender.org/manual/en/dev/)
It is actually really well written and even though watching videos sounds more fun it's in my opinion the way to go. The big advantage is that it is A) the current version and B) easy for you to look up again when you forgot a detail. It personally helped me a lot.

Not related to your Problem:
I'm back @TheDuckCow! I am currently not looking into the code I wrote a year ago. I hopefully will have a project at work soon for which I'll find a reason to use blender, and then when I'm back in blender I'll investigate in what's going on with the lights in your plugin ;)

**Comment by Anonanon2323** [comment]
Dear @TheDuckCow and @birawaich ,

When I put it in rendered mode it does in fact go all pink. Should I re-import the file?

**Comment by Anonanon2323** [comment]
Here is a screenshot:

<img width="2048" alt="screen shot 2018-06-04 at 11 08 57" src="https://user-images.githubusercontent.com/39518740/40911806-b77ee12c-67e7-11e8-89b7-7695503f9c63.png"></img>

**Comment by TheDuckCow** [comment]
Yes, it seems your textures have been misplaced @Anonanon2323. When exporting your world, 1) make sure you also export the textures from the program to a folder. Then, after exporting your world, make sure you don't move the obj file or material file away (or at least, keep it the same "relative path" to the textures folder). 

Let me know if that makes sense.

**Comment by Anonanon2323** [comment]
Dear all,

I finally understand what's going on!! I was storing the wavefront OBJ file on a separate school server starting with 'smb://'. So, all the textures were instead stored locally on the computers!! It makes sense. I will try and use the configuration where I can create a zip file with all textures and store it on the server. Thanks all for the help.

**Comment by TheDuckCow** [comment]
Great! Glad you sorted it out, and happy blending.

**Comment by TheDuckCow** [comment]
Hi @EndlessDoom FYI you commented on a close issue, so I normally wouldn't see it (if needed, you can open a new issue). Make sure you select all materials first, but btw, it would only really be relevant to run on a world import, character materials generally should already be fine.
