### ISSUE TITLE
mcprep not working

### ISSUE THREAD

**Issue by B4raaG4mer** [TheDuckCow/MCprep#46]
i can set he on blender but i cant prees him plz tell me ho to fix plzz

**Comment by B4raaG4mer** [comment]
tell me plz

**Comment by TheDuckCow** [comment]
Sorry for the delay, I'm not really sure based on your description what issue you are encountering. Are you trying to prep materials? Try to press "Improve UI" as well, or go into render mode (shift+z in the 3D view, or press F12); make sure you have some lights in the scene. Hopefully this helps.
