### ISSUE TITLE
Trubble with "prep materials"

### ISSUE THREAD

**Issue by StarCatz11** [TheDuckCow/MCprep#47]
so i have an issue with MCprep... when i import a mineways .OBJ and click "prep materials" it says i have 0 objects selected.  
here are some screen shots incase you need them:
![screen shot 2018-06-11 at 5 37 09 pm](https://user-images.githubusercontent.com/40186254/41262478-4991d16c-6d9e-11e8-9a08-4d01a572f0ab.png)

![screen shot 2018-06-11 at 5 36 44 pm](https://user-images.githubusercontent.com/40186254/41262483-4e5d7d7c-6d9e-11e8-96e2-a3d9fff34735.png)

**Comment by TheDuckCow** [comment]
Sorry you’re having an issue. It almost looks like there aren’t any existing materials on the model - could you confirm by seeing any image textures are in the file by going to the UV image editor and clicking the drop down to see images? If there are none, then most likely the model wasn’t exported with material information, or the material file (I believe it’s .mtl) was not next to the obj file. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Hey @StarCatz11 just following up, have you tried the above to see if any materials or images already exist?

**Comment by TheDuckCow** [comment]
Closing issue for now @StarCatz11 but let me know if you've tried again recently and still had trouble.

**Comment by StarCatz11** [comment]
sorry for the late response, thanks it has worked for me now. nice addon
