### ISSUE TITLE
i t does not want to install it gives a long error

### ISSUE THREAD

**Issue by Samyipy** [TheDuckCow/MCprep#49]

**Comment by TheDuckCow** [comment]
Can you please include a screenshot of the error? Also be sure to use the latest released version of blender ie 2.79.

**Comment by Samyipy** [comment]
Yes I have blender v2.79b

**Comment by TheDuckCow** [comment]
Based on those errors, there’s an issue with the version of python that blender is using, of which one dependency MCprep uses. 

Can you explain how you installed this version of blender? Did you use the windows installer, or is it running from a zip - extracted download?

To resolve, I recommend actually using a different blender build - try 2.79a, and try using the zip download from blender.org over the installer package. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Just following up @Samyipy, did you try the above or otherwise have any further success?

**Comment by Samyipy** [comment]
I don’t  understand what 

[TheDuckCow/MCprep] i t does not want to install it gives a longerror (#49)

What does that mean I must do
Sent from Mail for Windows 10

**Comment by TheDuckCow** [comment]
Try using a different version of blender - because the one you have happens to have an invalid or missing library MCprep. e.g. try 2.79a from here: https://download.blender.org/release/Blender2.79/ (and choose the according windows, e.g. blender-2.79a-windows64.zip or blender-2.79a-windows32.zip)

**Comment by TheDuckCow** [comment]
Any luck @Samyipy?

**Comment by TheDuckCow** [comment]
Closing in the meantime, but @Samyipy let me know if you try again with another version of blender and still have the same issue.
