### ISSUE TITLE
Prep Matirials not working

### ISSUE THREAD

**Issue by Steel-Smasher** [TheDuckCow/MCprep#5]
I've recently uploaded my world to blender using Mineways and editing with MCprep, but for some reason unlike in any youtube videos I've seen the Prep Materials button wont work, it will only be clicked and nothing will happen,still colorless. 

https://youtu.be/cF5x6P0bHNU <----A video of me trying to use Prep Materials

**Comment by TheDuckCow** [comment]
Hello,

MCprep only modifies materials, doesn’t create them. It looks like your world imported has no materials attached, so the add-on won’t work. Try exporting with it or making sure you don’t lose the material files? What did you use for exporting, JMC2obj or Mineways?


Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com <http://www.theduckcow.com/>
youtube <http://www.youtube.com/TheDuckCow>, twitter <https://twitter.com/TheDuckCow>, facebook <https://www.facebook.com/TheDuckCow>

**Comment by EpicMadBadger** [comment]
I am having the same problem.  I have imported the world using Mineways as per the instructions on various YouTube videos.  It seems to save okay and upload to Blender fine, but nothing happens when I hit the Prep Materials button.  I have tried uninstalling everything and starting from scratch, but nothing is helping.  i am using Windows 7 on my PC and Windows 10 on my laptop and it doesn't work on either.  I have seen a lot of comments on a Blender YouTube video which suggests a lot of people are having this same problem.  Any suggestions?

**Comment by ColbyPlayz** [comment]
At the bottom, look for the box that says object mode. To the right, click the circle and select Material!

**Comment by ColbyPlayz** [comment]
![capture](https://cloud.githubusercontent.com/assets/19244367/15094997/fd88acec-147a-11e6-8764-b9bbc74134ec.PNG)

**Comment by EpicMadBadger** [comment]
Thanks for that ColbyPlayz!  It worked as long as you change it to Material before you try to Prep Materials.  I can get on with my animation now.  Thanks again !!!

**Comment by TheDuckCow** [comment]
To elaborate, it should work in both cases to my knowledge - you just don't see any modification in the solid view mode because the effects only exist when rendered. Would you confirm this is the case? It would be visible on render in both cases.

Thanks Colby for helping out :)

**Comment by EpicMadBadger** [comment]
It only worked for me if I changed it before hitting the Prep Materials.  It could be a quirk of my system though!!

**Comment by TheDuckCow** [comment]
To be honest, I didn't actually think about getting the textures to display properly in object mode with cycles. So the fact it works at all is kind of a coincidence (again, everything works on render). I can look into more explicitly supporting it so you don't have to do that materials button thing.  

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook
