### ISSUE TITLE
How do I enable normal maps when importing the .obj?

### ISSUE THREAD

**Issue by Zophiekat** [TheDuckCow/MCprep#51]
I tried using the dev version of Mcprep to try realistico texture pack normals,when exporting the world with jmc it exports the normals and specularity maps, but when importing it doesnt, I tried prepping materials and swapping texture packs but got no luck :(

**Comment by Zophiekat** [comment]
Alrighty here it is :)

btw, how does mesh swapping works? like what if I have extrusions on a crafting table? is it per face and material?

Texture pack:
https://minecraft.curseforge.com/projects/realistico

**Comment by TheDuckCow** [comment]
@Zophiekat Thanks. Give me maybe a day and I'll debug and update the dev branch to have it working. Looks like a good reference pack to try it on, so thanks for sharing. 

Meshswapping is an entirely different process. It simply looks for blocks in the world export (e.g. Enchantment Tables), then completely deletes those faces from the world export, and then appends-in-place the corresponding asset which is found in the meshswap blend file. So it's really just swapping the simple mesh for a pre-made unique mesh.

**Comment by TheDuckCow** [comment]
I'd refer to [this very old video for a reference](https://www.youtube.com/watch?v=Nax7iuCTovk) - any block would be replaced fully. It's not perfect, so e.g. if you added a custom half slab, it probably right now won't properly replace it like you'd hope. Honestly, the most common use case is swapping in better grass (pre-animated), and a few other things that work better with lights or are animatable like torches. Doesn't mean I can't plan to improve it further though.

**Comment by TheDuckCow** [comment]
Closing this issue for now with the latest release of 3.1.0 out, which permits the use of normal maps via prep materials. Let me know if you ended up having any other troubles, and definitely give the updated addon a try
