### ISSUE TITLE
Can MeshSwap replace stairs?

### ISSUE THREAD

**Issue by Zophiekat** [TheDuckCow/MCprep#52]
I was working with some 3D blocks models and was wondering if MeshSawp works with stairs? since they have their own direction which they are facing, would that affect the rotation of the block model? what if there's a corner with a stair pattern made out of different stair bends? they are a single object,

is there a way to separate blocks by North, South, West, East, Material not block type, and Bend direction before importing?

<img width="730" alt="screenie1" src="https://user-images.githubusercontent.com/42160166/44632268-6e5c5480-a92c-11e8-944a-235ce2540234.PNG">

Also, if there's a world exporter that exports blocks models and it's textures itno .obj then I wouldn't need to use MeshSwap for  this, I would create a 3D resource pack instead

**Comment by TheDuckCow** [comment]
Hey there,

To answer your question, no - stairs and similar objects are complicated like you have said, and I specifically haven't tackled them to work with MeshSwap. MeshSwap isn't intended as a tool to completely replace _all_ blocks, but a shortcut to replace a specific few that have bene pre-setup (and those ones that have been setup can be freely edited in the meshswap.blend file). 

To my understanding, you are able to use jmc2obj with custom models, but it's a bit of a manual (replacing the individual packaged models that come with jmc2obj for each block/object type). Not quite as easy as using a full resource pack, but gets close. I recommend looking there as a starting point if this is what you wish to achieve.
