### ISSUE TITLE
I cant get this to work please help

### ISSUE THREAD

**Issue by Creepus07** [TheDuckCow/MCprep#53]
A friend of mine sent me the .blend file to render and export his animation cause ive got a better pc. Everything was pink without textures so i added mcprep but all textures that came with it are alex steve and redsirt. Please how do i get the teaxtures to load?

**Comment by TheDuckCow** [comment]
Tell your friend to first: save the blend file, go to file>external> press pack all images (there may be some error popup a... ignore them), then send the blend file. This way all of the textures are maintained inside the blend file itself (note - if there are image sequences or videos, this won’t work). 

Let me know if that solves the problem. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
@Creepus07 did the comment above help out? Closing the issue for now since it's more of a blender texture management thing than an MCprep specific issue, but happy to keep helping here if needed.
