### ISSUE TITLE
Why is there an error 

### ISSUE THREAD

**Issue by Crashbandit04** [TheDuckCow/MCprep#55]
![screenshot 14](https://user-images.githubusercontent.com/43712181/46251453-50997800-c421-11e8-8d2f-68860bd72341.png)
 Why is there an error when I try to enable it and plz tell me now

**Comment by Crashbandit04** [comment]
Fixed

**Comment by TheDuckCow** [comment]
Glad to hear it's fixed - what did you have to do to fix it, if I might ask? and was this with version 3.1.0?

**Comment by Crashbandit04** [comment]
I removed it then close blender then added it back
