### ISSUE TITLE
MeshSwap not changing .blend source

### ISSUE THREAD

**Issue by Zophiekat** [TheDuckCow/MCprep#58]
I tried to change the .blend source of where McPrep grabs the blocks to MeshSwap with, but for some reason it is displaying my .blend directory while it's still getting the blocks from the original MeshSwap file.

![aa2e28b716912f854dff59521c9b46d8](https://user-images.githubusercontent.com/42160166/48296449-e4605a00-e44b-11e8-9798-15be3268d27c.gif)

Here I showed how it wouldn't let me replace this block, then the file directory of where it should be getting it, and last tried to add it with Shift + A and it showed all the blocks in the original MeshSwap .blend which there's none in my new custom .blend

I made sure to keep my object's name and material to match the ones in the world export

**Comment by TheDuckCow** [comment]
Thanks for your message. I recently fixed this bug in the dev version of MCprep, essentially the UI in the 3D view panel was showing the “default” setting as opposed to the actively used scene meshswap path. 

It’ll be another week or so most likely before the next MCprep is out, but if you really want to use custom mesh swapping right now, you can do this:

1) open up a python console window (eg change one of the layouts like the 3D view or other, and select python console)
2) type this exactly into this black-backgrounded:

bpy.context.scene.meshswap_path =

And then, drag and drop the blend file into this black background window, it should populate the path inside quotes. After this, it should work! (Let me know if not). 


Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook
