### ISSUE TITLE
Mesh Swap not working in Blender 2.77

### ISSUE THREAD

**Issue by RarePika** [TheDuckCow/MCprep#6]
In MCprep 2.1.3, meshswap was fixed in Blender 2.76. Now that Blender 2.77 is out, it needs fixing again. Please update soon! Thanks!

**Comment by TheDuckCow** [comment]
On what way is it broken, what was working and then stopped? Screenshots can be useful too, thanks. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Closing due to staleness, my most recent tests indicate meshseapping currently works as intended.
