### ISSUE TITLE
MeshSwap not working

### ISSUE THREAD

**Issue by BluSpring** [TheDuckCow/MCprep#61]
![image](https://user-images.githubusercontent.com/20620191/50143129-c3aae000-02e6-11e9-8758-84325c044a1e.png)

MeshSwap doesn't seem to want to work for me right now. The error's in the image.
MCPrep: v3.1.1
Blender: v2.79b
Note: I just updated it.

**Comment by TheDuckCow** [comment]
Thanks for sharing. Looks like there’s two errors occurring and I’m not able to see the source from the screen shot. Any chance you could open your file again, and then open the Header window > Window > Show console window? Then press meshswap again and then finally take a screenshot of that console window (with the error). 

Best regards,
Patrick

**Comment by TheDuckCow** [comment]
Long time follow up, did you get a chance to try the above, or ever get it working (e.g. on another version of blender)?

**Comment by TheDuckCow** [comment]
Closing this issue for now, still unsure of the true original issue, but if it surfaces again in the future, please report (via the popup & report error button if that appears) or by commenting back here.
