### ISSUE TITLE
Unable To Enable MCPrep

### ISSUE THREAD

**Issue by vonvrona** [TheDuckCow/MCprep#62]
So I finally decided to update to the latest version, however when I installed it, I've seen I no longer have the MCPrep tab. It turns out it wasn't enabled and I can't enable it no matter what. Here's the error it produces whenever I try to click the box:
![image](https://user-images.githubusercontent.com/46051108/50346971-feea2080-052b-11e9-9ce9-7a76f90a347f.png)

**Comment by patik225** [comment]
Have the same problem...

**Comment by toneelspeler** [comment]
I' ve the same problem and I can' t delete the addon cuz then I' ll get the error again.

**Comment by TheDuckCow** [comment]
I might suggest that you completely remove the addon by expanding it (click the triangle, not the tick box) and pressing remove; if that doesn't work, then you can even more manually delete it by going to the path it shows.

Then, **close** Blender entirely, download the most recent version (v3.2.0), and try installing that. There was a recent update so the issue may be fixed now.

**Comment by TheDuckCow** [comment]
Follow up for everyone having this issue, please try the latest version of MCprep recently release - version 3.2.0. Make a note to **close** blender completely _after_ installing MCprep's update, and then open it again to see if everything is working. Comment back if you find you still have an issue!

**Comment by ThePoptartCrpr** [comment]
Was getting this same error after installing 3.2.0, closing and reopening Blender fixed. Strange issue.

**Comment by TheDuckCow** [comment]
Okay, closing out this issue - the main takeaways is **always** restart blender after installing an update to an addon (not just MCprep); python modules don't always properly reload themselves, so this is always the safest thing to do.

Errors like this will especially pop up if new files are added or renamed in the newly updated addon, which are resolved once blender restarts as python modules are completely reloaded from file.
