### ISSUE TITLE
Syntax error when trying to enable MCprep

### ISSUE THREAD

**Issue by Broukodrak** [TheDuckCow/MCprep#632]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

I need to install the MCprep addon for Minecraft animating, but when i try to turn it on, i get this error: 

![issue](https://github.com/user-attachments/assets/38639a82-85d0-44d8-8223-10429021a6a6)

### What steps are needed to produce the bug?

1. Download Blender 2.7 there: https://download.blender.org/release/Blender2.70/ (the lowest .exe file)
2. Download MCprep 3.6.1
3. In Blender, go to File/User Preferencer/Addons, click Install from file, choose the MCprep zip file.
4. On the left sidebar in Addons click on User and mark the box in Object: MCprep.
5. You might get the error.

### What version of MCprep are you using?

MCprep 3.6.1

### What version of Blender are you using?

Blender 2.7

**Comment by Aspirata** [comment]
Mcprep 3.6 doesn't support Blender 2.7

**Comment by Aspirata** [comment]
Download Mcprep 3.4.3 or 3.2.4 instead

**Comment by StandingPadAnimations** [comment]
Blender 2.7 support hasn't been in MCprep since 2020, and the last versions of 2.7X we supported (2.78 and 2.79) were dropped in 2023. The syntax error is due to us using Python type annotations in MCprep now, which were added in Python 3.7 (which was not shipped with Blender until Blender 2.8).

See [here](https://github.com/Moo-Ack-Productions/MCprep/issues/399) for the rationale

**Comment by Broukodrak** [comment]
> Download Mcprep 3.4.3 or 3.2.4 instead

I downloaded 3.4.3, when i marked the box i got this:
![huh](https://github.com/user-attachments/assets/11abeffb-067b-4cf6-bde6-7a96ad3aa046)

**Comment by StandingPadAnimations** [comment]
Since you're on 2.70, 3.4.3 won't work either (that only goes as far back as 2.78). You'll need 3.2.4 for Blender 2.70 support
