### ISSUE TITLE
There should be a variant slider

### ISSUE THREAD

**Issue by AJSquaredMediaGroup** [TheDuckCow/MCprep#634]
There should be a variant slider 
![image](https://user-images.githubusercontent.com/75058058/125868612-d4fb843e-fadc-423d-acd3-e36eb4b4ff12.png)

_Originally posted by @StandingPadAnimations in https://github.com/Moo-Ack-Productions/MCprep/issues/227#issuecomment-881064471_

**Comment by StandingPadAnimations** [comment]
Closing since this doesn't use the feature request template. Also redundent since it's already referenced in another issue

**Comment by AJSquaredMediaGroup** [comment]
hi, i used as reference because im using the last mcprep version which is different than the one used on the first request
