### ISSUE TITLE
All textures turn solid white after prepping materials and exporting

### ISSUE THREAD

**Issue by Terimiyo** [TheDuckCow/MCprep#640]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

Hello, I've tried to import a part of my old Minecraft world into Blender with the use of jMc2Obj and MCprep. All went well until I prepped the materials with MCprep and exported it. I am sure it's a problem with MCprep as fresh import from jMc2Obj shows in Blender correctly textured even after exporting and importing it again. 
![FreshImport](https://github.com/user-attachments/assets/283c106b-0efe-4db0-afd5-24bb22b30953)

The problem only happens when I hit prep materials and export. I tried exporting as .obj and .fbx, joining meshes and leaving them separate, but nothing helped.
![ExportedImport](https://github.com/user-attachments/assets/a4b10798-671b-4105-8caf-450c9e647b54)

Exporting as .obj does create an .mtl file which should store all the required materials, and the materials are there in blender too, they just turn white for some reason.
![MaterialList](https://github.com/user-attachments/assets/c548a2e7-5fef-4984-a258-4ac292d64836)

Using Blender 4.2.3 and MCprep 3.6.1.2 btw

### What steps are needed to produce the bug?

1. Export .obj file of your world in jMc2Obj
2. Import it inside Blender
3. Prep materials using MCprep
4. Export as .obj or .fbx
5. Import your exported file back into Blender

### What version of MCprep are you using?

MCprep 3.6.1.2

### What version of Blender are you using?

Blender 4.2.3

**Comment by StandingPadAnimations** [comment]
Did you enable Material exports when exporting from Blender? If so, it might be related to how Blender exports materials in general for OBJ (OBJ is limited when it comes to materials, so Blender can't export everything)
![image](https://github.com/user-attachments/assets/927d8c07-62d6-4b9e-919c-529f55e26d36)

I'll close this issue since this isn't an MCprep-side issue (OBJ *exporting* is handled by Blender, not MCprep), but you'll still be able to comment.

**Comment by Terimiyo** [comment]
Yes, I have enabled it, but I still get the same result. The .mtl file gets created on export, but all the materials turn white after export. I get the same result when exporting as .fbx too so I imagine it's probably not an .obj file issue. I've recorded a short video showing the results exporting with and without using MCprep: https://www.youtube.com/watch?v=55mSwkhbqcs
