### ISSUE TITLE
Spawned vegetation can't be preped

### ISSUE THREAD

**Issue by Aspirata** [TheDuckCow/MCprep#642]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When I click “prep materials” on a spawned leaves block, vines or any other “gray stuff”, nothing happens.

### What steps are needed to produce the bug?

1) Spawn Acacia Leaves 
2) Press "Prep Materials"

### What version of MCprep are you using?

Mcprep 3.6.1.2

### What version of Blender are you using?

Blender 4.3.1

**Comment by zNightlord** [comment]
Resolved. [6c30be5](https://github.com/Moo-Ack-Productions/MCprep/commit/6c30be52d0fba65ce374003602f5b3fb4fa452b5)
