### ISSUE TITLE
Spawning custom rigs/assets with mob spawner overrides material with prepped material

### ISSUE THREAD

**Issue by Zophiekat** [TheDuckCow/MCprep#65]
i use the mob spawner for adding rigs and assets into my scene (saves a lot of time compared to navigating through a folder when appending) but i recently found out that the original material of all the objects in the group get replaced or pre-prepped when adding them into the scene.

Prepped material when spawning rig
![screenie96](https://user-images.githubusercontent.com/47702767/52906105-6950d180-31fa-11e9-9530-d03103565ca0.PNG)

material in original .blend
![screenie97](https://user-images.githubusercontent.com/47702767/52906106-6c4bc200-31fa-11e9-862c-45e2adb4e2f2.PNG)

**Comment by TheDuckCow** [comment]
Correct me if I’m wrong, but in the spanwer popup there should be a checkbox for “prep materials” defaulted to on; turn this off, and it will leave your original materials/node groups. 

Let me know if that doesn’t do the trick!

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by Zophiekat** [comment]
ooohh.. i didnt know there was such a thing lol, (sorry!) just tried it and indeed there is and it works, i didnt expect for it to be like that, i kinda expected to be similar to prepping materials where a box would pop up after clicking the prep button

![screenie98](https://user-images.githubusercontent.com/47702767/52906414-45908a00-3200-11e9-9c8f-12af277468ed.PNG)
if this is how it is supposed to look like thennn.. yup it works and that pretty much solves my problem.

Thank you!

**Comment by TheDuckCow** [comment]
yes, that’s how it’s supposed to work. I’ve gone a bit back and forth with different versions of MCprep where Mob Spawner would have a popup or just have these F6/Redo last menu settings for mob spawning. I liked not always having a popup in case someone wanted to quickly, one-click add a bunch of Mobs (and you’ll notice once you set the settings one way, it will keep that way until you change them again within the same blender session). But as you experienced, the drawback is that the settings are a bit more hidden and some might not realize the options are there.

So, any feedback or suggestions to me would be well received!


Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com <https://theduckcow.com/>
youtube <http://www.youtube.com/TheDuckCow>, twitter <https://twitter.com/TheDuckCow>, facebook <https://www.facebook.com/TheDuckCow>

**Comment by TheDuckCow** [comment]
Closing issue in the meantime - but again, your feedback would be very valuable - alternatively (or in addition) to feedback here, you could also consider filling some of this out: http://bit.ly/MCprepSurvey
