### ISSUE TITLE
MCprep 2.8 bug?

### ISSUE THREAD

**Issue by krentil** [TheDuckCow/MCprep#67]
Hi, i love MCprep i used it many times in the past. I saw your post on twitter about new version for blender 2.8. So I immediately wanted to try it. But when I try to install and than enable it in blender  im getting this error. 
![image](https://user-images.githubusercontent.com/23291628/55030763-52797800-500d-11e9-97b7-68f880f12011.png)

**Comment by TheDuckCow** [comment]
Thanks for reporting this. Can you try the following:

1) Completely remove the addon, close blender, and then install it again. Also check if somehow you have multiple mcprep folders in the addon folder for 2.8
2) if the error occurs still, still close blender without removing the addon, and try opening and enabling again
3) if still not working, try with an even more recent version of blender 
4) if that all doesn’t work, I’m sorry! Please give me info like the operating system and version, and the specific build of blender 2.8. 
4b) the code actually should also work in blender 2.79, so see if it installs properly there (let me know either way)

Patrick

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by krentil** [comment]
Hi, heres update. IT WORKS!!! Thank you so much. The issue acours only in this version of blender "blender-2.80-adfdae3fc2f4-win64". And today i have downloaded new version of blender "blender-2.80.0-git.532536bf52da-windows64" and its works and there is no issues. 
![image](https://user-images.githubusercontent.com/23291628/55100548-67641300-50c2-11e9-9bc8-009cb6326320.png)

**Comment by TheDuckCow** [comment]
Glad to hear it is working. By chance the most most recent version of 2.8 actually does break it, so... if it’s working right now, don’t change your version of 2.8 for s little bit while I try to catch up with the Blender Foundation!

**Comment by BGP19000** [comment]
I have the same problem, where can I download blender-2.80.0-git.532536bf52da-windows64?

**Comment by Abuws** [comment]
> I have the same problem, where can I download blender-2.80.0-git.532536bf52da-windows64?

Same!

**Comment by Abuws** [comment]
> Glad to hear it is working. By chance the most most recent version of 2.8 actually does break it, so... if it’s working right now, don’t change your version of 2.8 for s little bit while I try to catch up with the Blender Foundation!
> […](#)
> On Mar 27, 2019, at 14:03, krentil ***@***.***> wrote: Hi, heres update. IT WORKS!!! Thank you so much. The issue acours only in this version of blender "blender-2.80-adfdae3fc2f4-win64". And today i have downloaded new version of blender "blender-2.80.0-git.532536bf52da-windows64" and its works and there is no issues. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

![image](https://user-images.githubusercontent.com/40725969/55597887-b9311c80-5704-11e9-97db-af9be0049234.png)

**Comment by Abuws** [comment]
> > Glad to hear it is working. By chance the most most recent version of 2.8 actually does break it, so... if it’s working right now, don’t change your version of 2.8 for s little bit while I try to catch up with the Blender Foundation!
> > […](#)
> > On Mar 27, 2019, at 14:03, krentil ***@***.***> wrote: Hi, heres update. IT WORKS!!! Thank you so much. The issue acours only in this version of blender "blender-2.80-adfdae3fc2f4-win64". And today i have downloaded new version of blender "blender-2.80.0-git.532536bf52da-windows64" and its works and there is no issues. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> ![image](https://user-images.githubusercontent.com/40725969/55597887-b9311c80-5704-11e9-97db-af9be0049234.png)

YOOOO Somehow i got it to work. I was giving up until I opened blender as a admin and it worked <3

**Comment by TheDuckCow** [comment]
Thanks for sharing that update. Out of curiosity, do you need to always start blender as admin now, or (after completely closing blender at least once) does it start working even without admin after that first install?

**Comment by Abuws** [comment]
No, good question actually I just tested it. I saved my user settings and its automatically installed when open in regular and admin mode.

**Comment by TheDuckCow** [comment]
In any regard, glad it's working. I'm doing some final touch updates, then hopefully releasing the next version officially soon (with many 2.8 fixes). Closing this issue for now, remember this in the future to try enabling with Admin the first time if you have issues!
