### ISSUE TITLE
Water Glitch

### ISSUE THREAD

**Issue by The-Epic-Emerald** [TheDuckCow/MCprep#68]
For some reason, when I import the world into blender everything loads except from water or lava. Please help with this issue!

**Comment by TheDuckCow** [comment]
When you say everything loads, is this before or after using MCprep functions like prep materials? Also, to let me help you, what world exporter are you using (jmc2obj or mineways), and what Verizon it MCprep?

Btw, the most recent version of MCprep (3.1.1) has a prep materials function called “reconnect missing textures” (on by default) which ideally would solve your issue. Let me know if that works, but especially let me know if it doesn’t!

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by TheDuckCow** [comment]
Just following up here - is this still an issue, or did you manage to get it working?

**Comment by TheDuckCow** [comment]
Let me know if this issue persists, closing for now but can reopen later if needed.

**Comment by The-Epic-Emerald** [comment]
I gave up
