### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seQundo** [TheDuckCow/MCprep#69]
Hey! I'm from Poland, so I'm sorry for mistakes.
I have a problem adding a texture to my world. When I click to add it, nothing happens
PHOTOS:
https://imgur.com/a/bcDMSor

**Comment by seQundo** [comment]
Please help

**Comment by TheDuckCow** [comment]
Hi there,

Sorry, looks like my response didn't submit earlier. Can you:
1) Try out the latest version of MCprep, release in the last couple days (version 3.2.0); restart blender after installing before trying anything.
2) What does the _rendered_ view of the scene look like before prepping materials? If there are no materials on the imported world to begin with, prepping materials won't really do anything. What are you importing this world from? Mineways?

**Comment by TheDuckCow** [comment]
Following up, did you manage to resolve your issue?

**Comment by TheDuckCow** [comment]
Closing for now, re-open if the issue persists.
