### ISSUE TITLE
Prep materials not working...

### ISSUE THREAD

**Issue by lbdBG** [TheDuckCow/MCprep#7]
Not working, just trying to do the end (if it does issues).

**Comment by TheDuckCow** [comment]
In what way is it not working? It may be that you're expecting it to do something other than you want. First, go into rendered view and see if the change happens there. If not, remember it only MODIFIES materials already created. It will not create lost textures or anything like that. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by iamdumb56** [comment]
I have the same issue.

**Comment by iamdumb56** [comment]
It is like when you click the prep material it does not response.

**Comment by TheDuckCow** [comment]
Check rendered view, likely it does work but there isn't necessarily a change in the viewport.

**Comment by CactusGamer** [comment]
I have the same problem, i am using windows 10 with blender 2.78 and when i click prep materials nothing happens, i have tried multiple things including what you said and nothing happens. could it be to do with the new windows/blender?

**Comment by TheDuckCow** [comment]
Can you please provide before and after screenshots of a closeup of a block in *rendered* view?

**Comment by TheDuckCow** [comment]
Closing due to staleness. @CactusGamer or @iamdumb56 reopen if you still are unable to use it, but my best understanding is that you need to verify how it looks in render mode and not just the default UI to see it working.

**Comment by themoviea** [comment]
hi
