### ISSUE TITLE
General-block model spawning

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/MCprep#77]
**Vision**

Ability to one-click add any block, not just those custom blocks stored in the meshswap file

**Approach**

- Create a reference for all major block types
- Create a mapping of material names/block names to the block types
  - Note to self: sounds very manual and will likely get out of date very often, a risk of implementing this feature. Try where possible to future proof and infer block types. 
  - Could for instance default to assume basic cube as the block model
- Support custom block models by directly reading resource pack model definitions
  - Requires implementing of UV mapping and model creation
  - Can segue this into an alternative way of running meshswap
  - Could potentially tie this in with the Mineways exporter to include custom models directly.
- Decide whether to complete deprecate the meshswap lib, make it connected per resource pack, or even merging it with the concept of the material sync library (so there's just one utility blend file, again set per resource pack).

Additional research links
- [Reddit q on loading json into blender](https://www.reddit.com/r/blenderhelp/comments/3c21gd/importing_3d_objects_formatted_as_json_files_into/) (contains links to 404 files now that would have been ideal most likely)
- This [git repo](https://github.com/warmwaffles/io_mesh_json) does the reverse, export only
- [Blender to Minecraft tool](https://www.reddit.com/r/Minecraft/comments/hdkn4p/blender_vanilla_minecraft_json_model_importexport/), and its [repo](https://github.com/phonon/blender-minecraft-json), noting this is both active (as of Oct. 2020) and appears to do what is required above. Need to test still.

**Comment by SkyDiverCool** [comment]
Is this being worked on, or maybe there is a way to do it manually?

**Comment by TheDuckCow** [comment]
Sorry for the delay @SkyDiverCool, it's not there yet, but I still have plans for it.

In the meantime, you can do this manually. If you take e.g. BoxScapeStudio's rig pack (which includes a file with all blocks), you can import the models there via the normal blender import process, or even copy those models into the meshswap blend file (in the MCprep addon folder under blender settings), and by making each block a group/collection (centered on itself), you'd be able to use the spawning like you wish.

**Comment by TheDuckCow** [comment]
Not a code update, but an encapsulation of a general +1 to this feature. An existing jmc2obj user is running into errors exporting custom resource pack models in the program directly, therefore it would be helpful to at least have MCprep directly read the models found in resource packs.

Generally this request is inline with the core request here. One side thought this generates, is potentially the ability to use MCprep to more quickly and rapidly author and test Minecraft resource packs by exporting models from Blender, as it essentially would be using the same engine (but in reverse).

TODO: Collect reference resource packs with custom models to start exploring.

**Comment by TheDuckCow** [comment]
While the main branch is merged, some work remains to add test runners for this, do some style cleanup, and add a UI and spawner code for it. Will keep this issue open until that is done.

**Comment by TheDuckCow** [comment]
Closing this now as the feature is now polished with a UI wrapped around! Any future bugs or improvements can be added with new issue reports.
