### ISSUE TITLE
Item Spawner Not functioning

### ISSUE THREAD

**Issue by Kickdevil123** [TheDuckCow/MCprep#79]
When I attempt to use the MCPrep item spawner, I get a simple 'File not Found' message. Not sure why this is. There is not a directory for item files in the preferences, and in the MCPrep folder, all of the item assets are present.

**Comment by TheDuckCow** [comment]
Sorry you are having the issue. Does it persist even after closing and reopening blender? Try also saving your current file, closing, and then running refresh all spawners (image below).
![reload items](https://user-images.githubusercontent.com/2958461/62621362-ab291d80-b8e9-11e9-91ae-0da9fe9149da.png)

Do the images previews for the items at least load? Note that the items are pulled in by the "resource" pack that comes with MCprep, and you can change this via changing the Texture Pack in user preferences as well as the spawner panel in the screenshot above.

Let me know if this helps.

**Comment by Kickdevil123** [comment]
Hitting 'Reload items' seems to have fixed my issue with that. I honestly do not know how I missed that. Thanks a lot!
