### ISSUE TITLE
my MCprep addon wont go into blender it is just in my file and i cant tick the add icon

### ISSUE THREAD

**Issue by piggyDinoLover** [TheDuckCow/MCprep#8]

**Comment by mcccs** [comment]
Screenshot?

**Comment by TheDuckCow** [comment]
Yeah, @piggyDinoLover I'm not sure what that means exactly. Make sure you download the .zip file as indicated on the [releases](http://bit.ly/MCprep) page and ensure it stays as a .zip, then install from the "install" button at the bottom of the addons preferences page.

**Comment by TheDuckCow** [comment]
Closing for now due to staleness, plus new version coming out greatly improves compatibility.
