### ISSUE TITLE
blender 2.8 world import issue

### ISSUE THREAD

**Issue by Busy-GamerRS** [TheDuckCow/MCprep#81]
So I just downloaded blender 2.8. I got all my settings setup that I remembered for 2.78 and got MCprep installed. I imported my OBJ using Mineways and prepped materials. I figured out how to separate items by materials but how do I work with each individual block in object mode?  For example, say I have tons of dirt blocks and I want to be able to move each of those separately in object mode, how do I do that? Right now I can only figure out how to separate it by material therefore I can't move them around individually.

P.S new to blender btw.

**Comment by TheDuckCow** [comment]
Yes I see the same issue, this appears to be an issue/change in the obj importer script (so, outside the control of MCprep). If needed, you can still go into edit mode of your world, press p, and then select separate by material, this will split into the separate objects you need.

**Comment by Busy-GamerRS** [comment]
Yeah, I already did that. Well thank you for the quick reply :) at least I know what I need to work with now :)
