### ISSUE TITLE
AttributeError: module 'MCprep_addon_util' has no attribute 'get_user_preferences'

### ISSUE THREAD

**Issue by Paulux06** [TheDuckCow/MCprep#85]
Then I try to enable MCprep 3.2.0, it shows me this error message:

![img](https://user-images.githubusercontent.com/45801364/64489296-b907f080-d251-11e9-880a-194a5dbbe680.jpg)

What can I do to fix it ?

**Comment by TheDuckCow** [comment]
Can you try removing the addon, closing blender (don't skip this step!), and then re-opening and installing the addon? This looks like an error that would be similar to a caching issue from a previous version being installed. Let me know if you still have troubles!

**Comment by Tianerad** [comment]
Yeah! Something happed just like that to me, and I download a previous version before, and it wont let me enable it.

**Comment by Tianerad** [comment]
It works! Your description worked! Thanks TheDuckCow!

**Comment by TheDuckCow** [comment]
Glad to hear it! Let me know if you run into any other issues. In general, when installing a new version of an addon, it's a good idea to close blender after installing the update!
