### ISSUE TITLE
[SOLVED] It won't let me Enable the Add-on! (3.2.1)

### ISSUE THREAD

**Issue by Tianerad** [TheDuckCow/MCprep#87]
![Screen Shot 2019-09-13 at 11 16 38 PM](https://user-images.githubusercontent.com/55308128/64903800-cf141780-d67c-11e9-8dbb-3a8b0c80c6a9.png)

It says that I need to enable and register something and won't let me enable the addon, please fix this! I love your addon and will contuine using it. Thanks for reading!

-Tianerad 999

**Comment by Tianerad** [comment]
Hey! If this happens to you, remove the add-on, close blender, reopen it, and install the add-on again, and then enable it, and it should work!

**Comment by TheDuckCow** [comment]
Thanks for sharing your solution. Out of curiosity, was this happening the first time you installed MCprep, or did you already have MCprep installed before on that version of Blender? (ie you were updating it)?

**Comment by Tianerad** [comment]
I already had it installed, and wanting to use the new version, with the
textures and all. :)
