### ISSUE TITLE
Import Error with Blender 2.8

### ISSUE THREAD

**Issue by RPGFabi** [TheDuckCow/MCprep#88]
I tried to import the Add-On. As soon as I enable it, i get following error Message. What am I'm doing wrong.
MCPrep Version: 3.2.1

![grafik](https://user-images.githubusercontent.com/35190886/65409188-5da83780-dde7-11e9-96b3-398d514bcd86.png)

**Comment by TheDuckCow** [comment]
Thanks for flagging! Just to check, this is your first time trying to use MCprep in Blender 2.8?

Separately, it looks like you might be using a daily build. Can you try using the officially released Blender 2.80, and see if that works?

Other information would be helpful, including the splashscreen screenshot and what operating system you are on.

**Comment by RPGFabi** [comment]
Checking it today evening.

Yes it is my first time using ur AddOn. 

Windows 10

what Splashscreen?

**Comment by TheDuckCow** [comment]
Sorry for the delay, essentially wanted to see the blender startup splashscreen to understand if this is an issue based on a specific build of blender. Basically, I'd recommend trying using it with an officially released version of 2.80 to start, and see if that helps solve the problem. Consider removing, closing, and then reinstalling the addon itself too.

**Comment by TheDuckCow** [comment]
Just following up, what version of Blender were/are you using? Do you still have this issue?

**Comment by TheDuckCow** [comment]
Closing this for now as I think it was a reloading issue. Let me know if you run into anything else.
