### ISSUE TITLE
Newer jmc2obj compatibility?

### ISSUE THREAD

**Issue by mcccs** [TheDuckCow/MCprep#9]
The new export window is very different.

![](https://cloud.githubusercontent.com/assets/20167871/19628567/6210e3e6-9969-11e6-83d5-cfbcdd81e51d.png)

Can you please add newer settings' screenshot to README?

**Comment by TheDuckCow** [comment]
Thanks, I will work on this. In the meantime, you should find at least the highlighted options / names should be about the same and assign settings based on this.

**Comment by mcccs** [comment]
![1](https://cloud.githubusercontent.com/assets/20167871/19646809/d8fe764a-9a03-11e6-909b-981eff9c02ef.png)

I'm not sure about "occlude different adjacent materials" and "export threads (max value.)"

**Comment by TheDuckCow** [comment]
Occlude is optional, threads doesn't matter - that's just how many processing threads are used to do the export. 2 or 4 is probably safe but honestly the program should be able to auto detect the number of cores you have.

**Comment by TheDuckCow** [comment]
Occlude is optional, threads doesn't matter - that's just how many processing threads are used to do the export. 2 or 4 is probably safe but honestly the program should be able to auto detect the number of cores you have. 

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by mcccs** [comment]
No, when you launch that for the first time, the number of threads is 1.

**Comment by TheDuckCow** [comment]
Regardless, it doesn't matter. If you want to be safe, use 1 - just means it will take a little bit longer to process than potentially the optimal.

**Comment by TheDuckCow** [comment]
Closing as newest version coming out does have the updated diagrams, v3.0.1
