### ISSUE TITLE
Greyscale textures for water

### ISSUE THREAD

**Issue by bundabrg** [TheDuckCow/MCprep#90]
First time I'm trying this plugin so I may well be doing something silly.

I am having issues where water appears grey.

OS: Linux (Ubuntu 19.04)
Blender: 2.79b
MCPrep: 3.2.1
jmc2obj: 107
minecraft: Both 1.13.2 and 1.14.4 worlds tried.

I do the following: 
1. Export both the map and textures using jmc2obj.
2. Run blender and set engine to cycles and display to 'textures' in 3dview.
3. Using the MCPrep tab I import in blender using the mcprep open world obj. The map loads and everything looks mostly fine (water is blue for example)
4. I then select all and click 'Prep materials'. Now the water turns grey. 

![image](https://user-images.githubusercontent.com/1607029/66365612-32fdd780-e9c0-11e9-8a56-eaf18d26d52d.png)

5. Adding a sun and then render using cycles gives the following

![image](https://user-images.githubusercontent.com/1607029/66365662-5c1e6800-e9c0-11e9-874f-e5e6284a1e92.png)

What am I doing wrong :( I am in RGBA.

**Comment by TheDuckCow** [comment]
Hi there! Thanks for giving the addon a try. Can you try going into rendered mode, or actually rendering the image?

The issue, if you want to call it that, is that indeed the source water textures from a resource pack are grey (so they may be custom colored per biome), and in textured view blender will only directly show the raw texture itself. However, MCprep should already setup for you extra shaders that add the blue back in for rendered view.

Let me know if that seems to not work!

**Comment by bundabrg** [comment]
Thanks for the reply. I'm muddling my way through blender but its something I've been wanting to learn for years.

The second image I posted is from a fully rendered view (Pressing the Render button). Perhaps there's a step I'm missing?

**Comment by TheDuckCow** [comment]
Gotcha, based on what you described you've done everything correctly, especially odd since it starts as blue and then changes. 

One question: Are you using a custom texture pack? And does the issue persist if you don't use it, and instead use default Minecraft textures from jmc2obj?

Beyond that, to further debug, could you either 1) share a screenshot of what the water node shader looks like? or 2) send me the blend file you have as-is to investigate further. You should be able to upload here if it's not too big; would be also helpful if you packed the files (file > External data > pack into blend file).

**Comment by bundabrg** [comment]
Thanks. To answer your question I started with a custom but when it failed I threw everything out and redid with everything standard. I'll do that again now and log my steps with all relevant material attached.

## 1. Cleaning up (just in case)
* Uninstall MCPrep from blender (which removes everything from ~/.config/blender/scripts/addons except for mcprep_addon_trackerid.json)

## 2. New World
* Open Minecraft, create new world and save

## 3. Install MCPrep
* Open Blender, User Prefs, Addons, Install Addon from file, Choose "MCprep_addon_v3.2.1.zip"
* Tick it, Safe settings

## 4. Use jmc2obj
![jmc2obj](https://user-images.githubusercontent.com/1607029/66442948-be827180-ea6f-11e9-9a61-505512da3506.png)

* Execute "java -jar jmc2obj-107.rar"
* Browse to the new world I created
* Click Load
* Select region + set floor
* Export
* Export textures from Minecraft to: folder/textures/
* Export selection to: folder/world.obj

## 5. Import to Blender
* Select 'jmc2obj' as exporter, click 'OBJ world import', open world.obj
![blender1](https://user-images.githubusercontent.com/1607029/66442961-ccd08d80-ea6f-11e9-9f44-5f10e7f43c70.png)
* View water shader nodes
![blender2](https://user-images.githubusercontent.com/1607029/66442965-d3f79b80-ea6f-11e9-89db-50ea6d1d7a29.png)
* Select everything, then Prep Materials
![blender3](https://user-images.githubusercontent.com/1607029/66442969-dce86d00-ea6f-11e9-8896-52c0acbec674.png)
![blender4](https://user-images.githubusercontent.com/1607029/66442974-e540a800-ea6f-11e9-9c61-ea60920cc129.png)
* Set camera position
![blender5](https://user-images.githubusercontent.com/1607029/66442978-ec67b600-ea6f-11e9-99f5-fc9f7ee4fa7a.png)
* Render scene
![blender6](https://user-images.githubusercontent.com/1607029/66442987-f25d9700-ea6f-11e9-85b0-d98254bfab76.png)
* Pack data. This resulted in errors of missing files all with _a.png. I presume they are alpha channels 
![blender7](https://user-images.githubusercontent.com/1607029/66442995-fbe6ff00-ea6f-11e9-8612-df27d5c70acc.png)
.

## Debugging
As the _a files were missing I reexported textures from jmc2obj but ticked "Export alpha channel in separate files" and redid all the blender steps. This resulted in a file that packs all data without issue. I've attached that here. Unfortunately it still results in the grey water in render.

[test3.zip](https://github.com/TheDuckCow/MCprep/files/3705055/test3.zip)

**Comment by TheDuckCow** [comment]
For a short term fix, I suggest you go into the nodes and simply adjust the "Add Color" node; unmute it (select it and press m), then expand, and change the Color2 color to be any shade of blue you desire. This will work even if you use the animate textures on the water (a button under advanced). As for the code, looks like I need to do more to ensure it detects if the source water image doe shave saturation or not, and enable this node when needed.

![add blue](https://user-images.githubusercontent.com/2958461/66478724-fcc86280-ea68-11e9-8964-35456c83214d.png)
by step troubleshooting, it's very helpful!
Let me know if you have any other troubles in the meantime, thanks for the clear step

**Comment by bundabrg** [comment]
Thanks for the help. I might just sit down and also learn more about the shader nodes and compositor as well so they're less of a black box.

Feel free to close this unless you need the issue open as a reminder.

**Comment by TheDuckCow** [comment]
Closing this now as I have finally implement more automated check for grayscale images and re-saturation. Will be included in the upcoming update.
