### ISSUE TITLE
The mouth of the creeper disappears

### ISSUE THREAD

**Issue by Lyrians** [TheDuckCow/MCprep#91]
The mouth of the creeper is displayed correctly in the window, but at the time of rendering, it disappears completely

OS: Windows 10
Blender Version: 2.8
MCPrep: 3.2.1

![Blender](https://i.ibb.co/kybxHZ4/Blender-Render.jpg)
![Blender](https://i.ibb.co/S7PftRq/Blender-EMinecraft-Renders-Blender-Creepercreeper-blend.jpg)

**Comment by TheDuckCow** [comment]
Responding back here, seems there's an issue with the creeper's viewport drivers not updating correctly in blender 2.8 (confirmed in my own install, too). However, the correct result is still seen on render for both Cycles and Eevee - noting that the shape of the creeper is controlled by the bone highlighted here (move it down to keep the frowny face). 

![control](https://user-images.githubusercontent.com/2958461/67164595-3e4eec80-f34a-11e9-8d70-cdded117278c.png)

**Comment by TheDuckCow** [comment]
This is fixed now in the latest 3.2.2 release, in that the default behavior is to ensure even in rest mode the creeper's face is in the "frown" position.
