### ISSUE TITLE
Blender closes when inserting mobs, duplicate blocks, etc.

### ISSUE THREAD

**Issue by Lyrians** [TheDuckCow/MCprep#93]
I have had a number of problems with "MCPREP" in Blender 2.8.
I leave a video with everything.

The last thing is that when wanting to make a villager appear in my work area, Blender closes.

Video: https://www.youtube.com/watch?v=lnbAD_EMxYI

**Comment by TheDuckCow** [comment]
Hi there, thanks for making the video. Running through:

- Mesh Spawner creating 2 copies of things: There is not an easy way around this right now. What is happening is 1) the raw group is imported into blender (in 2.7x this would simply be placed on the last layer), and 2) an instance is being added to where the cursor is. If you were to create more spawns of something already added, it will keep using that original group imported, so only the first time will you get a "second" one. You can hide or exclude it, but it might affect your render. 
- Torches: Similar fashion, the smoke/particle group also has to be imported. In blender 2.7x this would be placed on a different layer, in 2.8 I need to find a better way to 'hide it' without also affecting either it showing up in the viewport or in the render.
- Villager: There is one open issue addressing the [villagers specifically here](https://github.com/TheDuckCow/MCprep/issues/74), but can you let me know if the issue you face is happening with other mobs too?

Thanks for posting,
Patrick

**Comment by TheDuckCow** [comment]
Closing issue for now as other issues captures your first two bullets, and the now released 3.2.2 fixes the last point. Thanks again for reporting!
