### ISSUE TITLE
Lanterns not taken into account by Meshswap

### ISSUE THREAD

**Issue by Cyphall** [TheDuckCow/MCprep#97]
The Meshswap function doesn't create a light source for lanterns (added in 1.14).

EDIT: apparently, others light blocks are also missing.

**Comment by TheDuckCow** [comment]
Hi there,

Yes, you can see the only blocks available for meshswapping in the meshswap file packaged with MCprep. I would gladly take inputs for models as I can't keep up, and sometimes it takes some extra coding. I'm expecting to incorporate some of the models made by BoxScapeStudios, but in your own opinion, what are the most useful blocks to include? Suggesting some below:

- Lanterns
- Bells
- Campfires
- Blast furnace (and normal furnaces)
- Composter
- Fletching table
- Bee hives with pre-animated lil bees circulating (via a particle system).

Let me know what would be most important to you, maybe calling out the top 2-3 most important for you!

**Comment by Cyphall** [comment]
Hi, thanks for answering!
I would say parity with vanilla is the priority.
This includes everything that can't be transported in an obj file, such as light sources.
Everything else such as fancy 3d models is bonus.
Not having fancy stone bricks or such certainly wont harm too much. However, not having a light source emitting its light can annihilate night/interior screenshots.
Also, I believe jmc2obj already creates vanilla 3d models for non-cubic blocks.

**Comment by TheDuckCow** [comment]
Thanks for the input here, I think this is a totally fair guiding principle - will continue to focus on supporting meshswap for these light-emitting blocks, as well as those with inherently animated features (enchanting tables, etc).

Are you mostly using Eevee or Blender Internal? Just curious since, to a degree, some of the lighting issue is accomplished in cycles by using emissive materials, but this of course doesn't have the same effects in Eevee or Blender Internal.

**Comment by Cyphall** [comment]
I've been using only Cycles (I'm very interested in realistic 3D rendering techs such as path tracing) and I wanted to see what my first Minecraft world would look like with 100% realistic lightings. Unfortunately, I'm using a lot of lanterns in this world.
I would love to help you making these custom blocks but unfortunately my blender level is near 0 :/

**Comment by TheDuckCow** [comment]
Resolving this issue as I have addressed Campfires and Lanterns with the latest v3.2.3 update. Will create another issue for other blocks still needed (soul torch, end rod, ...).
