### ISSUE TITLE
Torches are misplaced by Mesh Swap

### ISSUE THREAD

**Issue by zibbozz** [TheDuckCow/MCprep#99]
The base group is wrong so all objects that use this group are misplaced.
In the first image you can see the base group and in the second image an example for the misplaced torch.

This error is occuring with MCprep 3.2.2 and Blender 2.81.16. 
![Screen1](https://user-images.githubusercontent.com/36664943/71321203-958e4c00-24b6-11ea-8416-8b2e7f85462b.PNG)
![Screen2](https://user-images.githubusercontent.com/36664943/71321205-9a530000-24b6-11ea-90ae-bb15b71d29a3.PNG)

**Comment by TheDuckCow** [comment]
Hi there, this probably happened if you moved the torch from the original location (e.g. by clearing its location). You can quickly fix it by adjusting the collection's center location, or just by visually moving the torch. so that it is fixed in the instances.

**Comment by zibbozz** [comment]
> Hi there, this probably happened if you moved the torch from the original location (e.g. by clearing its location). You can quickly fix it by adjusting the collection's center location, or just by visually moving the torch. so that it is fixed in the instances.

Yes I was able to fix this by moving the corresponing object. But the error occured right after I clicked Mesh Swap and I made sure that this is not my fault by redoing this in a new file.

**Comment by TheDuckCow** [comment]
Okay thanks for letting me know - I'm not able to reproduce, but if you find it is still happening, maybe see if you can record a video, starting from scratch with an empty blender window and go through the steps of importing the model and then meshswapping torches, will help a lot!

**Comment by zibbozz** [comment]
https://www.youtube.com/watch?v=MCeO6eCz9KQ
I hope this helps to understand the problem

**Comment by imatrixgp** [comment]
Same thing happens to me.

**Comment by TheDuckCow** [comment]
Thank you for sharing, and for making the video - very helpful. I'm still not experiencing it myself, but I'll see if I can do something to automatically reset the origin properly in a more forced way. Thanks for sharing.

**Comment by vaggvisa** [comment]
I also stumbled over this bug on my very first day trying MCprep. I used a rather basic scene with four torches. After swapping meshes, the torches are misplaced (seems to be 0.5 m off in x, y and z) and some lack emission of light. Repeated executions of mesh swap followed by undoign the action showed that it is random which of the torches emit light and which not.

**Comment by TheDuckCow** [comment]
Thanks. I've completely re-worked the meshswap file and as a part of this, I am hoping the issue is resolved. I'm working towards a new update but no immediate ETA. Thanks for your patience.

**Comment by TheDuckCow** [comment]
Hi all - v3.2.3 of MCprep is out, and while I believe this bug has been resolved, I'd love to confirm with anyone who can test their original exports. Please let me know if the issue persists (or if it's okay now)!

**Comment by zibbozz** [comment]
I checked it in two different exports and it seems like everything is working now. Thank you very much for your work :)
